// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -package=payloads -out <path>

package payloads

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	AppendRequest |
		AppendResult |
		CommitRequest |
		CommitResult |
		CreateRequest |
		CreateResult |
		Handle |
		ReadRequest |
		ReadResult |
		RevokeRequest |
		RevokeResult
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "payloads: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "payloads: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// Create is the generated descriptor for cmd.gateway.payloads.v1.create revision 1.
var Create = Command[CreateRequest, CreateResult]{c: plugin.NewValidatedCommand[CreateRequest, CreateResult]("cmd.gateway.payloads.v1.create", 1, "5e7ab3b8fa044a4c14a62842ac068f75b6ff64f8d8ab2f264bda8e40374236d1", "cmd.gateway.payloads.v1.create")}

// Append is the generated descriptor for cmd.gateway.payloads.v1.append revision 1.
var Append = Command[AppendRequest, AppendResult]{c: plugin.NewValidatedCommand[AppendRequest, AppendResult]("cmd.gateway.payloads.v1.append", 1, "0bd4f9e5bd5d9ce6153b0cdece50dc0993b52cb8b079c5396a297a7e1e1593f3", "cmd.gateway.payloads.v1.append")}

// Commit is the generated descriptor for cmd.gateway.payloads.v1.commit revision 1.
var Commit = Command[CommitRequest, CommitResult]{c: plugin.NewValidatedCommand[CommitRequest, CommitResult]("cmd.gateway.payloads.v1.commit", 1, "60a3e35c2a79aeca604f4f6099d12ab8f0b2b6c02270307d58627a5210aa67a2", "cmd.gateway.payloads.v1.commit")}

// Read is the generated descriptor for cmd.gateway.payloads.v1.read revision 1.
var Read = Command[ReadRequest, ReadResult]{c: plugin.NewValidatedCommand[ReadRequest, ReadResult]("cmd.gateway.payloads.v1.read", 1, "46427af3bee4250bd7cbdfab4b1c94d86f74f85a74a2279b2a011386b34d22d1", "cmd.gateway.payloads.v1.read")}

// Revoke is the generated descriptor for cmd.gateway.payloads.v1.revoke revision 1.
var Revoke = Command[RevokeRequest, RevokeResult]{c: plugin.NewValidatedCommand[RevokeRequest, RevokeResult]("cmd.gateway.payloads.v1.revoke", 1, "0525aff67f7d1eac044fcc724b594fe33b6433a3ca0473b039d02ce4d2fa2a39", "cmd.gateway.payloads.v1.revoke")}
