// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.

export interface Config {
  sections?: ConfigSection[]
}

export interface ConfigSection {
  id: string
  title?: string
  description?: string
}

export interface ExtensionPoint {
  name: string
  interface?: string
  description?: string
}

export interface Family {
  selector?: string
  members?: FamilyMember[]
}

export interface FamilyMember {
  id: string
  when?: When
}

export interface HostCapabilities {
  major: number
  features: string[] | null
  pluginId: string
  generation: string
  grants: Permissions
}

export interface LauncherSpec {
  kind: string
  title: string
  description?: string
  group?: string
}

export interface LifecycleOperation {
  id: string
  pluginId: string
  action: string
  state: string
  generation?: string
  reason?: string
}

export interface Manifest {
  id: string
  version?: string
  nav?: NavItem[]
  panels?: PanelSpec[]
  launchers?: LauncherSpec[]
  scopes?: string[]
  routes?: string[]
  spawn?: boolean
  binary?: string
  socket?: string
  minCoreVersion?: string
  targets?: string[]
  role?: string
  provides?: string[]
  requires?: Requirement[]
  requiresProvides?: string[]
  pricing?: Pricing
  publisher?: Publisher
  family?: Family
  when?: When
  extends?: ExtensionPoint[]
  implements?: Provider[]
  critical?: boolean
  protocol?: ProtocolRequirements
  permissions?: Permissions
  ui?: UIContribution[]
  config?: Config
}

export interface NavItem {
  id: string
  label: string
  icon?: string
  href: string
  order?: number
}

export interface PanelSpec {
  id: string
  kind: string
  url: string
  module?: string
  documentPaths?: string[]
}

export interface Permissions {
  publish?: string[]
  subscribe?: string[]
  request?: string[]
}

export interface PresentationBadge {
  readonly label: string
  readonly icon?: string
}

export interface PresentationGroup {
  readonly id: string
  readonly label: string
}

export interface PresentationItem {
  readonly terminalId: string
  readonly agentId?: string
  readonly displayName?: string
  readonly groupPath: readonly PresentationGroup[]
  readonly badges: readonly PresentationBadge[]
  readonly priority: number
  readonly freshness: 'fresh' | 'stale' | 'unknown'
}

export interface PresentationLease {
  readonly hostEpoch: string
  readonly pluginId: string
  readonly providerId: string
  readonly generation: string
  readonly subjectLease: string
  readonly requestId: string
  readonly viewRevision: string
}

export interface PresentationRequest {
  readonly lease: PresentationLease
  readonly terminals: readonly PresentationTerminal[]
}

export interface PresentationResult {
  readonly lease: PresentationLease
  readonly maxAgeMs: number
  readonly items: readonly PresentationItem[]
}

export interface PresentationTerminal {
  readonly terminalId: string
  readonly context: TerminalBindingContext
}

export interface Pricing {
  model: string
  sku?: string
  trialDays?: number
}

export interface ProtocolRequirements {
  major: number
  required?: string[]
}

export interface Provider {
  point: string
  id: string
  priority?: number
}

export interface Publisher {
  id: string
  name: string
  url?: string
}

export interface Requirement {
  id: string
  version?: string
}

export interface RuntimeSnapshot {
  epoch: string
  revision: string
  plugins: RuntimeStatus[] | null
}

export interface RuntimeStatus {
  id: string
  installed: boolean
  desiredState: string
  observedState: string
  available: boolean
  generation: string
  reason?: string
}

export type TerminalBindingContext =
  | { readonly kind: 'none'; readonly tmux?: never }
  | { readonly kind: 'tmux'; readonly tmux: TmuxPresentationContext }

export interface TmuxPresentationContext {
  readonly repositoryKey: string
  readonly serverKey: string
  readonly serverPid: string
  readonly sessionId: string
  readonly sessionCreated: string
  readonly paneId: string
  readonly panePid: string
}

export interface UIContribution {
  id: string
  slot: string
  panelId?: string
  command?: string
  label?: string
  icon?: string
  priority?: number
}

export interface When {
  os?: string[]
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isConfig(value: unknown): value is Config
export declare function isConfigSection(value: unknown): value is ConfigSection
export declare function isExtensionPoint(value: unknown): value is ExtensionPoint
export declare function isFamily(value: unknown): value is Family
export declare function isFamilyMember(value: unknown): value is FamilyMember
export declare function isHostCapabilities(value: unknown): value is HostCapabilities
export declare function isLauncherSpec(value: unknown): value is LauncherSpec
export declare function isLifecycleOperation(value: unknown): value is LifecycleOperation
export declare function isManifest(value: unknown): value is Manifest
export declare function isNavItem(value: unknown): value is NavItem
export declare function isPanelSpec(value: unknown): value is PanelSpec
export declare function isPermissions(value: unknown): value is Permissions
export declare function isPresentationBadge(value: unknown): value is PresentationBadge
export declare function isPresentationGroup(value: unknown): value is PresentationGroup
export declare function isPresentationItem(value: unknown): value is PresentationItem
export declare function isPresentationLease(value: unknown): value is PresentationLease
export declare function isPresentationRequest(value: unknown): value is PresentationRequest
export declare function isPresentationResult(value: unknown): value is PresentationResult
export declare function isPresentationTerminal(value: unknown): value is PresentationTerminal
export declare function isPricing(value: unknown): value is Pricing
export declare function isProtocolRequirements(value: unknown): value is ProtocolRequirements
export declare function isProvider(value: unknown): value is Provider
export declare function isPublisher(value: unknown): value is Publisher
export declare function isRequirement(value: unknown): value is Requirement
export declare function isRuntimeSnapshot(value: unknown): value is RuntimeSnapshot
export declare function isRuntimeStatus(value: unknown): value is RuntimeStatus
export declare function isTerminalBindingContext(value: unknown): value is TerminalBindingContext
export declare function isTmuxPresentationContext(value: unknown): value is TmuxPresentationContext
export declare function isUIContribution(value: unknown): value is UIContribution
export declare function isWhen(value: unknown): value is When
