// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.

export interface ExtensionPoint {
  name: string
  interface?: string
  description?: string
}

export interface Family {
  selector?: string
  members?: FamilyMember[]
}

export interface FamilyMember {
  id: string
  when?: When
}

export interface HostCapabilities {
  major: number
  features: string[] | null
  pluginId: string
  generation: string
  grants: Permissions
}

export interface LauncherSpec {
  kind: string
  title: string
  description?: string
  group?: string
}

export interface LifecycleOperation {
  id: string
  pluginId: string
  action: string
  state: string
  generation?: string
  reason?: string
}

export interface Manifest {
  id: string
  version?: string
  nav?: NavItem[]
  panels?: PanelSpec[]
  launchers?: LauncherSpec[]
  scopes?: string[]
  routes?: string[]
  spawn?: boolean
  binary?: string
  socket?: string
  minCoreVersion?: string
  targets?: string[]
  role?: string
  provides?: string[]
  requires?: Requirement[]
  requiresProvides?: string[]
  pricing?: Pricing
  publisher?: Publisher
  family?: Family
  when?: When
  extends?: ExtensionPoint[]
  implements?: Provider[]
  critical?: boolean
  protocol?: ProtocolRequirements
  permissions?: Permissions
  ui?: UIContribution[]
}

export interface NavItem {
  id: string
  label: string
  icon?: string
  href: string
  order?: number
}

export interface PanelSpec {
  id: string
  kind: string
  url: string
  module?: string
  documentPaths?: string[]
}

export interface Permissions {
  publish?: string[]
  subscribe?: string[]
  request?: string[]
}

export interface Pricing {
  model: string
  sku?: string
  trialDays?: number
}

export interface ProtocolRequirements {
  major: number
  required?: string[]
}

export interface Provider {
  point: string
  id: string
  priority?: number
}

export interface Publisher {
  id: string
  name: string
  url?: string
}

export interface Requirement {
  id: string
  version?: string
}

export interface RuntimeSnapshot {
  epoch: string
  revision: string
  plugins: RuntimeStatus[] | null
}

export interface RuntimeStatus {
  id: string
  installed: boolean
  desiredState: string
  observedState: string
  available: boolean
  generation: string
  reason?: string
}

export interface UIContribution {
  id: string
  slot: string
  panelId?: string
  command?: string
  label?: string
  icon?: string
  priority?: number
}

export interface When {
  os?: string[]
}
