// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isBinding(value) {
  if (!record(value)) return false
  if (!(str(value.kind))) return false
  if (!(str(value.event))) return false
  if (!(value.field === undefined || str(value.field))) return false
  return true
}

export function isComponentAssignRequest(value) {
  if (!record(value)) return false
  if (!(isComponentIdentity(value.identity))) return false
  return true
}

export function isComponentAssignResult(value) {
  if (!record(value)) return false
  if (!(isComponentAssignment(value.assignment))) return false
  return true
}

export function isComponentAssignment(value) {
  if (!record(value)) return false
  if (!(isComponentIdentity(value.identity))) return false
  if (!(str(value.lease))) return false
  return true
}

export function isComponentAvailableRequest(value) {
  if (!record(value)) return false
  return true
}

export function isComponentAvailableResult(value) {
  if (!record(value)) return false
  if (!(list(value.components, isComponentIdentity))) return false
  return true
}

export function isComponentContributeRequest(value) {
  if (!record(value)) return false
  if (!(isComponentAssignment(value.assignment))) return false
  if (!(isComponentExtension(value.extension))) return false
  return true
}

export function isComponentContributeResult(value) {
  if (!record(value)) return false
  if (!(isComponentExtension(value.extension))) return false
  return true
}

export function isComponentExtension(value) {
  if (!record(value)) return false
  if (!(str(value.ownerId))) return false
  if (!(str(value.generation))) return false
  if (!(value.panelId === undefined || str(value.panelId))) return false
  if (!(value.icon === undefined || str(value.icon))) return false
  if (!(str(value.id))) return false
  if (!(isComponentIdentity(value.target))) return false
  if (!(str(value.point))) return false
  if (!(str(value.label))) return false
  if (!(num(value.order))) return false
  if (!(value.command === undefined || str(value.command))) return false
  return true
}

export function isComponentFileTreeSnapshot(value) {
  if (!record(value)) return false
  if (!(str(value.root))) return false
  if (!(str(value.selectedPath))) return false
  if (!(list(value.expandedPaths, str))) return false
  if (!(str(value.filter))) return false
  if (!(bool(value.loading))) return false
  return true
}

export function isComponentIdentity(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.family))) return false
  if (!(str(value.ownerId))) return false
  if (!(str(value.generation))) return false
  if (!(value.projectId === undefined || str(value.projectId))) return false
  if (!(value.sessionId === undefined || str(value.sessionId))) return false
  return true
}

export function isComponentPlacement(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(num(value.column))) return false
  if (!(num(value.row))) return false
  if (!(num(value.width))) return false
  if (!(num(value.height))) return false
  if (!(num(value.displayWidth))) return false
  if (!(num(value.displayHeight))) return false
  return true
}

export function isComponentProjectToolsSnapshot(value) {
  if (!record(value)) return false
  if (!(list(value.views, str))) return false
  if (!(str(value.selectedView))) return false
  if (!(bool(value.expanded))) return false
  if (!(bool(value.loading))) return false
  return true
}

export function isComponentSessionListSnapshot(value) {
  if (!record(value)) return false
  if (!(list(value.sessionIds, str))) return false
  if (!(str(value.selectedId))) return false
  if (!(str(value.group))) return false
  return true
}

export function isComponentSessionTabSnapshot(value) {
  if (!record(value)) return false
  if (!(str(value.title))) return false
  if (!(str(value.provider))) return false
  if (!(str(value.status))) return false
  if (!(bool(value.pinned))) return false
  return true
}

export function isComponentStageSnapshot(value) {
  if (!record(value)) return false
  if (!(list(value.placements, isComponentPlacement))) return false
  if (!(str(value.saveStatus))) return false
  return true
}

export function isComponentTasksSnapshot(value) {
  if (!record(value)) return false
  if (!(bool(value.available))) return false
  if (!(bool(value.running))) return false
  if (!(str(value.href))) return false
  if (!(bool(value.starting))) return false
  if (!(str(value.error))) return false
  return true
}

export function isComponentTerminalSnapshot(value) {
  if (!record(value)) return false
  if (!(bool(value.connected))) return false
  if (!(bool(value.visible))) return false
  if (!(str(value.viewMode))) return false
  return true
}

export function isComponentWorkspaceSnapshot(value) {
  if (!record(value)) return false
  if (!(bool(value.ready))) return false
  if (!(list(value.children, isComponentIdentity))) return false
  return true
}

export function isConfig(value) {
  if (!record(value)) return false
  if (!(value.sections === undefined || list(value.sections, isConfigSection))) return false
  return true
}

export function isConfigField(value) {
  if (!record(value)) return false
  if (!(str(value.key))) return false
  if (!(str(value.kind))) return false
  if (!(value.label === undefined || str(value.label))) return false
  if (!(value.description === undefined || str(value.description))) return false
  if (!(value.default === undefined || str(value.default))) return false
  if (!(value.min === undefined || num(value.min))) return false
  if (!(value.max === undefined || num(value.max))) return false
  if (!(value.nullable === undefined || bool(value.nullable))) return false
  if (!(value.choices === undefined || list(value.choices, str))) return false
  if (!(value.point === undefined || str(value.point))) return false
  if (!(value.requires === undefined || list(value.requires, str))) return false
  if (!(value.readOnly === undefined || bool(value.readOnly))) return false
  if (!(value.requiresRestart === undefined || bool(value.requiresRestart))) return false
  return true
}

export function isConfigSection(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.title === undefined || str(value.title))) return false
  if (!(value.description === undefined || str(value.description))) return false
  if (!(value.fields === undefined || list(value.fields, isConfigField))) return false
  return true
}

export function isDesktopApplication(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.name))) return false
  if (!(str(value.kind))) return false
  if (!(value.preset === undefined || str(value.preset))) return false
  if (!(str(value.status))) return false
  if (!(value.error === undefined || str(value.error))) return false
  if (!(value.manual === undefined || bool(value.manual))) return false
  if (!(value.revision === undefined || str(value.revision))) return false
  if (!(value.iconUrl === undefined || str(value.iconUrl))) return false
  if (!(value.launcherPath === undefined || str(value.launcherPath))) return false
  if (!(value.executablePath === undefined || str(value.executablePath))) return false
  if (!(value.installedAt === undefined || str(value.installedAt))) return false
  if (!(value.installedAtEstimated === undefined || bool(value.installedAtEstimated))) return false
  return true
}

export function isDesktopApplicationSession(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.applicationId))) return false
  if (!(str(value.name))) return false
  if (!(str(value.state))) return false
  if (!(value.windows === null || list(value.windows, isDesktopApplicationWindow))) return false
  if (!(str(value.viewerUrl))) return false
  if (!(value.error === undefined || str(value.error))) return false
  return true
}

export function isDesktopApplicationWindow(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.title))) return false
  return true
}

export function isDesktopApplicationsOpenRequest(value) {
  if (!record(value)) return false
  if (!(str(value.applicationId))) return false
  if (!(value.windowId === undefined || str(value.windowId))) return false
  return true
}

export function isDesktopApplicationsOpenResult(value) {
  if (!record(value)) return false
  if (!(isDesktopApplicationSession(value.session))) return false
  return true
}

export function isDesktopApplicationsQuitRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  return true
}

export function isDesktopApplicationsQuitResult(value) {
  if (!record(value)) return false
  if (!(bool(value.ok))) return false
  return true
}

export function isDesktopApplicationsRefreshRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  return true
}

export function isDesktopApplicationsRefreshResult(value) {
  if (!record(value)) return false
  if (!(isDesktopApplicationSession(value.session))) return false
  return true
}

export function isDesktopApplicationsRegisterRequest(value) {
  if (!record(value)) return false
  if (!(value.applicationId === undefined || str(value.applicationId))) return false
  if (!(str(value.name))) return false
  if (!(str(value.path))) return false
  return true
}

export function isDesktopApplicationsRegisterResult(value) {
  if (!record(value)) return false
  if (!(isDesktopApplication(value.application))) return false
  return true
}

export function isDesktopApplicationsScanRequest(value) {
  if (!record(value)) return false
  return true
}

export function isDesktopApplicationsScanResult(value) {
  if (!record(value)) return false
  if (!(isDesktopSessionStatus(value.desktop))) return false
  if (!(value.applications === null || list(value.applications, isDesktopApplication))) return false
  return true
}

export function isDesktopApplicationsScanV2Request(value) {
  if (!record(value)) return false
  if (!(value.scanId === undefined || str(value.scanId))) return false
  if (!(value.cursor === undefined || str(value.cursor))) return false
  if (!(value.limit === undefined || num(value.limit))) return false
  return true
}

export function isDesktopApplicationsScanV2Result(value) {
  if (!record(value)) return false
  if (!(str(value.scanId))) return false
  if (!(str(value.state))) return false
  if (!(value.revision === undefined || str(value.revision))) return false
  if (!(value.scannedAt === undefined || str(value.scannedAt))) return false
  if (!(num(value.total))) return false
  if (!(value.applications === null || list(value.applications, isDesktopApplication))) return false
  if (!(value.nextCursor === undefined || str(value.nextCursor))) return false
  if (!(value.error === undefined || str(value.error))) return false
  return true
}

export function isDesktopApplicationsStatusRequest(value) {
  if (!record(value)) return false
  return true
}

export function isDesktopApplicationsStatusResult(value) {
  if (!record(value)) return false
  if (!(isDesktopSessionStatus(value.desktop))) return false
  return true
}

export function isDesktopApplicationsViewerTicketRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(str(value.origin))) return false
  return true
}

export function isDesktopApplicationsViewerTicketResult(value) {
  if (!record(value)) return false
  if (!(str(value.ticket))) return false
  if (!(num(value.expiresIn))) return false
  return true
}

export function isDesktopSessionStatus(value) {
  if (!record(value)) return false
  if (!(bool(value.available))) return false
  if (!(str(value.message))) return false
  return true
}

export function isDirectoryContextActionContribution(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  if (!(value.icon === undefined || str(value.icon))) return false
  if (!(value.order === undefined || num(value.order))) return false
  if (!(str(value.wizardPanelId))) return false
  return true
}

export function isDirectoryContextActionEligibilityRequest(value) {
  if (!record(value)) return false
  if (!(str(value.actionId))) return false
  if (!(isProjectDirectoryContext(value.context))) return false
  return true
}

export function isDirectoryContextActionEligibilityResult(value) {
  if (!record(value)) return false
  if (!(bool(value.eligible))) return false
  if (!(value.reason === undefined || str(value.reason))) return false
  return true
}

export function isDirectoryContextActionWizardContext(value) {
  if (!record(value)) return false
  if (!(str(value.actionId))) return false
  if (!(isProjectDirectoryContext(value.context))) return false
  return true
}

export function isExtensionPoint(value) {
  if (!record(value)) return false
  if (!(str(value.name))) return false
  if (!(value.interface === undefined || str(value.interface))) return false
  if (!(value.description === undefined || str(value.description))) return false
  return true
}

export function isFamily(value) {
  if (!record(value)) return false
  if (!(value.selector === undefined || str(value.selector))) return false
  if (!(value.members === undefined || list(value.members, isFamilyMember))) return false
  return true
}

export function isFamilyMember(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.when === undefined || isWhen(value.when))) return false
  return true
}

export function isHostCapabilities(value) {
  if (!record(value)) return false
  if (!(num(value.major))) return false
  if (!(value.features === null || list(value.features, str))) return false
  if (!(str(value.pluginId))) return false
  if (!(str(value.generation))) return false
  if (!(isPermissions(value.grants))) return false
  if (!(value.hooks === undefined || list(value.hooks, str))) return false
  return true
}

export function isLauncherSpec(value) {
  if (!record(value)) return false
  if (!(str(value.kind))) return false
  if (!(str(value.title))) return false
  if (!(value.description === undefined || str(value.description))) return false
  if (!(value.group === undefined || str(value.group))) return false
  return true
}

export function isLifecycleOperation(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.pluginId))) return false
  if (!(str(value.action))) return false
  if (!(str(value.state))) return false
  if (!(value.generation === undefined || str(value.generation))) return false
  if (!(value.reason === undefined || str(value.reason))) return false
  return true
}

export function isManifest(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.version === undefined || str(value.version))) return false
  if (!(value.nav === undefined || list(value.nav, isNavItem))) return false
  if (!(value.panels === undefined || list(value.panels, isPanelSpec))) return false
  if (!(value.launchers === undefined || list(value.launchers, isLauncherSpec))) return false
  if (!(value.scopes === undefined || list(value.scopes, str))) return false
  if (!(value.routes === undefined || list(value.routes, str))) return false
  if (!(value.publicRoutes === undefined || list(value.publicRoutes, str))) return false
  if (!(value.spawn === undefined || bool(value.spawn))) return false
  if (!(value.binary === undefined || str(value.binary))) return false
  if (!(value.socket === undefined || str(value.socket))) return false
  if (!(value.minCoreVersion === undefined || str(value.minCoreVersion))) return false
  if (!(value.targets === undefined || list(value.targets, str))) return false
  if (!(value.role === undefined || str(value.role))) return false
  if (!(value.provides === undefined || list(value.provides, str))) return false
  if (!(value.requires === undefined || list(value.requires, isRequirement))) return false
  if (!(value.requiresProvides === undefined || list(value.requiresProvides, str))) return false
  if (!(value.pricing === undefined || isPricing(value.pricing))) return false
  if (!(value.publisher === undefined || isPublisher(value.publisher))) return false
  if (!(value.family === undefined || isFamily(value.family))) return false
  if (!(value.when === undefined || isWhen(value.when))) return false
  if (!(value.extends === undefined || list(value.extends, isExtensionPoint))) return false
  if (!(value.implements === undefined || list(value.implements, isProvider))) return false
  if (!(value.critical === undefined || bool(value.critical))) return false
  if (!(value.protocol === undefined || isProtocolRequirements(value.protocol))) return false
  if (!(value.permissions === undefined || isPermissions(value.permissions))) return false
  if (!(value.ui === undefined || list(value.ui, isUIContribution))) return false
  if (!(value.projectViews === undefined || list(value.projectViews, isProjectViewContribution))) return false
  if (!(value.directoryContextActions === undefined || list(value.directoryContextActions, isDirectoryContextActionContribution))) return false
  if (!(value.config === undefined || isConfig(value.config))) return false
  return true
}

export function isNavItem(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  if (!(value.icon === undefined || str(value.icon))) return false
  if (!(str(value.href))) return false
  if (!(value.order === undefined || num(value.order))) return false
  return true
}

export function isPanelSpec(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.kind))) return false
  if (!(str(value.url))) return false
  if (!(value.module === undefined || str(value.module))) return false
  if (!(value.documentPaths === undefined || list(value.documentPaths, str))) return false
  return true
}

export function isPermissions(value) {
  if (!record(value)) return false
  if (!(value.publish === undefined || list(value.publish, str))) return false
  if (!(value.subscribe === undefined || list(value.subscribe, str))) return false
  if (!(value.request === undefined || list(value.request, str))) return false
  return true
}

export function isPresentationBadge(value) {
  if (!record(value)) return false
  if (!(str(value.label))) return false
  if (!(value.icon === undefined || str(value.icon))) return false
  return true
}

export function isPresentationGroup(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  return true
}

export function isPresentationItem(value) {
  if (!record(value)) return false
  if (!(str(value.terminalId))) return false
  if (!(value.agentId === undefined || str(value.agentId))) return false
  if (!(value.displayName === undefined || str(value.displayName))) return false
  if (!(list(value.groupPath, isPresentationGroup))) return false
  if (!(list(value.badges, isPresentationBadge))) return false
  if (!(num(value.priority))) return false
  if (!(['fresh', 'stale', 'unknown'].includes(value.freshness))) return false
  return true
}

export function isPresentationLease(value) {
  if (!record(value)) return false
  if (!(str(value.hostEpoch))) return false
  if (!(str(value.pluginId))) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.generation))) return false
  if (!(str(value.subjectLease))) return false
  if (!(str(value.requestId))) return false
  if (!(str(value.viewRevision))) return false
  return true
}

export function isPresentationRequest(value) {
  if (!record(value)) return false
  if (!(isPresentationLease(value.lease))) return false
  if (!(list(value.terminals, isPresentationTerminal))) return false
  return true
}

export function isPresentationResult(value) {
  if (!record(value)) return false
  if (!(isPresentationLease(value.lease))) return false
  if (!(num(value.maxAgeMs))) return false
  if (!(list(value.items, isPresentationItem))) return false
  return true
}

export function isPresentationTerminal(value) {
  if (!record(value)) return false
  if (!(str(value.terminalId))) return false
  if (!(isTerminalBindingContext(value.context))) return false
  return true
}

export function isPricing(value) {
  if (!record(value)) return false
  if (!(str(value.model))) return false
  if (!(value.sku === undefined || str(value.sku))) return false
  if (!(value.trialDays === undefined || num(value.trialDays))) return false
  return true
}

export function isProjectDirectoryContext(value) {
  if (!record(value)) return false
  if (!(str(value.projectId))) return false
  if (!(str(value.checkoutId))) return false
  if (!(str(value.worktreeId))) return false
  if (!(str(value.projectRoot))) return false
  if (!(str(value.worktreeRoot))) return false
  if (!(str(value.directoryPath))) return false
  return true
}

export function isProjectViewContribution(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  if (!(str(value.icon))) return false
  if (!(value.order === undefined || num(value.order))) return false
  if (!(str(value.panelId))) return false
  return true
}

export function isProtocolRequirements(value) {
  if (!record(value)) return false
  if (!(num(value.major))) return false
  if (!(value.required === undefined || list(value.required, str))) return false
  if (!(value.hooks === undefined || list(value.hooks, str))) return false
  return true
}

export function isProvider(value) {
  if (!record(value)) return false
  if (!(str(value.point))) return false
  if (!(str(value.id))) return false
  if (!(value.priority === undefined || num(value.priority))) return false
  return true
}

export function isPublisher(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.name))) return false
  if (!(value.url === undefined || str(value.url))) return false
  return true
}

export function isRequirement(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.version === undefined || str(value.version))) return false
  return true
}

export function isRuntimeSnapshot(value) {
  if (!record(value)) return false
  if (!(str(value.epoch))) return false
  if (!(dec(value.revision))) return false
  if (!(value.plugins === null || list(value.plugins, isRuntimeStatus))) return false
  return true
}

export function isRuntimeStatus(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(bool(value.installed))) return false
  if (!(str(value.desiredState))) return false
  if (!(str(value.observedState))) return false
  if (!(bool(value.available))) return false
  if (!(str(value.generation))) return false
  if (!(value.reason === undefined || str(value.reason))) return false
  return true
}

export function isTerminalBindingContext(value) {
  if (!record(value)) return false
  if (value.kind === 'none') return value.tmux === undefined || value.tmux === null
  if (value.kind === 'tmux') return isTmuxPresentationContext(value.tmux)
  return false
}

export function isTmuxAvailability(value) {
  if (!record(value)) return false
  if (!(str(value.state))) return false
  if (!(value.version === undefined || str(value.version))) return false
  if (!(str(value.message))) return false
  return true
}

export function isTmuxAvailabilityRequest(value) {
  if (!record(value)) return false
  return true
}

export function isTmuxAvailabilityResult(value) {
  if (!record(value)) return false
  if (!(isTmuxAvailability(value.tmux))) return false
  return true
}

export function isTmuxPanesRequest(value) {
  if (!record(value)) return false
  return true
}

export function isTmuxPanesResult(value) {
  if (!record(value)) return false
  if (!(str(value.output))) return false
  return true
}

export function isTmuxPresentationContext(value) {
  if (!record(value)) return false
  if (!(str(value.repositoryKey))) return false
  if (!(str(value.serverKey))) return false
  if (!(str(value.serverPid))) return false
  if (!(str(value.sessionId))) return false
  if (!(str(value.sessionCreated))) return false
  if (!(str(value.paneId))) return false
  if (!(str(value.panePid))) return false
  return true
}

export function isTmuxSessionsRequest(value) {
  if (!record(value)) return false
  return true
}

export function isTmuxSessionsResult(value) {
  if (!record(value)) return false
  if (!(str(value.output))) return false
  return true
}

export function isTmuxWindowsRequest(value) {
  if (!record(value)) return false
  return true
}

export function isTmuxWindowsResult(value) {
  if (!record(value)) return false
  if (!(str(value.output))) return false
  return true
}

export function isUIContribution(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.slot))) return false
  if (!(value.panelId === undefined || str(value.panelId))) return false
  if (!(value.command === undefined || str(value.command))) return false
  if (!(value.label === undefined || str(value.label))) return false
  if (!(value.icon === undefined || str(value.icon))) return false
  if (!(value.priority === undefined || num(value.priority))) return false
  if (!(value.bindings === undefined || list(value.bindings, isBinding))) return false
  return true
}

export function isWhen(value) {
  if (!record(value)) return false
  if (!(value.os === undefined || list(value.os, str))) return false
  return true
}
