// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isExtensionPoint(value) {
  if (!record(value)) return false
  if (!(str(value.name))) return false
  if (!(value.interface === undefined || str(value.interface))) return false
  if (!(value.description === undefined || str(value.description))) return false
  return true
}

export function isFamily(value) {
  if (!record(value)) return false
  if (!(value.selector === undefined || str(value.selector))) return false
  if (!(value.members === undefined || list(value.members, isFamilyMember))) return false
  return true
}

export function isFamilyMember(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.when === undefined || isWhen(value.when))) return false
  return true
}

export function isHostCapabilities(value) {
  if (!record(value)) return false
  if (!(num(value.major))) return false
  if (!(value.features === null || list(value.features, str))) return false
  if (!(str(value.pluginId))) return false
  if (!(str(value.generation))) return false
  if (!(isPermissions(value.grants))) return false
  return true
}

export function isLauncherSpec(value) {
  if (!record(value)) return false
  if (!(str(value.kind))) return false
  if (!(str(value.title))) return false
  if (!(value.description === undefined || str(value.description))) return false
  if (!(value.group === undefined || str(value.group))) return false
  return true
}

export function isLifecycleOperation(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.pluginId))) return false
  if (!(str(value.action))) return false
  if (!(str(value.state))) return false
  if (!(value.generation === undefined || str(value.generation))) return false
  if (!(value.reason === undefined || str(value.reason))) return false
  return true
}

export function isManifest(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.version === undefined || str(value.version))) return false
  if (!(value.nav === undefined || list(value.nav, isNavItem))) return false
  if (!(value.panels === undefined || list(value.panels, isPanelSpec))) return false
  if (!(value.launchers === undefined || list(value.launchers, isLauncherSpec))) return false
  if (!(value.scopes === undefined || list(value.scopes, str))) return false
  if (!(value.routes === undefined || list(value.routes, str))) return false
  if (!(value.spawn === undefined || bool(value.spawn))) return false
  if (!(value.binary === undefined || str(value.binary))) return false
  if (!(value.socket === undefined || str(value.socket))) return false
  if (!(value.minCoreVersion === undefined || str(value.minCoreVersion))) return false
  if (!(value.targets === undefined || list(value.targets, str))) return false
  if (!(value.role === undefined || str(value.role))) return false
  if (!(value.provides === undefined || list(value.provides, str))) return false
  if (!(value.requires === undefined || list(value.requires, isRequirement))) return false
  if (!(value.requiresProvides === undefined || list(value.requiresProvides, str))) return false
  if (!(value.pricing === undefined || isPricing(value.pricing))) return false
  if (!(value.publisher === undefined || isPublisher(value.publisher))) return false
  if (!(value.family === undefined || isFamily(value.family))) return false
  if (!(value.when === undefined || isWhen(value.when))) return false
  if (!(value.extends === undefined || list(value.extends, isExtensionPoint))) return false
  if (!(value.implements === undefined || list(value.implements, isProvider))) return false
  if (!(value.critical === undefined || bool(value.critical))) return false
  if (!(value.protocol === undefined || isProtocolRequirements(value.protocol))) return false
  if (!(value.permissions === undefined || isPermissions(value.permissions))) return false
  if (!(value.ui === undefined || list(value.ui, isUIContribution))) return false
  return true
}

export function isNavItem(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  if (!(value.icon === undefined || str(value.icon))) return false
  if (!(str(value.href))) return false
  if (!(value.order === undefined || num(value.order))) return false
  return true
}

export function isPanelSpec(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.kind))) return false
  if (!(str(value.url))) return false
  if (!(value.module === undefined || str(value.module))) return false
  if (!(value.documentPaths === undefined || list(value.documentPaths, str))) return false
  return true
}

export function isPermissions(value) {
  if (!record(value)) return false
  if (!(value.publish === undefined || list(value.publish, str))) return false
  if (!(value.subscribe === undefined || list(value.subscribe, str))) return false
  if (!(value.request === undefined || list(value.request, str))) return false
  return true
}

export function isPresentationBadge(value) {
  if (!record(value)) return false
  if (!(str(value.label))) return false
  if (!(value.icon === undefined || str(value.icon))) return false
  return true
}

export function isPresentationGroup(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  return true
}

export function isPresentationItem(value) {
  if (!record(value)) return false
  if (!(str(value.terminalId))) return false
  if (!(list(value.groupPath, isPresentationGroup))) return false
  if (!(list(value.badges, isPresentationBadge))) return false
  if (!(num(value.priority))) return false
  if (!(['fresh', 'stale', 'unknown'].includes(value.freshness))) return false
  return true
}

export function isPresentationLease(value) {
  if (!record(value)) return false
  if (!(str(value.hostEpoch))) return false
  if (!(str(value.pluginId))) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.generation))) return false
  if (!(str(value.subjectLease))) return false
  if (!(str(value.requestId))) return false
  if (!(str(value.viewRevision))) return false
  return true
}

export function isPresentationRequest(value) {
  if (!record(value)) return false
  if (!(isPresentationLease(value.lease))) return false
  if (!(list(value.terminals, isPresentationTerminal))) return false
  return true
}

export function isPresentationResult(value) {
  if (!record(value)) return false
  if (!(isPresentationLease(value.lease))) return false
  if (!(num(value.maxAgeMs))) return false
  if (!(list(value.items, isPresentationItem))) return false
  return true
}

export function isPresentationTerminal(value) {
  if (!record(value)) return false
  if (!(str(value.terminalId))) return false
  if (!(isTerminalBindingContext(value.context))) return false
  return true
}

export function isPricing(value) {
  if (!record(value)) return false
  if (!(str(value.model))) return false
  if (!(value.sku === undefined || str(value.sku))) return false
  if (!(value.trialDays === undefined || num(value.trialDays))) return false
  return true
}

export function isProtocolRequirements(value) {
  if (!record(value)) return false
  if (!(num(value.major))) return false
  if (!(value.required === undefined || list(value.required, str))) return false
  return true
}

export function isProvider(value) {
  if (!record(value)) return false
  if (!(str(value.point))) return false
  if (!(str(value.id))) return false
  if (!(value.priority === undefined || num(value.priority))) return false
  return true
}

export function isPublisher(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.name))) return false
  if (!(value.url === undefined || str(value.url))) return false
  return true
}

export function isRequirement(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.version === undefined || str(value.version))) return false
  return true
}

export function isRuntimeSnapshot(value) {
  if (!record(value)) return false
  if (!(str(value.epoch))) return false
  if (!(dec(value.revision))) return false
  if (!(value.plugins === null || list(value.plugins, isRuntimeStatus))) return false
  return true
}

export function isRuntimeStatus(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(bool(value.installed))) return false
  if (!(str(value.desiredState))) return false
  if (!(str(value.observedState))) return false
  if (!(bool(value.available))) return false
  if (!(str(value.generation))) return false
  if (!(value.reason === undefined || str(value.reason))) return false
  return true
}

export function isTerminalBindingContext(value) {
  if (!record(value)) return false
  if (value.kind === 'none') return value.tmux === undefined || value.tmux === null
  if (value.kind === 'tmux') return isTmuxPresentationContext(value.tmux)
  return false
}

export function isTmuxPresentationContext(value) {
  if (!record(value)) return false
  if (!(str(value.repositoryKey))) return false
  if (!(str(value.serverKey))) return false
  if (!(str(value.serverPid))) return false
  if (!(str(value.sessionId))) return false
  if (!(str(value.sessionCreated))) return false
  if (!(str(value.paneId))) return false
  if (!(str(value.panePid))) return false
  return true
}

export function isUIContribution(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.slot))) return false
  if (!(value.panelId === undefined || str(value.panelId))) return false
  if (!(value.command === undefined || str(value.command))) return false
  if (!(value.label === undefined || str(value.label))) return false
  if (!(value.icon === undefined || str(value.icon))) return false
  if (!(value.priority === undefined || num(value.priority))) return false
  return true
}

export function isWhen(value) {
  if (!record(value)) return false
  if (!(value.os === undefined || list(value.os, str))) return false
  return true
}
