// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface Answer {
  id: string
  kind: string
  choice?: ChoiceAnswer
  score?: ScoreAnswer
  noul?: NoulAnswer
}

export interface BatchRequest {
  purpose: string
  providerId: string
  model: string
  state: StructuredValue
  questions: Question[] | null
  idempotencyKey: string
}

export interface BatchResult {
  providerId: string
  requestedModel: string
  model: string
  answers: Answer[] | null
  usage: Usage
}

export interface CancelRequest {
  jobId: string
}

export interface CancelResult {
  job: Job
}

export interface ChoiceAnswer {
  choice: string
  probabilities: Probability[] | null
  confidence: string
}

export interface ChoiceQuestion {
  options: Option[] | null
}

export interface DecisionModel {
  id: string
  label: string
  kinds: string[] | null
}

export interface Failure {
  code: string
  message: string
  retryable: boolean
}

export interface Job {
  id: string
  providerId: string
  state: string
  createdAt: string
  deadlineAt: string
  result?: BatchResult
  resultHandleId?: string
  failure?: Failure
}

export interface LegendEntry {
  id: string
  label: string
}

export interface ModelsRequest {
  providerId: string
}

export interface ModelsResult {
  providerId: string
  models: DecisionModel[] | null
  refreshing: boolean
  observedAt?: string
  failure?: Failure
}

export interface NoulAnswer {
  noul: string
}

export interface NoulCriteria {
  true: StructuredValue
  false: StructuredValue
}

export interface NoulQuestion {
  criteria?: NoulCriteria
}

export interface Option {
  id: string
  description?: StructuredValue
}

export interface Probability {
  id: string
  value: string
}

export interface ProviderCancelRequest {
  invocationId: string
  jobId: string
}

export interface ProviderModelsRequest {
  invocationId: string
  request: ModelsRequest
}

export interface ProviderReadRequest {
  invocationId: string
  jobId: string
}

export interface ProviderStartRequest {
  invocationId: string
  batch: BatchRequest
}

export interface Question {
  id: string
  instructions: StructuredValue
  kind: string
  choice?: ChoiceQuestion
  score?: ScoreQuestion
  noul?: NoulQuestion
}

export interface ReadRequest {
  jobId: string
}

export interface ReadResult {
  job: Job
}

export interface ScoreAnswer {
  score: string
  legend: LegendEntry[] | null
  probabilities: Probability[] | null
  confidence: string
}

export interface ScoreQuestion {
  levels: StructuredValue[] | null
}

export interface StartResult {
  job: Job
}

export interface StructuredValue {
  format: string
  content: TextInput
}

export interface TextInput {
  inline?: string
  handleId?: string
}

export interface Usage {
  inputTokens: string | null
  outputTokens: string | null
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isAnswer(value: unknown): value is Answer
export declare function isBatchRequest(value: unknown): value is BatchRequest
export declare function isBatchResult(value: unknown): value is BatchResult
export declare function isCancelRequest(value: unknown): value is CancelRequest
export declare function isCancelResult(value: unknown): value is CancelResult
export declare function isChoiceAnswer(value: unknown): value is ChoiceAnswer
export declare function isChoiceQuestion(value: unknown): value is ChoiceQuestion
export declare function isDecisionModel(value: unknown): value is DecisionModel
export declare function isFailure(value: unknown): value is Failure
export declare function isJob(value: unknown): value is Job
export declare function isLegendEntry(value: unknown): value is LegendEntry
export declare function isModelsRequest(value: unknown): value is ModelsRequest
export declare function isModelsResult(value: unknown): value is ModelsResult
export declare function isNoulAnswer(value: unknown): value is NoulAnswer
export declare function isNoulCriteria(value: unknown): value is NoulCriteria
export declare function isNoulQuestion(value: unknown): value is NoulQuestion
export declare function isOption(value: unknown): value is Option
export declare function isProbability(value: unknown): value is Probability
export declare function isProviderCancelRequest(value: unknown): value is ProviderCancelRequest
export declare function isProviderModelsRequest(value: unknown): value is ProviderModelsRequest
export declare function isProviderReadRequest(value: unknown): value is ProviderReadRequest
export declare function isProviderStartRequest(value: unknown): value is ProviderStartRequest
export declare function isQuestion(value: unknown): value is Question
export declare function isReadRequest(value: unknown): value is ReadRequest
export declare function isReadResult(value: unknown): value is ReadResult
export declare function isScoreAnswer(value: unknown): value is ScoreAnswer
export declare function isScoreQuestion(value: unknown): value is ScoreQuestion
export declare function isStartResult(value: unknown): value is StartResult
export declare function isStructuredValue(value: unknown): value is StructuredValue
export declare function isTextInput(value: unknown): value is TextInput
export declare function isUsage(value: unknown): value is Usage
