// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  Cancel: Object.freeze({"name":"cmd.gateway.ai-decision.v1.cancel","kind":"command","rev":1,"schema":"05ed4cfed9e49c06343200a1a56fb9f5ebc5d2d5c66c292d524e0070d20cc75a","subject":"cmd.gateway.ai-decision.v1.cancel"}),
  Models: Object.freeze({"name":"cmd.gateway.ai-decision.v1.models","kind":"command","rev":1,"schema":"306654ef3d902e5995120aaa18d027ca50c652e76f3a651570b1404b79450552","subject":"cmd.gateway.ai-decision.v1.models"}),
  Read: Object.freeze({"name":"cmd.gateway.ai-decision.v1.read","kind":"command","rev":1,"schema":"538cac07027aa6cbb9ceb31bef5e0c4542ccb048a4f169e147b3889ff34fa6b7","subject":"cmd.gateway.ai-decision.v1.read"}),
  Start: Object.freeze({"name":"cmd.gateway.ai-decision.v1.start","kind":"command","rev":1,"schema":"7590dd6e60a336d9ca468b6ee371f1c92cf9d4773c1371b78f0d39fcfcfd1129","subject":"cmd.gateway.ai-decision.v1.start"}),
})
