// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isAnswer(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.kind))) return false
  if (!(value.choice === undefined || isChoiceAnswer(value.choice))) return false
  if (!(value.score === undefined || isScoreAnswer(value.score))) return false
  if (!(value.noul === undefined || isNoulAnswer(value.noul))) return false
  return true
}

export function isBatchRequest(value) {
  if (!record(value)) return false
  if (!(str(value.purpose))) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.model))) return false
  if (!(isStructuredValue(value.state))) return false
  if (!(value.questions === null || list(value.questions, isQuestion))) return false
  if (!(str(value.idempotencyKey))) return false
  return true
}

export function isBatchResult(value) {
  if (!record(value)) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.requestedModel))) return false
  if (!(str(value.model))) return false
  if (!(value.answers === null || list(value.answers, isAnswer))) return false
  if (!(isUsage(value.usage))) return false
  return true
}

export function isCancelRequest(value) {
  if (!record(value)) return false
  if (!(str(value.jobId))) return false
  return true
}

export function isCancelResult(value) {
  if (!record(value)) return false
  if (!(isJob(value.job))) return false
  return true
}

export function isChoiceAnswer(value) {
  if (!record(value)) return false
  if (!(str(value.choice))) return false
  if (!(value.probabilities === null || list(value.probabilities, isProbability))) return false
  if (!(str(value.confidence))) return false
  return true
}

export function isChoiceQuestion(value) {
  if (!record(value)) return false
  if (!(value.options === null || list(value.options, isOption))) return false
  return true
}

export function isDecisionModel(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  if (!(value.kinds === null || list(value.kinds, str))) return false
  return true
}

export function isFailure(value) {
  if (!record(value)) return false
  if (!(str(value.code))) return false
  if (!(str(value.message))) return false
  if (!(bool(value.retryable))) return false
  return true
}

export function isJob(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.state))) return false
  if (!(str(value.createdAt))) return false
  if (!(str(value.deadlineAt))) return false
  if (!(value.result === undefined || isBatchResult(value.result))) return false
  if (!(value.resultHandleId === undefined || str(value.resultHandleId))) return false
  if (!(value.failure === undefined || isFailure(value.failure))) return false
  return true
}

export function isLegendEntry(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  return true
}

export function isModelsRequest(value) {
  if (!record(value)) return false
  if (!(str(value.providerId))) return false
  return true
}

export function isModelsResult(value) {
  if (!record(value)) return false
  if (!(str(value.providerId))) return false
  if (!(value.models === null || list(value.models, isDecisionModel))) return false
  if (!(bool(value.refreshing))) return false
  if (!(value.observedAt === undefined || str(value.observedAt))) return false
  if (!(value.failure === undefined || isFailure(value.failure))) return false
  return true
}

export function isNoulAnswer(value) {
  if (!record(value)) return false
  if (!(str(value.noul))) return false
  return true
}

export function isNoulCriteria(value) {
  if (!record(value)) return false
  if (!(isStructuredValue(value.true))) return false
  if (!(isStructuredValue(value.false))) return false
  return true
}

export function isNoulQuestion(value) {
  if (!record(value)) return false
  if (!(value.criteria === undefined || isNoulCriteria(value.criteria))) return false
  return true
}

export function isOption(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.description === undefined || isStructuredValue(value.description))) return false
  return true
}

export function isProbability(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.value))) return false
  return true
}

export function isProviderCancelRequest(value) {
  if (!record(value)) return false
  if (!(str(value.invocationId))) return false
  if (!(str(value.jobId))) return false
  return true
}

export function isProviderModelsRequest(value) {
  if (!record(value)) return false
  if (!(str(value.invocationId))) return false
  if (!(isModelsRequest(value.request))) return false
  return true
}

export function isProviderReadRequest(value) {
  if (!record(value)) return false
  if (!(str(value.invocationId))) return false
  if (!(str(value.jobId))) return false
  return true
}

export function isProviderStartRequest(value) {
  if (!record(value)) return false
  if (!(str(value.invocationId))) return false
  if (!(isBatchRequest(value.batch))) return false
  return true
}

export function isQuestion(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(isStructuredValue(value.instructions))) return false
  if (!(str(value.kind))) return false
  if (!(value.choice === undefined || isChoiceQuestion(value.choice))) return false
  if (!(value.score === undefined || isScoreQuestion(value.score))) return false
  if (!(value.noul === undefined || isNoulQuestion(value.noul))) return false
  return true
}

export function isReadRequest(value) {
  if (!record(value)) return false
  if (!(str(value.jobId))) return false
  return true
}

export function isReadResult(value) {
  if (!record(value)) return false
  if (!(isJob(value.job))) return false
  return true
}

export function isScoreAnswer(value) {
  if (!record(value)) return false
  if (!(str(value.score))) return false
  if (!(value.legend === null || list(value.legend, isLegendEntry))) return false
  if (!(value.probabilities === null || list(value.probabilities, isProbability))) return false
  if (!(str(value.confidence))) return false
  return true
}

export function isScoreQuestion(value) {
  if (!record(value)) return false
  if (!(value.levels === null || list(value.levels, isStructuredValue))) return false
  return true
}

export function isStartResult(value) {
  if (!record(value)) return false
  if (!(isJob(value.job))) return false
  return true
}

export function isStructuredValue(value) {
  if (!record(value)) return false
  if (!(str(value.format))) return false
  if (!(isTextInput(value.content))) return false
  return true
}

export function isTextInput(value) {
  if (!record(value)) return false
  if (!(value.inline === undefined || str(value.inline))) return false
  if (!(value.handleId === undefined || str(value.handleId))) return false
  return true
}

export function isUsage(value) {
  if (!record(value)) return false
  if (!(value.inputTokens === null || dec(value.inputTokens))) return false
  if (!(value.outputTokens === null || dec(value.outputTokens))) return false
  return true
}
