// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface App {
  target: Target
  name: string
  description: string
  stackHint?: string
  relativeRoot: string
  configState: string
  configError?: string
  conversation: Conversation
  run?: Run
  providers: Provider[] | null
  services: ServiceStatus[] | null
  preview?: Preview
}

export interface Attachment {
  id?: string
  name: string
  mediaType?: string
  size: string
}

export interface Conversation {
  id: string
  replayFrom?: string
  nextCursor?: string
  messages: Message[] | null
}

export interface ConversationAnswerRequest {
  target: Target
  requestId: string
  answer: string
}

export interface ConversationAnswerResult {
  message: Message
  run?: Run
  cursor: string
}

export interface ConversationApproveRequest {
  target: Target
  requestId: string
  approved: boolean
}

export interface ConversationApproveResult {
  message: Message
  run?: Run
  cursor: string
}

export interface ConversationSendRequest {
  target: Target
  content: string
  mode: string
  providerId: string
  effort?: string
  attachments: Attachment[] | null
}

export interface ConversationSendResult {
  message: Message
  run: Run
  cursor: string
}

export interface CreateRequest {
  context: ProjectDirectoryContext
  name: string
  description: string
  stackHint?: string
  references: Attachment[] | null
}

export interface CreateResult {
  app: App
  href: string
}

export interface CreationEligibilityRequest {
  context: ProjectDirectoryContext
}

export interface CreationEligibilityResult {
  eligible: boolean
  reason?: string
}

export interface ListRequest {
  target: ProjectTarget
  appId?: string
  cursor?: string
  limit?: number
}

export interface ListResult {
  apps: App[] | null
  selectedAppId?: string
  events: RuntimeEvent[] | null
  nextCursor?: string
}

export interface LogEntry {
  cursor: string
  serviceId: string
  stream: string
  text: string
  createdAt: string
}

export interface Message {
  id: string
  role: string
  kind: string
  markdown: string
  createdAt: string
  pending?: boolean
  attachments?: Attachment[]
}

export interface Preview {
  state: string
  url?: string
  path?: string
  serviceId?: string
  capabilities: PreviewCapabilities
  message?: string
}

export interface PreviewCapabilities {
  inspection: boolean
  webSocket: boolean
  externalOpen: boolean
}

export interface PreviewNavigateRequest {
  target: Target
  direction: string
}

export interface PreviewNavigateResult {
  preview: Preview
}

export interface PreviewOpenExternalRequest {
  target: Target
}

export interface PreviewOpenExternalResult {
  opened: boolean
}

export interface PreviewResolveRequest {
  target: Target
}

export interface PreviewResolveResult {
  preview: Preview
}

export interface ProjectDirectoryContext {
  projectId: string
  checkoutId: string
  worktreeId: string
  projectRoot: string
  worktreeRoot: string
  directoryPath: string
}

export interface ProjectTarget {
  projectId: string
  checkoutId: string
}

export interface Provider {
  id: string
  label: string
  effortOptions: string[] | null
  attachments: boolean
  approvals: boolean
  questions: boolean
  inspection: boolean
}

export interface Run {
  id: string
  state: string
  mode: string
  providerId: string
  effort?: string
  configRevision: string
  activity: ToolActivity[] | null
  startedAt?: string
  finishedAt?: string
}

export interface RunStopRequest {
  target: Target
}

export interface RunStopResult {
  run: Run
  cursor: string
}

export interface RuntimeEvent {
  cursor: string
  kind: string
  target: Target
  createdAt: string
  message?: Message
  run?: Run
  service?: ServiceStatus
  preview?: Preview
}

export interface ServiceStatus {
  id: string
  state: string
  port?: number
  message?: string
  ready: boolean
  updatedAt: string
}

export interface ServicesLogsRequest {
  target: Target
  serviceId?: string
  cursor?: string
  limit?: number
}

export interface ServicesLogsResult {
  entries: LogEntry[] | null
  nextCursor?: string
}

export interface ServicesStartRequest {
  target: Target
  serviceIds: string[] | null
}

export interface ServicesStartResult {
  services: ServiceStatus[] | null
  cursor: string
}

export interface ServicesStopRequest {
  target: Target
  serviceIds: string[] | null
}

export interface ServicesStopResult {
  services: ServiceStatus[] | null
  cursor: string
}

export interface Target {
  projectId: string
  checkoutId: string
  appId: string
  configRevision: string
  runId?: string
}

export interface ToolActivity {
  id: string
  label: string
  state: string
  summary?: string
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isApp(value: unknown): value is App
export declare function isAttachment(value: unknown): value is Attachment
export declare function isConversation(value: unknown): value is Conversation
export declare function isConversationAnswerRequest(value: unknown): value is ConversationAnswerRequest
export declare function isConversationAnswerResult(value: unknown): value is ConversationAnswerResult
export declare function isConversationApproveRequest(value: unknown): value is ConversationApproveRequest
export declare function isConversationApproveResult(value: unknown): value is ConversationApproveResult
export declare function isConversationSendRequest(value: unknown): value is ConversationSendRequest
export declare function isConversationSendResult(value: unknown): value is ConversationSendResult
export declare function isCreateRequest(value: unknown): value is CreateRequest
export declare function isCreateResult(value: unknown): value is CreateResult
export declare function isCreationEligibilityRequest(value: unknown): value is CreationEligibilityRequest
export declare function isCreationEligibilityResult(value: unknown): value is CreationEligibilityResult
export declare function isListRequest(value: unknown): value is ListRequest
export declare function isListResult(value: unknown): value is ListResult
export declare function isLogEntry(value: unknown): value is LogEntry
export declare function isMessage(value: unknown): value is Message
export declare function isPreview(value: unknown): value is Preview
export declare function isPreviewCapabilities(value: unknown): value is PreviewCapabilities
export declare function isPreviewNavigateRequest(value: unknown): value is PreviewNavigateRequest
export declare function isPreviewNavigateResult(value: unknown): value is PreviewNavigateResult
export declare function isPreviewOpenExternalRequest(value: unknown): value is PreviewOpenExternalRequest
export declare function isPreviewOpenExternalResult(value: unknown): value is PreviewOpenExternalResult
export declare function isPreviewResolveRequest(value: unknown): value is PreviewResolveRequest
export declare function isPreviewResolveResult(value: unknown): value is PreviewResolveResult
export declare function isProjectDirectoryContext(value: unknown): value is ProjectDirectoryContext
export declare function isProjectTarget(value: unknown): value is ProjectTarget
export declare function isProvider(value: unknown): value is Provider
export declare function isRun(value: unknown): value is Run
export declare function isRunStopRequest(value: unknown): value is RunStopRequest
export declare function isRunStopResult(value: unknown): value is RunStopResult
export declare function isRuntimeEvent(value: unknown): value is RuntimeEvent
export declare function isServiceStatus(value: unknown): value is ServiceStatus
export declare function isServicesLogsRequest(value: unknown): value is ServicesLogsRequest
export declare function isServicesLogsResult(value: unknown): value is ServicesLogsResult
export declare function isServicesStartRequest(value: unknown): value is ServicesStartRequest
export declare function isServicesStartResult(value: unknown): value is ServicesStartResult
export declare function isServicesStopRequest(value: unknown): value is ServicesStopRequest
export declare function isServicesStopResult(value: unknown): value is ServicesStopResult
export declare function isTarget(value: unknown): value is Target
export declare function isToolActivity(value: unknown): value is ToolActivity
