// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  AnswerConversationRequest: Object.freeze({"name":"cmd.web-apps.v1.conversation.answer","kind":"command","rev":1,"schema":"abcfba5c232d979146ddd62c008421d7ff8e7d9810f68b85e4b1ac6f72312aea","subject":"cmd.web-apps.v1.conversation.answer"}),
  ApproveConversationRequest: Object.freeze({"name":"cmd.web-apps.v1.conversation.approve","kind":"command","rev":1,"schema":"5706a5fe3250b9049d30da45816316f020d03f66d8b4452847b6d5c6678e3bec","subject":"cmd.web-apps.v1.conversation.approve"}),
  Changed: Object.freeze({"name":"event.web-apps.v1.changed","kind":"event","rev":1,"schema":"573d4b52aae84c92bc95aa7dc56a9ffbbb9cb8bbb85a6d73c523dd2ad2a0de47","subject":"event.web-apps.v1.changed"}),
  CheckCreationEligibility: Object.freeze({"name":"cmd.web-apps.v1.creation-eligibility","kind":"command","rev":1,"schema":"0b476ef6a9b31e3dbcb434a7a7a9addf1afbdd12b17437e5c65a723f184a3a1c","subject":"cmd.web-apps.v1.creation-eligibility"}),
  Create: Object.freeze({"name":"cmd.web-apps.v1.create","kind":"command","rev":1,"schema":"b90d842f26948f74ddc8b6470585cd0b4932282a00da68ce9531177cbdd7faa4","subject":"cmd.web-apps.v1.create"}),
  Events: Object.freeze({"name":"stream.web-apps.v1.events","kind":"stream","rev":1,"schema":"981e41df754f7f7977a22804eeb7a406a7db5f744659dd640d148fa637a55913","stream":"WEB_APPS_EVENTS","subjects":["event.web-apps.v1.changed"]}),
  List: Object.freeze({"name":"cmd.web-apps.v1.list","kind":"command","rev":1,"schema":"4bb46fbc3c737fdd15e51957d4431f5f74fe6b4858926ac568b1e5a5183aed97","subject":"cmd.web-apps.v1.list"}),
  NavigatePreview: Object.freeze({"name":"cmd.web-apps.v1.preview.navigate","kind":"command","rev":1,"schema":"33b5e477355b14c25a510b4045fe944a61b73d0a49fb726f18f8ab1d3e5e7d9a","subject":"cmd.web-apps.v1.preview.navigate"}),
  OpenPreviewExternal: Object.freeze({"name":"cmd.web-apps.v1.preview.open-external","kind":"command","rev":1,"schema":"f3048549233bc4e939e673235ea8223c40ed5670f64c5ee0142bbe141ba536de","subject":"cmd.web-apps.v1.preview.open-external"}),
  ReadServiceLogs: Object.freeze({"name":"cmd.web-apps.v1.services.logs","kind":"command","rev":1,"schema":"d4a088b47debdf1486aa665df549245d830691098ddd0778b28c028ed7293e87","subject":"cmd.web-apps.v1.services.logs"}),
  ResolvePreview: Object.freeze({"name":"cmd.web-apps.v1.preview.resolve","kind":"command","rev":1,"schema":"ba0bce9af43db6cb49dfdc01736d31608b49182576f038f03b161b86ef1e30f3","subject":"cmd.web-apps.v1.preview.resolve"}),
  SendConversationMessage: Object.freeze({"name":"cmd.web-apps.v1.conversation.send","kind":"command","rev":1,"schema":"458f2ecce83fc55f282d2602f3ab20ffe9f51438f8e8fbb2971da63945b9ceae","subject":"cmd.web-apps.v1.conversation.send"}),
  StartServices: Object.freeze({"name":"cmd.web-apps.v1.services.start","kind":"command","rev":1,"schema":"7cf00b95dfce6b556b4a3e0f57085dfaadd0f967966d88c8186d96e7944136bb","subject":"cmd.web-apps.v1.services.start"}),
  StopRun: Object.freeze({"name":"cmd.web-apps.v1.run.stop","kind":"command","rev":1,"schema":"f3a4508b2dfd799270be3f622dddf626179875404437d2eda4dad08d4c196f54","subject":"cmd.web-apps.v1.run.stop"}),
  StopServices: Object.freeze({"name":"cmd.web-apps.v1.services.stop","kind":"command","rev":1,"schema":"68652738afc69adc8e4b579e8fdfa4ed9945d1b2a498c7d653bf492dc3d77ab1","subject":"cmd.web-apps.v1.services.stop"}),
})
