// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  AnswerConversationRequest: Object.freeze({"name":"cmd.gateway.web-apps.v1.conversation.answer","kind":"command","rev":1,"schema":"796d473b699f1ae91c968cabccf3764051ad2c1ce6bf2977ee0b934555fae086","subject":"cmd.gateway.web-apps.v1.conversation.answer"}),
  ApproveConversationRequest: Object.freeze({"name":"cmd.gateway.web-apps.v1.conversation.approve","kind":"command","rev":1,"schema":"e046d65de2b4224cf1a0b0e629146e21de9205fe48a861444cb9aa048d734621","subject":"cmd.gateway.web-apps.v1.conversation.approve"}),
  Changed: Object.freeze({"name":"event.web-apps.v1.changed","kind":"event","rev":1,"schema":"573d4b52aae84c92bc95aa7dc56a9ffbbb9cb8bbb85a6d73c523dd2ad2a0de47","subject":"event.web-apps.v1.changed"}),
  CheckCreationEligibility: Object.freeze({"name":"cmd.gateway.web-apps.v1.creation-eligibility","kind":"command","rev":1,"schema":"33df73e2b569ef57351a3b677cba87a054585fd43a1ff982c58b3a58f6111ddf","subject":"cmd.gateway.web-apps.v1.creation-eligibility"}),
  Create: Object.freeze({"name":"cmd.gateway.web-apps.v1.create","kind":"command","rev":1,"schema":"b36c5035182f66128eecb04d19ff7bbfc457bdf4c4428ec072abad36114383d1","subject":"cmd.gateway.web-apps.v1.create"}),
  Events: Object.freeze({"name":"stream.web-apps.v1.events","kind":"stream","rev":1,"schema":"981e41df754f7f7977a22804eeb7a406a7db5f744659dd640d148fa637a55913","stream":"WEB_APPS_EVENTS","subjects":["event.web-apps.v1.changed"]}),
  List: Object.freeze({"name":"cmd.gateway.web-apps.v1.list","kind":"command","rev":1,"schema":"cbf6469648ba690382b908ff60d8ff7b5fe4fdac18d7c65fc4309a42376c136c","subject":"cmd.gateway.web-apps.v1.list"}),
  NavigatePreview: Object.freeze({"name":"cmd.gateway.web-apps.v1.preview.navigate","kind":"command","rev":1,"schema":"586135f31c16c97466966f93d6459d2b33e37d23aa893e02951b3d0f2db3e7ec","subject":"cmd.gateway.web-apps.v1.preview.navigate"}),
  OpenPreviewExternal: Object.freeze({"name":"cmd.gateway.web-apps.v1.preview.open-external","kind":"command","rev":1,"schema":"7ac6cd7787d2e7c83a9c71a7736c18bc8952ca97dfea2f9280c20a1cabdb8b95","subject":"cmd.gateway.web-apps.v1.preview.open-external"}),
  ReadServiceLogs: Object.freeze({"name":"cmd.gateway.web-apps.v1.services.logs","kind":"command","rev":1,"schema":"42d6ea8c2a5ecdf68c6e13fc7509a7ddda1d22caac49fa9333954033b7320bac","subject":"cmd.gateway.web-apps.v1.services.logs"}),
  ResolvePreview: Object.freeze({"name":"cmd.gateway.web-apps.v1.preview.resolve","kind":"command","rev":1,"schema":"0ff37ad474ebfb345739a546d2aba9d5d46c39af7205cd0c1ce0a53f9e9311ec","subject":"cmd.gateway.web-apps.v1.preview.resolve"}),
  SendConversationMessage: Object.freeze({"name":"cmd.gateway.web-apps.v1.conversation.send","kind":"command","rev":1,"schema":"8c198bf95569cb7d9d2d346da4ee685be14be8a000b70698dcc047ae4428c69f","subject":"cmd.gateway.web-apps.v1.conversation.send"}),
  StartServices: Object.freeze({"name":"cmd.gateway.web-apps.v1.services.start","kind":"command","rev":1,"schema":"53df9abba0d5dbbbc39aec295dffacfcb5cb6813c12a6e3c54238ef582494128","subject":"cmd.gateway.web-apps.v1.services.start"}),
  StopRun: Object.freeze({"name":"cmd.gateway.web-apps.v1.run.stop","kind":"command","rev":1,"schema":"7cdc315c8824ae8ba869bcd1d5dbefc95a0f91d528944b1c9bf8ac14adc12aa8","subject":"cmd.gateway.web-apps.v1.run.stop"}),
  StopServices: Object.freeze({"name":"cmd.gateway.web-apps.v1.services.stop","kind":"command","rev":1,"schema":"c062f1af1418a834b5b2c72f54ade5a38fe67de97586971b42bd690f3f463742","subject":"cmd.gateway.web-apps.v1.services.stop"}),
})
