// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isApp(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  if (!(str(value.name))) return false
  if (!(str(value.description))) return false
  if (!(value.stackHint === undefined || str(value.stackHint))) return false
  if (!(str(value.relativeRoot))) return false
  if (!(str(value.configState))) return false
  if (!(value.configError === undefined || str(value.configError))) return false
  if (!(isConversation(value.conversation))) return false
  if (!(value.run === undefined || isRun(value.run))) return false
  if (!(value.providers === null || list(value.providers, isProvider))) return false
  if (!(value.services === null || list(value.services, isServiceStatus))) return false
  if (!(value.preview === undefined || isPreview(value.preview))) return false
  return true
}

export function isAttachment(value) {
  if (!record(value)) return false
  if (!(value.id === undefined || str(value.id))) return false
  if (!(str(value.name))) return false
  if (!(value.mediaType === undefined || str(value.mediaType))) return false
  if (!(dec(value.size))) return false
  return true
}

export function isConversation(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(value.replayFrom === undefined || str(value.replayFrom))) return false
  if (!(value.nextCursor === undefined || str(value.nextCursor))) return false
  if (!(value.messages === null || list(value.messages, isMessage))) return false
  return true
}

export function isConversationAnswerRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  if (!(str(value.requestId))) return false
  if (!(str(value.answer))) return false
  return true
}

export function isConversationAnswerResult(value) {
  if (!record(value)) return false
  if (!(isMessage(value.message))) return false
  if (!(value.run === undefined || isRun(value.run))) return false
  if (!(str(value.cursor))) return false
  return true
}

export function isConversationApproveRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  if (!(str(value.requestId))) return false
  if (!(bool(value.approved))) return false
  return true
}

export function isConversationApproveResult(value) {
  if (!record(value)) return false
  if (!(isMessage(value.message))) return false
  if (!(value.run === undefined || isRun(value.run))) return false
  if (!(str(value.cursor))) return false
  return true
}

export function isConversationSendRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  if (!(str(value.content))) return false
  if (!(str(value.mode))) return false
  if (!(str(value.providerId))) return false
  if (!(value.effort === undefined || str(value.effort))) return false
  if (!(value.attachments === null || list(value.attachments, isAttachment))) return false
  return true
}

export function isConversationSendResult(value) {
  if (!record(value)) return false
  if (!(isMessage(value.message))) return false
  if (!(isRun(value.run))) return false
  if (!(str(value.cursor))) return false
  return true
}

export function isCreateRequest(value) {
  if (!record(value)) return false
  if (!(isProjectDirectoryContext(value.context))) return false
  if (!(str(value.name))) return false
  if (!(str(value.description))) return false
  if (!(value.stackHint === undefined || str(value.stackHint))) return false
  if (!(value.references === null || list(value.references, isAttachment))) return false
  return true
}

export function isCreateResult(value) {
  if (!record(value)) return false
  if (!(isApp(value.app))) return false
  if (!(str(value.href))) return false
  return true
}

export function isCreationEligibilityRequest(value) {
  if (!record(value)) return false
  if (!(isProjectDirectoryContext(value.context))) return false
  return true
}

export function isCreationEligibilityResult(value) {
  if (!record(value)) return false
  if (!(bool(value.eligible))) return false
  if (!(value.reason === undefined || str(value.reason))) return false
  return true
}

export function isListRequest(value) {
  if (!record(value)) return false
  if (!(isProjectTarget(value.target))) return false
  if (!(value.appId === undefined || str(value.appId))) return false
  if (!(value.cursor === undefined || str(value.cursor))) return false
  if (!(value.limit === undefined || num(value.limit))) return false
  return true
}

export function isListResult(value) {
  if (!record(value)) return false
  if (!(value.apps === null || list(value.apps, isApp))) return false
  if (!(value.selectedAppId === undefined || str(value.selectedAppId))) return false
  if (!(value.events === null || list(value.events, isRuntimeEvent))) return false
  if (!(value.nextCursor === undefined || str(value.nextCursor))) return false
  return true
}

export function isLogEntry(value) {
  if (!record(value)) return false
  if (!(str(value.cursor))) return false
  if (!(str(value.serviceId))) return false
  if (!(str(value.stream))) return false
  if (!(str(value.text))) return false
  if (!(str(value.createdAt))) return false
  return true
}

export function isMessage(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.role))) return false
  if (!(str(value.kind))) return false
  if (!(str(value.markdown))) return false
  if (!(str(value.createdAt))) return false
  if (!(value.pending === undefined || bool(value.pending))) return false
  if (!(value.attachments === undefined || list(value.attachments, isAttachment))) return false
  return true
}

export function isPreview(value) {
  if (!record(value)) return false
  if (!(str(value.state))) return false
  if (!(value.url === undefined || str(value.url))) return false
  if (!(value.path === undefined || str(value.path))) return false
  if (!(value.serviceId === undefined || str(value.serviceId))) return false
  if (!(isPreviewCapabilities(value.capabilities))) return false
  if (!(value.message === undefined || str(value.message))) return false
  return true
}

export function isPreviewCapabilities(value) {
  if (!record(value)) return false
  if (!(bool(value.inspection))) return false
  if (!(bool(value.webSocket))) return false
  if (!(bool(value.externalOpen))) return false
  return true
}

export function isPreviewNavigateRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  if (!(str(value.direction))) return false
  return true
}

export function isPreviewNavigateResult(value) {
  if (!record(value)) return false
  if (!(isPreview(value.preview))) return false
  return true
}

export function isPreviewOpenExternalRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  return true
}

export function isPreviewOpenExternalResult(value) {
  if (!record(value)) return false
  if (!(bool(value.opened))) return false
  return true
}

export function isPreviewResolveRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  return true
}

export function isPreviewResolveResult(value) {
  if (!record(value)) return false
  if (!(isPreview(value.preview))) return false
  return true
}

export function isProjectDirectoryContext(value) {
  if (!record(value)) return false
  if (!(str(value.projectId))) return false
  if (!(str(value.checkoutId))) return false
  if (!(str(value.worktreeId))) return false
  if (!(str(value.projectRoot))) return false
  if (!(str(value.worktreeRoot))) return false
  if (!(str(value.directoryPath))) return false
  return true
}

export function isProjectTarget(value) {
  if (!record(value)) return false
  if (!(str(value.projectId))) return false
  if (!(str(value.checkoutId))) return false
  return true
}

export function isProvider(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  if (!(value.effortOptions === null || list(value.effortOptions, str))) return false
  if (!(bool(value.attachments))) return false
  if (!(bool(value.approvals))) return false
  if (!(bool(value.questions))) return false
  if (!(bool(value.inspection))) return false
  return true
}

export function isRun(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.state))) return false
  if (!(str(value.mode))) return false
  if (!(str(value.providerId))) return false
  if (!(value.effort === undefined || str(value.effort))) return false
  if (!(str(value.configRevision))) return false
  if (!(value.activity === null || list(value.activity, isToolActivity))) return false
  if (!(value.startedAt === undefined || str(value.startedAt))) return false
  if (!(value.finishedAt === undefined || str(value.finishedAt))) return false
  return true
}

export function isRunStopRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  return true
}

export function isRunStopResult(value) {
  if (!record(value)) return false
  if (!(isRun(value.run))) return false
  if (!(str(value.cursor))) return false
  return true
}

export function isRuntimeEvent(value) {
  if (!record(value)) return false
  if (!(str(value.cursor))) return false
  if (!(str(value.kind))) return false
  if (!(isTarget(value.target))) return false
  if (!(str(value.createdAt))) return false
  if (!(value.message === undefined || isMessage(value.message))) return false
  if (!(value.run === undefined || isRun(value.run))) return false
  if (!(value.service === undefined || isServiceStatus(value.service))) return false
  if (!(value.preview === undefined || isPreview(value.preview))) return false
  return true
}

export function isServiceStatus(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.state))) return false
  if (!(value.port === undefined || num(value.port))) return false
  if (!(value.message === undefined || str(value.message))) return false
  if (!(bool(value.ready))) return false
  if (!(str(value.updatedAt))) return false
  return true
}

export function isServicesLogsRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  if (!(value.serviceId === undefined || str(value.serviceId))) return false
  if (!(value.cursor === undefined || str(value.cursor))) return false
  if (!(value.limit === undefined || num(value.limit))) return false
  return true
}

export function isServicesLogsResult(value) {
  if (!record(value)) return false
  if (!(value.entries === null || list(value.entries, isLogEntry))) return false
  if (!(value.nextCursor === undefined || str(value.nextCursor))) return false
  return true
}

export function isServicesStartRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  if (!(value.serviceIds === null || list(value.serviceIds, str))) return false
  return true
}

export function isServicesStartResult(value) {
  if (!record(value)) return false
  if (!(value.services === null || list(value.services, isServiceStatus))) return false
  if (!(str(value.cursor))) return false
  return true
}

export function isServicesStopRequest(value) {
  if (!record(value)) return false
  if (!(isTarget(value.target))) return false
  if (!(value.serviceIds === null || list(value.serviceIds, str))) return false
  return true
}

export function isServicesStopResult(value) {
  if (!record(value)) return false
  if (!(value.services === null || list(value.services, isServiceStatus))) return false
  if (!(str(value.cursor))) return false
  return true
}

export function isTarget(value) {
  if (!record(value)) return false
  if (!(str(value.projectId))) return false
  if (!(str(value.checkoutId))) return false
  if (!(str(value.appId))) return false
  if (!(str(value.configRevision))) return false
  if (!(value.runId === undefined || str(value.runId))) return false
  return true
}

export function isToolActivity(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.label))) return false
  if (!(str(value.state))) return false
  if (!(value.summary === undefined || str(value.summary))) return false
  return true
}
