// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface Approval {
  id: string
  promptId: string
  title: string
  options: ApprovalOption[] | null
}

export interface ApprovalOption {
  id: string
  name: string
  kind: string
}

export interface ApproveRequest {
  sessionId: string
  approvalId: string
  optionId: string
}

export interface BoundWorkUnit {
  taskId: string
  bindingId: string
}

export interface Capabilities {
  loadSession: boolean
  resumeSession: boolean
  closeSession: boolean
  setConfigOption: boolean
  setModel: boolean
  setMode: boolean
  extensionsJson?: string
}

export interface CatalogRequest {
  cursor?: string
}

export interface CatalogResult {
  providers: Provider[] | null
  nextCursor?: string
}

export interface ChangedEvent {
  sessionId: string
  lastSequence: string
}

export interface ConfigChoice {
  value: string
  name: string
  group?: string
}

export interface ConfigOption {
  id: string
  name: string
  category?: string
  type: string
  currentValue: string
  choices?: ConfigChoice[]
  extensionsJson?: string
}

export interface ConfigUpdate {
  options: ConfigOption[] | null
}

export interface ConfigValue {
  id: string
  value: string
}

export interface CreateRequest {
  projectId: string
  checkoutRef: string
  preferences: Preferences
  idempotencyKey: string
  workUnit?: WorkUnitReference
}

export interface EventsRequest {
  sessionId: string
  afterSequence: string
  limit: number
}

export interface EventsResult {
  events: SessionEvent[] | null
  lastSequence: string
  hasMore: boolean
}

export interface Failure {
  code: string
  message: string
}

export interface ListRequest {
  projectId: string
  cursor?: string
}

export interface ListResult {
  sessions: Session[] | null
  nextCursor?: string
}

export interface Message {
  role: string
  content: TextInput
}

export interface Model {
  id: string
  name: string
  description?: string
}

export interface NewTaskRequest {
  sessionId: string
  preferences: Preferences
  idempotencyKey: string
  workUnit?: WorkUnitReference
}

export interface OpenSurfaceRequest {
  sessionId: string
}

export interface OpenSurfaceResult {
  sessionId: string
  surfaceId: string
  focused: boolean
}

export interface Overrides {
  providerId?: string
  modelId?: string
  configValues?: ConfigValue[]
}

export interface Preferences {
  routingPolicy: string
  permissionMode: string
  nextTaskOverrides?: Overrides
}

export interface PreferencesRequest {
  sessionId: string
  preferences: Preferences
}

export interface PreviewJob {
  id: string
  state: string
  deadlineAt: string
  result?: PreviewResult
  failure?: Failure
}

export interface PreviewJobRequest {
  jobId: string
}

export interface PreviewJobResult {
  job: PreviewJob
}

export interface PreviewRequest {
  projectId: string
  checkoutRef: string
  preferences: Preferences
  content: TextInput
  idempotencyKey: string
}

export interface PreviewResult {
  status: string
  route?: Route
  reason: string
  confidence?: string
  costKnown: boolean
  latencyKnown: boolean
  warnings: string[] | null
}

export interface PromptRequest {
  sessionId: string
  content: TextInput
  idempotencyKey: string
}

export interface PromptResult {
  session: Session
  promptId: string
}

export interface Provider {
  id: string
  generation: string
  name: string
  availability: string
  unavailableReason?: string
  capabilities: Capabilities
  models: Model[] | null
  configOptions: ConfigOption[] | null
  permissionModes: string[] | null
  observedAt: string
}

export interface Route {
  providerId: string
  providerGeneration: string
  modelId: string
  configValues: ConfigValue[] | null
  policy: string
  source: string
  reason: string
}

export interface Session {
  id: string
  taskId: string
  projectId: string
  state: string
  preferences: Preferences
  route?: Route
  configOptions: ConfigOption[] | null
  activePromptId?: string
  lastSequence: string
  recovery: string
  createdAt: string
  updatedAt: string
  checkoutRef: string
  worktreeRef?: string
  workUnit?: BoundWorkUnit
}

export interface SessionEvent {
  sessionId: string
  taskId: string
  sequence: string
  at: string
  kind: string
  message?: Message
  tool?: ToolUpdate
  approval?: Approval
  route?: Route
  state?: StateUpdate
  config?: ConfigUpdate
  failure?: Failure
}

export interface SessionRequest {
  sessionId: string
}

export interface SessionResult {
  session: Session
}

export interface StateUpdate {
  state: string
  recovery: string
}

export interface StopRequest {
  sessionId: string
  promptId: string
}

export interface TextInput {
  inline?: string
  handleId?: string
}

export interface ToolUpdate {
  id: string
  title: string
  status: string
  content?: TextInput
}

export interface WorkUnitReference {
  taskId: string
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isApproval(value: unknown): value is Approval
export declare function isApprovalOption(value: unknown): value is ApprovalOption
export declare function isApproveRequest(value: unknown): value is ApproveRequest
export declare function isBoundWorkUnit(value: unknown): value is BoundWorkUnit
export declare function isCapabilities(value: unknown): value is Capabilities
export declare function isCatalogRequest(value: unknown): value is CatalogRequest
export declare function isCatalogResult(value: unknown): value is CatalogResult
export declare function isChangedEvent(value: unknown): value is ChangedEvent
export declare function isConfigChoice(value: unknown): value is ConfigChoice
export declare function isConfigOption(value: unknown): value is ConfigOption
export declare function isConfigUpdate(value: unknown): value is ConfigUpdate
export declare function isConfigValue(value: unknown): value is ConfigValue
export declare function isCreateRequest(value: unknown): value is CreateRequest
export declare function isEventsRequest(value: unknown): value is EventsRequest
export declare function isEventsResult(value: unknown): value is EventsResult
export declare function isFailure(value: unknown): value is Failure
export declare function isListRequest(value: unknown): value is ListRequest
export declare function isListResult(value: unknown): value is ListResult
export declare function isMessage(value: unknown): value is Message
export declare function isModel(value: unknown): value is Model
export declare function isNewTaskRequest(value: unknown): value is NewTaskRequest
export declare function isOpenSurfaceRequest(value: unknown): value is OpenSurfaceRequest
export declare function isOpenSurfaceResult(value: unknown): value is OpenSurfaceResult
export declare function isOverrides(value: unknown): value is Overrides
export declare function isPreferences(value: unknown): value is Preferences
export declare function isPreferencesRequest(value: unknown): value is PreferencesRequest
export declare function isPreviewJob(value: unknown): value is PreviewJob
export declare function isPreviewJobRequest(value: unknown): value is PreviewJobRequest
export declare function isPreviewJobResult(value: unknown): value is PreviewJobResult
export declare function isPreviewRequest(value: unknown): value is PreviewRequest
export declare function isPreviewResult(value: unknown): value is PreviewResult
export declare function isPromptRequest(value: unknown): value is PromptRequest
export declare function isPromptResult(value: unknown): value is PromptResult
export declare function isProvider(value: unknown): value is Provider
export declare function isRoute(value: unknown): value is Route
export declare function isSession(value: unknown): value is Session
export declare function isSessionEvent(value: unknown): value is SessionEvent
export declare function isSessionRequest(value: unknown): value is SessionRequest
export declare function isSessionResult(value: unknown): value is SessionResult
export declare function isStateUpdate(value: unknown): value is StateUpdate
export declare function isStopRequest(value: unknown): value is StopRequest
export declare function isTextInput(value: unknown): value is TextInput
export declare function isToolUpdate(value: unknown): value is ToolUpdate
export declare function isWorkUnitReference(value: unknown): value is WorkUnitReference
