// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  Approve: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.approve","kind":"command","rev":1,"schema":"19ef74374fb2281d43d3fd3905adfb785428f7cccb5ee58a77941c6a1e42725e","subject":"cmd.gateway.coding-sessions.v1.approve"}),
  Catalog: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.catalog","kind":"command","rev":1,"schema":"472e7e6147aba591f004c331e296e86cf6ae72254010fa503f3c868d76f3dc02","subject":"cmd.gateway.coding-sessions.v1.catalog"}),
  Changed: Object.freeze({"name":"event.gateway.coding-sessions.v1.changed","kind":"event","rev":1,"schema":"6ba741e12f65cfbd3db73b053c55241b236fe87602888426ac34c90857aec42c","subject":"event.gateway.coding-sessions.v1.changed"}),
  Complete: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.complete","kind":"command","rev":1,"schema":"c0f3eb4178636fdc5d650d06e6881f8c0dba20d0ab9324e871ff555c70875cbd","subject":"cmd.gateway.coding-sessions.v1.complete"}),
  Create: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.create","kind":"command","rev":1,"schema":"420ae406d3faba10ed9e624755ba3933681c8609acbe7506dccaa2886822e1f1","subject":"cmd.gateway.coding-sessions.v1.create"}),
  End: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.end","kind":"command","rev":1,"schema":"1c4f5db1962e7fc92d01d9e7cbecb34611658d1f011ca6f139deac221d1dc168","subject":"cmd.gateway.coding-sessions.v1.end"}),
  Events: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.events","kind":"command","rev":1,"schema":"140dc34f5f348d6ef84b17d97124797fb8a6f11f5a6a6b016ab83fb22e16fd0e","subject":"cmd.gateway.coding-sessions.v1.events"}),
  List: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.list","kind":"command","rev":1,"schema":"9165cb8062ae5a6fb6e1d670b2a3143fa2cf7a50f69a8ded3266ab8bfcdb5eb6","subject":"cmd.gateway.coding-sessions.v1.list"}),
  NewTask: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.new-task","kind":"command","rev":1,"schema":"1a1d6c732d1a9a1e7c1eca54d817c4685276d925b88c92b99f9c35a66332b5f3","subject":"cmd.gateway.coding-sessions.v1.new-task"}),
  OpenSurface: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.open-surface","kind":"command","rev":1,"schema":"c58ff311051c0969d594628d825c3144ebffc264d1669d9975afd5977393478d","subject":"cmd.gateway.coding-sessions.v1.open-surface"}),
  Preview: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.preview","kind":"command","rev":1,"schema":"473a9b018e2d58a0414164ebdd951be0e5700231cf3030f2515eec44e3056c77","subject":"cmd.gateway.coding-sessions.v1.preview"}),
  PreviewCancel: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.preview-cancel","kind":"command","rev":1,"schema":"ee510f00f8073f13d27e9d3745d4bd6ea62d742e61ba0408c1994e1878b8a90f","subject":"cmd.gateway.coding-sessions.v1.preview-cancel"}),
  PreviewRead: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.preview-read","kind":"command","rev":1,"schema":"12c17d2d6c15af21bea886d67adb953a7c4c3536f6f31fb333faed68f3e260a7","subject":"cmd.gateway.coding-sessions.v1.preview-read"}),
  Prompt: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.prompt","kind":"command","rev":1,"schema":"f5c2150744580a05f197a123940f371583bbe6a9404dabe5546ecf68c62a68c4","subject":"cmd.gateway.coding-sessions.v1.prompt"}),
  Read: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.read","kind":"command","rev":1,"schema":"8832001706d99c4f6443e991dfcd75be37fbe6f65716f22ae2d40192f0cf307d","subject":"cmd.gateway.coding-sessions.v1.read"}),
  Recover: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.recover","kind":"command","rev":1,"schema":"c1fa7990685425fcb66fd94a350322304d11705158f03b4bd634c608741df2b6","subject":"cmd.gateway.coding-sessions.v1.recover"}),
  Stop: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.stop","kind":"command","rev":1,"schema":"80ac3931ba9da5bffbe72911e5cd33fdfd06bb385ad55f7f6e98936bd9facf4d","subject":"cmd.gateway.coding-sessions.v1.stop"}),
  UpdatePreferences: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.preferences","kind":"command","rev":1,"schema":"a19936e0aac5d9fac802e0ef7cf19f76572a81b99b500396fde7a0eb8e56d98e","subject":"cmd.gateway.coding-sessions.v1.preferences"}),
})
