// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  Approve: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.approve","kind":"command","rev":1,"schema":"68a79cb6d28900e344d11d90f9a623c86bcecb05258f5c3a6cb5f9ffdc785798","subject":"cmd.gateway.coding-sessions.v1.approve"}),
  Catalog: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.catalog","kind":"command","rev":1,"schema":"472e7e6147aba591f004c331e296e86cf6ae72254010fa503f3c868d76f3dc02","subject":"cmd.gateway.coding-sessions.v1.catalog"}),
  Changed: Object.freeze({"name":"event.gateway.coding-sessions.v1.changed","kind":"event","rev":1,"schema":"6ba741e12f65cfbd3db73b053c55241b236fe87602888426ac34c90857aec42c","subject":"event.gateway.coding-sessions.v1.changed"}),
  Complete: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.complete","kind":"command","rev":1,"schema":"f14c2e9f6038b85cc109947f63760405c698ebcc9839cc3e663c152d75d0eb66","subject":"cmd.gateway.coding-sessions.v1.complete"}),
  Create: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.create","kind":"command","rev":1,"schema":"b39e5192107263ca56e6c064b687075c93af4f40c857910149729e6c7899d8f0","subject":"cmd.gateway.coding-sessions.v1.create"}),
  End: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.end","kind":"command","rev":1,"schema":"07c34e9d68a9034682fc6e885f1b53604bbd4ff9b5a331fdb7ca4a36dd26d089","subject":"cmd.gateway.coding-sessions.v1.end"}),
  Events: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.events","kind":"command","rev":1,"schema":"140dc34f5f348d6ef84b17d97124797fb8a6f11f5a6a6b016ab83fb22e16fd0e","subject":"cmd.gateway.coding-sessions.v1.events"}),
  List: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.list","kind":"command","rev":1,"schema":"9afbc2b4bfd71620b3b9c5b03d41ce8c1cd45292a84b8f556d7fd6118ef3174f","subject":"cmd.gateway.coding-sessions.v1.list"}),
  NewTask: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.new-task","kind":"command","rev":1,"schema":"a08ed42c12a856f1f9da4b4c7c3ed4474b4d5ce40d6200437001bb2f09e5ae95","subject":"cmd.gateway.coding-sessions.v1.new-task"}),
  OpenSurface: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.open-surface","kind":"command","rev":1,"schema":"c58ff311051c0969d594628d825c3144ebffc264d1669d9975afd5977393478d","subject":"cmd.gateway.coding-sessions.v1.open-surface"}),
  Preview: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.preview","kind":"command","rev":1,"schema":"473a9b018e2d58a0414164ebdd951be0e5700231cf3030f2515eec44e3056c77","subject":"cmd.gateway.coding-sessions.v1.preview"}),
  PreviewCancel: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.preview-cancel","kind":"command","rev":1,"schema":"ee510f00f8073f13d27e9d3745d4bd6ea62d742e61ba0408c1994e1878b8a90f","subject":"cmd.gateway.coding-sessions.v1.preview-cancel"}),
  PreviewRead: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.preview-read","kind":"command","rev":1,"schema":"12c17d2d6c15af21bea886d67adb953a7c4c3536f6f31fb333faed68f3e260a7","subject":"cmd.gateway.coding-sessions.v1.preview-read"}),
  Prompt: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.prompt","kind":"command","rev":1,"schema":"80adf133d4b595be5e24c31148842d274f92a23b6973d5d5db8f90f01a2af7d8","subject":"cmd.gateway.coding-sessions.v1.prompt"}),
  Read: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.read","kind":"command","rev":1,"schema":"7e30a4e1961318e85b4f4ac388d2dab22a18684f6982023bedeaede52580f122","subject":"cmd.gateway.coding-sessions.v1.read"}),
  Recover: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.recover","kind":"command","rev":1,"schema":"56d90eb37cf9b8a15da710f4454c98020b7a2741cd05a6a17cd1250b53f80397","subject":"cmd.gateway.coding-sessions.v1.recover"}),
  Stop: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.stop","kind":"command","rev":1,"schema":"51127a02664cce918b48aeba4985b18658ca73ab07e8b52223b96f559c0f4542","subject":"cmd.gateway.coding-sessions.v1.stop"}),
  UpdatePreferences: Object.freeze({"name":"cmd.gateway.coding-sessions.v1.preferences","kind":"command","rev":1,"schema":"fe0b2ff008700b28e2ec0dbb381e8dc9eddfe5ce6656465eb1a350ca6f81814f","subject":"cmd.gateway.coding-sessions.v1.preferences"}),
})
