// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isApproval(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.promptId))) return false
  if (!(str(value.title))) return false
  if (!(value.options === null || list(value.options, isApprovalOption))) return false
  return true
}

export function isApprovalOption(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.name))) return false
  if (!(str(value.kind))) return false
  return true
}

export function isApproveRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(str(value.approvalId))) return false
  if (!(str(value.optionId))) return false
  return true
}

export function isCapabilities(value) {
  if (!record(value)) return false
  if (!(bool(value.loadSession))) return false
  if (!(bool(value.resumeSession))) return false
  if (!(bool(value.closeSession))) return false
  if (!(bool(value.setConfigOption))) return false
  if (!(bool(value.setModel))) return false
  if (!(bool(value.setMode))) return false
  if (!(value.extensionsJson === undefined || str(value.extensionsJson))) return false
  return true
}

export function isCatalogRequest(value) {
  if (!record(value)) return false
  if (!(value.cursor === undefined || str(value.cursor))) return false
  return true
}

export function isCatalogResult(value) {
  if (!record(value)) return false
  if (!(value.providers === null || list(value.providers, isProvider))) return false
  if (!(value.nextCursor === undefined || str(value.nextCursor))) return false
  return true
}

export function isChangedEvent(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(dec(value.lastSequence))) return false
  return true
}

export function isConfigChoice(value) {
  if (!record(value)) return false
  if (!(str(value.value))) return false
  if (!(str(value.name))) return false
  if (!(value.group === undefined || str(value.group))) return false
  return true
}

export function isConfigOption(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.name))) return false
  if (!(value.category === undefined || str(value.category))) return false
  if (!(str(value.type))) return false
  if (!(str(value.currentValue))) return false
  if (!(value.choices === undefined || list(value.choices, isConfigChoice))) return false
  if (!(value.extensionsJson === undefined || str(value.extensionsJson))) return false
  return true
}

export function isConfigUpdate(value) {
  if (!record(value)) return false
  if (!(value.options === null || list(value.options, isConfigOption))) return false
  return true
}

export function isConfigValue(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.value))) return false
  return true
}

export function isCreateRequest(value) {
  if (!record(value)) return false
  if (!(str(value.projectId))) return false
  if (!(str(value.checkoutRef))) return false
  if (!(isPreferences(value.preferences))) return false
  if (!(str(value.idempotencyKey))) return false
  return true
}

export function isEventsRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(dec(value.afterSequence))) return false
  if (!(num(value.limit))) return false
  return true
}

export function isEventsResult(value) {
  if (!record(value)) return false
  if (!(value.events === null || list(value.events, isSessionEvent))) return false
  if (!(dec(value.lastSequence))) return false
  if (!(bool(value.hasMore))) return false
  return true
}

export function isFailure(value) {
  if (!record(value)) return false
  if (!(str(value.code))) return false
  if (!(str(value.message))) return false
  return true
}

export function isListRequest(value) {
  if (!record(value)) return false
  if (!(str(value.projectId))) return false
  if (!(value.cursor === undefined || str(value.cursor))) return false
  return true
}

export function isListResult(value) {
  if (!record(value)) return false
  if (!(value.sessions === null || list(value.sessions, isSession))) return false
  if (!(value.nextCursor === undefined || str(value.nextCursor))) return false
  return true
}

export function isMessage(value) {
  if (!record(value)) return false
  if (!(str(value.role))) return false
  if (!(isTextInput(value.content))) return false
  return true
}

export function isModel(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.name))) return false
  if (!(value.description === undefined || str(value.description))) return false
  return true
}

export function isNewTaskRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(isPreferences(value.preferences))) return false
  if (!(str(value.idempotencyKey))) return false
  return true
}

export function isOpenSurfaceRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  return true
}

export function isOpenSurfaceResult(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(str(value.surfaceId))) return false
  if (!(bool(value.focused))) return false
  return true
}

export function isOverrides(value) {
  if (!record(value)) return false
  if (!(value.providerId === undefined || str(value.providerId))) return false
  if (!(value.modelId === undefined || str(value.modelId))) return false
  if (!(value.configValues === undefined || list(value.configValues, isConfigValue))) return false
  return true
}

export function isPreferences(value) {
  if (!record(value)) return false
  if (!(str(value.routingPolicy))) return false
  if (!(str(value.permissionMode))) return false
  if (!(value.nextTaskOverrides === undefined || isOverrides(value.nextTaskOverrides))) return false
  return true
}

export function isPreferencesRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(isPreferences(value.preferences))) return false
  return true
}

export function isPreviewJob(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.state))) return false
  if (!(str(value.deadlineAt))) return false
  if (!(value.result === undefined || isPreviewResult(value.result))) return false
  if (!(value.failure === undefined || isFailure(value.failure))) return false
  return true
}

export function isPreviewJobRequest(value) {
  if (!record(value)) return false
  if (!(str(value.jobId))) return false
  return true
}

export function isPreviewJobResult(value) {
  if (!record(value)) return false
  if (!(isPreviewJob(value.job))) return false
  return true
}

export function isPreviewRequest(value) {
  if (!record(value)) return false
  if (!(str(value.projectId))) return false
  if (!(str(value.checkoutRef))) return false
  if (!(isPreferences(value.preferences))) return false
  if (!(isTextInput(value.content))) return false
  if (!(str(value.idempotencyKey))) return false
  return true
}

export function isPreviewResult(value) {
  if (!record(value)) return false
  if (!(str(value.status))) return false
  if (!(value.route === undefined || isRoute(value.route))) return false
  if (!(str(value.reason))) return false
  if (!(value.confidence === undefined || str(value.confidence))) return false
  if (!(bool(value.costKnown))) return false
  if (!(bool(value.latencyKnown))) return false
  if (!(value.warnings === null || list(value.warnings, str))) return false
  return true
}

export function isPromptRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(isTextInput(value.content))) return false
  if (!(str(value.idempotencyKey))) return false
  return true
}

export function isPromptResult(value) {
  if (!record(value)) return false
  if (!(isSession(value.session))) return false
  if (!(str(value.promptId))) return false
  return true
}

export function isProvider(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.generation))) return false
  if (!(str(value.name))) return false
  if (!(str(value.availability))) return false
  if (!(value.unavailableReason === undefined || str(value.unavailableReason))) return false
  if (!(isCapabilities(value.capabilities))) return false
  if (!(value.models === null || list(value.models, isModel))) return false
  if (!(value.configOptions === null || list(value.configOptions, isConfigOption))) return false
  if (!(value.permissionModes === null || list(value.permissionModes, str))) return false
  if (!(str(value.observedAt))) return false
  return true
}

export function isRoute(value) {
  if (!record(value)) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.providerGeneration))) return false
  if (!(str(value.modelId))) return false
  if (!(value.configValues === null || list(value.configValues, isConfigValue))) return false
  if (!(str(value.policy))) return false
  if (!(str(value.source))) return false
  if (!(str(value.reason))) return false
  return true
}

export function isSession(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.taskId))) return false
  if (!(str(value.projectId))) return false
  if (!(str(value.state))) return false
  if (!(isPreferences(value.preferences))) return false
  if (!(value.route === undefined || isRoute(value.route))) return false
  if (!(value.configOptions === null || list(value.configOptions, isConfigOption))) return false
  if (!(value.activePromptId === undefined || str(value.activePromptId))) return false
  if (!(dec(value.lastSequence))) return false
  if (!(str(value.recovery))) return false
  if (!(str(value.createdAt))) return false
  if (!(str(value.updatedAt))) return false
  if (!(str(value.checkoutRef))) return false
  if (!(value.worktreeRef === undefined || str(value.worktreeRef))) return false
  return true
}

export function isSessionEvent(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(str(value.taskId))) return false
  if (!(dec(value.sequence))) return false
  if (!(str(value.at))) return false
  if (!(str(value.kind))) return false
  if (!(value.message === undefined || isMessage(value.message))) return false
  if (!(value.tool === undefined || isToolUpdate(value.tool))) return false
  if (!(value.approval === undefined || isApproval(value.approval))) return false
  if (!(value.route === undefined || isRoute(value.route))) return false
  if (!(value.state === undefined || isStateUpdate(value.state))) return false
  if (!(value.config === undefined || isConfigUpdate(value.config))) return false
  if (!(value.failure === undefined || isFailure(value.failure))) return false
  return true
}

export function isSessionRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  return true
}

export function isSessionResult(value) {
  if (!record(value)) return false
  if (!(isSession(value.session))) return false
  return true
}

export function isStateUpdate(value) {
  if (!record(value)) return false
  if (!(str(value.state))) return false
  if (!(str(value.recovery))) return false
  return true
}

export function isStopRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(str(value.promptId))) return false
  return true
}

export function isTextInput(value) {
  if (!record(value)) return false
  if (!(value.inline === undefined || str(value.inline))) return false
  if (!(value.handleId === undefined || str(value.handleId))) return false
  return true
}

export function isToolUpdate(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.title))) return false
  if (!(str(value.status))) return false
  if (!(value.content === undefined || isTextInput(value.content))) return false
  return true
}
