// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface CredentialHandle {
  id: string
  providerId: string
  generation: string
  slot: string
}

export interface CredentialRequest {
  slot: string
}

export interface CredentialResult {
  credential: CredentialHandle
}

export interface EgressCancelRequest {
  invocationId: string
  jobId: string
}

export interface EgressCancelResult {
  job: EgressJob
}

export interface EgressFailure {
  code: string
  message: string
  retryable: boolean
}

export interface EgressJob {
  id: string
  state: string
  deadlineAt: string
  result?: EgressResult
  failure?: EgressFailure
}

export interface EgressReadRequest {
  invocationId: string
  jobId: string
}

export interface EgressReadResult {
  job: EgressJob
}

export interface EgressRequest {
  invocationId: string
  credentialId: string
  operation: string
  payloadId?: string
  idempotencyKey: string
  timeoutSeconds?: number
}

export interface EgressResult {
  statusCode: number
  payloadId: string
  retryAfterSeconds?: number
}

export interface EgressStartResult {
  job: EgressJob
}

export interface RevokeRequest {
  credentialId: string
}

export interface RevokeResult {
  revoked: boolean
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isCredentialHandle(value: unknown): value is CredentialHandle
export declare function isCredentialRequest(value: unknown): value is CredentialRequest
export declare function isCredentialResult(value: unknown): value is CredentialResult
export declare function isEgressCancelRequest(value: unknown): value is EgressCancelRequest
export declare function isEgressCancelResult(value: unknown): value is EgressCancelResult
export declare function isEgressFailure(value: unknown): value is EgressFailure
export declare function isEgressJob(value: unknown): value is EgressJob
export declare function isEgressReadRequest(value: unknown): value is EgressReadRequest
export declare function isEgressReadResult(value: unknown): value is EgressReadResult
export declare function isEgressRequest(value: unknown): value is EgressRequest
export declare function isEgressResult(value: unknown): value is EgressResult
export declare function isEgressStartResult(value: unknown): value is EgressStartResult
export declare function isRevokeRequest(value: unknown): value is RevokeRequest
export declare function isRevokeResult(value: unknown): value is RevokeResult
