// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  Credential: Object.freeze({"name":"cmd.gateway.provider-access.v1.credential","kind":"command","rev":1,"schema":"b83fc191119f8402957d001dd1aa8bf331afabfce8c8adf82877b44d88c6bab8","subject":"cmd.gateway.provider-access.v1.credential"}),
  EgressCancel: Object.freeze({"name":"cmd.gateway.provider-access.v1.egress-cancel","kind":"command","rev":1,"schema":"734dcb520a538e8a7abf9dec944bf18263c82975cd8cdf5559799b988f8a0cbf","subject":"cmd.gateway.provider-access.v1.egress-cancel"}),
  EgressRead: Object.freeze({"name":"cmd.gateway.provider-access.v1.egress-read","kind":"command","rev":1,"schema":"19cfd1cd805efb5823d2bed40447a4b4e2762380d29b87f7cac9bfbd81d7a8bf","subject":"cmd.gateway.provider-access.v1.egress-read"}),
  EgressStart: Object.freeze({"name":"cmd.gateway.provider-access.v1.egress-start","kind":"command","rev":1,"schema":"4fa2b827fd638437a327cc81d0a124c946d140645f534c649b1fbf5666ff199a","subject":"cmd.gateway.provider-access.v1.egress-start"}),
  Revoke: Object.freeze({"name":"cmd.gateway.provider-access.v1.revoke","kind":"command","rev":1,"schema":"1f0abb275fd8e1c5e7ba57d3b6655c777f164035591fff63608b2b5adedfb1ed","subject":"cmd.gateway.provider-access.v1.revoke"}),
})
