// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isCredentialHandle(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.generation))) return false
  if (!(str(value.slot))) return false
  return true
}

export function isCredentialRequest(value) {
  if (!record(value)) return false
  if (!(str(value.slot))) return false
  return true
}

export function isCredentialResult(value) {
  if (!record(value)) return false
  if (!(isCredentialHandle(value.credential))) return false
  return true
}

export function isEgressCancelRequest(value) {
  if (!record(value)) return false
  if (!(str(value.invocationId))) return false
  if (!(str(value.jobId))) return false
  return true
}

export function isEgressCancelResult(value) {
  if (!record(value)) return false
  if (!(isEgressJob(value.job))) return false
  return true
}

export function isEgressFailure(value) {
  if (!record(value)) return false
  if (!(str(value.code))) return false
  if (!(str(value.message))) return false
  if (!(bool(value.retryable))) return false
  return true
}

export function isEgressJob(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.state))) return false
  if (!(str(value.deadlineAt))) return false
  if (!(value.result === undefined || isEgressResult(value.result))) return false
  if (!(value.failure === undefined || isEgressFailure(value.failure))) return false
  return true
}

export function isEgressReadRequest(value) {
  if (!record(value)) return false
  if (!(str(value.invocationId))) return false
  if (!(str(value.jobId))) return false
  return true
}

export function isEgressReadResult(value) {
  if (!record(value)) return false
  if (!(isEgressJob(value.job))) return false
  return true
}

export function isEgressRequest(value) {
  if (!record(value)) return false
  if (!(str(value.invocationId))) return false
  if (!(str(value.credentialId))) return false
  if (!(str(value.operation))) return false
  if (!(value.payloadId === undefined || str(value.payloadId))) return false
  if (!(str(value.idempotencyKey))) return false
  if (!(value.timeoutSeconds === undefined || num(value.timeoutSeconds))) return false
  return true
}

export function isEgressResult(value) {
  if (!record(value)) return false
  if (!(num(value.statusCode))) return false
  if (!(str(value.payloadId))) return false
  if (!(value.retryAfterSeconds === undefined || num(value.retryAfterSeconds))) return false
  return true
}

export function isEgressStartResult(value) {
  if (!record(value)) return false
  if (!(isEgressJob(value.job))) return false
  return true
}

export function isRevokeRequest(value) {
  if (!record(value)) return false
  if (!(str(value.credentialId))) return false
  return true
}

export function isRevokeResult(value) {
  if (!record(value)) return false
  if (!(bool(value.revoked))) return false
  return true
}
