// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface ActingContext {
  actorId: string
  connectionId: string
  delegatedBy?: string
  originalActorId?: string
  executionMode: string
}

export interface AgentWork {
  goal?: ResourceRef
  requirements?: ResourceRef[]
  acceptance?: Criterion[]
  readiness: string
  reasons?: string[]
  poolId?: string
  dispatchId?: string
  worktreeId?: string
  reviewState: string
  claim?: Lease
}

export interface AgentWorkInput {
  goal?: ResourceRef
  requirements?: ResourceRef[]
  acceptance?: Criterion[]
  readiness: string
  reasons?: string[]
  poolId?: string
  dispatchId?: string
  worktreeId?: string
  reviewState: string
}

export interface Attachment {
  ref: ResourceRef
  name: string
  mediaType: string
  size: string
  checksum: string
  revision: string
}

export interface Binding {
  scope: Scope
  slot: string
  providerId: string
  resource: ResourceRef
  state: string
}

export interface Capabilities {
  revision: string
  operations: Capability[] | null
  transport: Transport
  recovery: RecoveryPolicy
}

export interface Capability {
  operation: string
  revision: number
  resourceKinds?: string[]
  formats?: string[]
  supported: boolean
  authorized: boolean
  reason?: string
  concurrency: string
  offline: string
  maxBatchItems?: number
}

export interface Change {
  resource: ResourceRef
  revision: string
  actorId: string
  origin: string
  operationId?: string
  kind: string
  occurredAt: string
}

export interface ChangesRequest {
  scope: Scope
  page: PageRequest
}

export interface ChangesResult {
  changes: Change[] | null
  page: PageInfo
  problem?: Problem
}

export interface ClaimRequest {
  scope: Scope
  mutation: Mutation
  resource: ResourceRef
  action: string
  leaseId?: string
  leaseFence?: string
  durationSeconds: number
}

export interface ClaimResult {
  lease?: Lease
  receipt: Receipt
}

export interface Comment {
  ref: ResourceRef
  body: RichBody
  authorId: string
  createdAt: string
  revision: string
  parent?: ResourceRef
  anchor?: FieldValue
  resolved: boolean
}

export interface CommentInput {
  body: RichBody
  parent?: ResourceRef
  anchor?: FieldValue
}

export interface Conflict {
  baseRevision: string
  remoteRevision: string
  localBody?: RichBody
  remoteBody?: RichBody
  localFields?: FieldValue[]
  remoteFields?: FieldValue[]
  payloadRef?: string
  resolutionOptions: string[] | null
}

export interface Criterion {
  id: string
  text: string
  state: string
  evidence?: Evidence[]
}

export interface DescribeRequest {
  scope: Scope
}

export interface DescribeResult {
  capabilities: Capabilities
  binding?: Binding
  problem?: Problem
}

export interface Evidence {
  id: string
  kind: string
  uri: string
  checksum?: string
  outcome: string
}

export interface FieldSchema {
  name: string
  type: string
  required: boolean
  editable: boolean
  multiple: boolean
  allowedValues?: FieldValue[]
}

export interface FieldValue {
  name: string
  type: string
  json: string
}

export interface Filter {
  field: string
  operator: string
  values?: FieldValue[]
}

export interface Grant {
  principalId: string
  principalKind: string
  operation: string
  effect: string
  inherited: boolean
}

export interface Invocation {
  id: string
  scope: Scope
  actor: ActingContext
  expiresAt: string
}

export interface ItemReceipt {
  itemId: string
  state: string
  resource?: ResourceRef
  revision?: string
  problem?: Problem
}

export interface Lease {
  id: string
  holderId: string
  fence: string
  expiresAt: string
  resource: ResourceRef
}

export interface Migration {
  id: string
  source: Scope
  destination: Scope
  state: string
  snapshotRevision: string
  cursor?: string
  entities?: MigrationEntity[]
  inventoryChecksum: string
  lossless: boolean
  writesPaused: boolean
}

export interface MigrationEntity {
  sourceRecordId: string
  source: ResourceRef
  destination?: ResourceRef
  revision: string
  checksum: string
  record?: Transfer
  problems?: Problem[]
}

export interface MigrationRequest {
  scope: Scope
  mutation: Mutation
  action: string
  migration: Migration
  page: PageRequest
}

export interface MigrationResult {
  migration?: Migration
  receipt: Receipt
  page: PageInfo
}

export interface Mutation {
  operationId: string
  expectedRevision?: string
  sourceBindingRevision: string
  dependsOn?: string[]
  origin: string
  createdAt: string
}

export interface NativeMapping {
  sessionId: string
  nativeId: string
  resource: ResourceRef
  bindingRevision: string
  providerGeneration: string
  lastOperationId: string
  direction: string
}

export interface OfflineOperation {
  scope: Scope
  actor: ActingContext
  mutation: Mutation
  operation: string
  payloadRef: string
  payloadChecksum: string
  receipt: Receipt
  persistedAt: string
  sessionId?: string
  nativeId?: string
}

export interface PageInfo {
  nextCursor?: string
  total: string
  totalKind: string
  consistency: string
  observedAt: string
}

export interface PageRequest {
  cursor?: string
  limit: number
}

export interface Person {
  id: string
  displayName: string
  assignable: boolean
}

export interface PlanningResource {
  ref: ResourceRef
  name: string
  state: string
  revision: string
  startsAt?: string
  endsAt?: string
  fields?: FieldValue[]
}

export interface Problem {
  code: string
  message: string
  field?: string
  retry: string
  retryAfterSeconds?: number
}

export interface Project {
  ref: ResourceRef
  name: string
  description?: RichBody
  revision: string
  fields?: FieldValue[]
}

export interface ProviderChangesRequest {
  invocation: Invocation
  request: ChangesRequest
}

export interface ProviderClaimRequest {
  invocation: Invocation
  request: ClaimRequest
}

export interface ProviderDescribeRequest {
  invocation: Invocation
  request: DescribeRequest
}

export interface ProviderMigrationRequest {
  invocation: Invocation
  request: MigrationRequest
}

export interface ProviderQueryRequest {
  invocation: Invocation
  request: QueryRequest
}

export interface ProviderReadRequest {
  invocation: Invocation
  request: ReadRequest
}

export interface ProviderRecoverRequest {
  invocation: Invocation
  request: RecoverRequest
}

export interface ProviderSchemaRequest {
  invocation: Invocation
  request: SchemaRequest
}

export interface ProviderTransferRequest {
  invocation: Invocation
  request: TransferRequest
}

export interface ProviderWriteRequest {
  invocation: Invocation
  request: WriteRequest
}

export interface Query {
  text?: string
  filters?: Filter[]
  sort?: Sort[]
  savedView?: ResourceRef
  nativeLanguage?: string
  nativeQuery?: string
  page: PageRequest
}

export interface QueryRequest {
  scope: Scope
  kind: string
  query: Query
}

export interface QueryResult {
  items?: WorkItem[]
  projects?: Project[]
  planning?: PlanningResource[]
  page: PageInfo
  problem?: Problem
}

export interface ReadRequest {
  scope: Scope
  resource: ResourceRef
  aspect: string
  page: PageRequest
}

export interface ReadResult {
  item?: WorkItem
  project?: Project
  planning?: PlanningResource
  relations?: Relation[]
  comments?: Comment[]
  attachments?: Attachment[]
  history?: Change[]
  watchers?: Person[]
  worklogs?: Worklog[]
  actions?: WorkflowAction[]
  grants?: Grant[]
  page: PageInfo
  problem?: Problem
}

export interface Receipt {
  operationId: string
  state: string
  remoteAccepted: boolean
  resource?: ResourceRef
  revision?: string
  items?: ItemReceipt[]
  problem?: Problem
  recoveryToken?: string
  observedAt: string
  conflict?: Conflict
}

export interface RecoverRequest {
  scope: Scope
  operationId: string
  recoveryToken?: string
}

export interface RecoverResult {
  receipt: Receipt
  offline?: OfflineOperation
}

export interface RecoveryPolicy {
  idempotency: string
  deduplicationSeconds: string
  receiptRetentionSeconds: string
  lookupByOperationId: boolean
  reconcileBeforeReplay: boolean
}

export interface Relation {
  kind: string
  source: ResourceRef
  target: ResourceRef
  type: string
}

export interface RelativePosition {
  container: ResourceRef
  before?: ResourceRef
  after?: ResourceRef
}

export interface ResourceRef {
  providerId: string
  installationId: string
  kind: string
  id: string
  key?: string
  url?: string
}

export interface RichBody {
  format: string
  version: string
  source: string
  plainText?: string
  rendered?: string
  lossy: boolean
}

export interface SchemaRequest {
  scope: Scope
  resource?: ResourceRef
  operation: string
  resourceKind: string
  page: PageRequest
}

export interface SchemaResult {
  fields: FieldSchema[] | null
  types?: string[]
  actions?: WorkflowAction[]
  people?: Person[]
  page: PageInfo
  problem?: Problem
}

export interface Scope {
  projectId: string
  environmentId: string
  tenantId: string
  bindingId: string
  bindingRevision: string
  providerGeneration: string
  capabilityRevision: string
}

export interface Sort {
  field: string
  direction: string
}

export interface Transfer {
  id: string
  resource: ResourceRef
  direction: string
  method: string
  uri: string
  expiresAt: string
  size: string
  mediaType: string
  checksum: string
  provenance: string
  verified: boolean
}

export interface TransferRequest {
  scope: Scope
  mutation: Mutation
  resource: ResourceRef
  action: string
  transferId?: string
  size: string
  mediaType: string
  checksum: string
}

export interface TransferResult {
  transfer?: Transfer
  receipt: Receipt
}

export interface Transport {
  kind: string
  protocolVersion?: string
  catalogRevision: string
  discovery: string
}

export interface WorkItem {
  ref: ResourceRef
  project: ResourceRef
  type: string
  title: string
  body?: RichBody
  status: string
  revision: string
  assigneeId?: string
  parent?: ResourceRef
  labels?: string[]
  fields?: FieldValue[]
  agent?: AgentWork
}

export interface WorkflowAction {
  id: string
  name: string
  targetStatus: string
  fields?: FieldSchema[]
}

export interface Worklog {
  ref: ResourceRef
  authorId: string
  startedAt: string
  seconds: string
  body?: RichBody
  revision: string
}

export interface WorklogInput {
  startedAt: string
  seconds: string
  body?: RichBody
}

export interface WriteRequest {
  scope: Scope
  mutation: Mutation
  action: string
  resource?: ResourceRef
  items?: ResourceRef[]
  title?: string
  body?: RichBody
  fields?: FieldValue[]
  clear?: string[]
  assigneeId?: string
  principalId?: string
  actionId?: string
  relation?: Relation
  position?: RelativePosition
  comment?: CommentInput
  worklog?: WorklogInput
  planning?: PlanningResource
  agent?: AgentWorkInput
  native?: NativeMapping
  grants?: Grant[]
  leaseFence?: string
  resourceKind?: string
  bulkAction?: string
  fieldDefinitions?: FieldSchema[]
  workflowActions?: WorkflowAction[]
}

export interface WriteResult {
  receipt: Receipt
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isActingContext(value: unknown): value is ActingContext
export declare function isAgentWork(value: unknown): value is AgentWork
export declare function isAgentWorkInput(value: unknown): value is AgentWorkInput
export declare function isAttachment(value: unknown): value is Attachment
export declare function isBinding(value: unknown): value is Binding
export declare function isCapabilities(value: unknown): value is Capabilities
export declare function isCapability(value: unknown): value is Capability
export declare function isChange(value: unknown): value is Change
export declare function isChangesRequest(value: unknown): value is ChangesRequest
export declare function isChangesResult(value: unknown): value is ChangesResult
export declare function isClaimRequest(value: unknown): value is ClaimRequest
export declare function isClaimResult(value: unknown): value is ClaimResult
export declare function isComment(value: unknown): value is Comment
export declare function isCommentInput(value: unknown): value is CommentInput
export declare function isConflict(value: unknown): value is Conflict
export declare function isCriterion(value: unknown): value is Criterion
export declare function isDescribeRequest(value: unknown): value is DescribeRequest
export declare function isDescribeResult(value: unknown): value is DescribeResult
export declare function isEvidence(value: unknown): value is Evidence
export declare function isFieldSchema(value: unknown): value is FieldSchema
export declare function isFieldValue(value: unknown): value is FieldValue
export declare function isFilter(value: unknown): value is Filter
export declare function isGrant(value: unknown): value is Grant
export declare function isInvocation(value: unknown): value is Invocation
export declare function isItemReceipt(value: unknown): value is ItemReceipt
export declare function isLease(value: unknown): value is Lease
export declare function isMigration(value: unknown): value is Migration
export declare function isMigrationEntity(value: unknown): value is MigrationEntity
export declare function isMigrationRequest(value: unknown): value is MigrationRequest
export declare function isMigrationResult(value: unknown): value is MigrationResult
export declare function isMutation(value: unknown): value is Mutation
export declare function isNativeMapping(value: unknown): value is NativeMapping
export declare function isOfflineOperation(value: unknown): value is OfflineOperation
export declare function isPageInfo(value: unknown): value is PageInfo
export declare function isPageRequest(value: unknown): value is PageRequest
export declare function isPerson(value: unknown): value is Person
export declare function isPlanningResource(value: unknown): value is PlanningResource
export declare function isProblem(value: unknown): value is Problem
export declare function isProject(value: unknown): value is Project
export declare function isProviderChangesRequest(value: unknown): value is ProviderChangesRequest
export declare function isProviderClaimRequest(value: unknown): value is ProviderClaimRequest
export declare function isProviderDescribeRequest(value: unknown): value is ProviderDescribeRequest
export declare function isProviderMigrationRequest(value: unknown): value is ProviderMigrationRequest
export declare function isProviderQueryRequest(value: unknown): value is ProviderQueryRequest
export declare function isProviderReadRequest(value: unknown): value is ProviderReadRequest
export declare function isProviderRecoverRequest(value: unknown): value is ProviderRecoverRequest
export declare function isProviderSchemaRequest(value: unknown): value is ProviderSchemaRequest
export declare function isProviderTransferRequest(value: unknown): value is ProviderTransferRequest
export declare function isProviderWriteRequest(value: unknown): value is ProviderWriteRequest
export declare function isQuery(value: unknown): value is Query
export declare function isQueryRequest(value: unknown): value is QueryRequest
export declare function isQueryResult(value: unknown): value is QueryResult
export declare function isReadRequest(value: unknown): value is ReadRequest
export declare function isReadResult(value: unknown): value is ReadResult
export declare function isReceipt(value: unknown): value is Receipt
export declare function isRecoverRequest(value: unknown): value is RecoverRequest
export declare function isRecoverResult(value: unknown): value is RecoverResult
export declare function isRecoveryPolicy(value: unknown): value is RecoveryPolicy
export declare function isRelation(value: unknown): value is Relation
export declare function isRelativePosition(value: unknown): value is RelativePosition
export declare function isResourceRef(value: unknown): value is ResourceRef
export declare function isRichBody(value: unknown): value is RichBody
export declare function isSchemaRequest(value: unknown): value is SchemaRequest
export declare function isSchemaResult(value: unknown): value is SchemaResult
export declare function isScope(value: unknown): value is Scope
export declare function isSort(value: unknown): value is Sort
export declare function isTransfer(value: unknown): value is Transfer
export declare function isTransferRequest(value: unknown): value is TransferRequest
export declare function isTransferResult(value: unknown): value is TransferResult
export declare function isTransport(value: unknown): value is Transport
export declare function isWorkItem(value: unknown): value is WorkItem
export declare function isWorkflowAction(value: unknown): value is WorkflowAction
export declare function isWorklog(value: unknown): value is Worklog
export declare function isWorklogInput(value: unknown): value is WorklogInput
export declare function isWriteRequest(value: unknown): value is WriteRequest
export declare function isWriteResult(value: unknown): value is WriteResult
