// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  Changes: Object.freeze({"name":"cmd.gateway.project-tasks.v1.changes","kind":"command","rev":1,"schema":"30435e50fbeb4c612ac5edb11e712d7b35b200a4562ec1938a22da839db66d1d","subject":"cmd.gateway.project-tasks.v1.changes"}),
  Claim: Object.freeze({"name":"cmd.gateway.project-tasks.v1.claim","kind":"command","rev":1,"schema":"3fd40b2d9138cd59272d18769bee2b178bbc7856892760c0524f5a51adabf114","subject":"cmd.gateway.project-tasks.v1.claim"}),
  Describe: Object.freeze({"name":"cmd.gateway.project-tasks.v1.describe","kind":"command","rev":1,"schema":"946bb5fd4a342c05f4c3a49d55c17a785a1e77ff5b2593cf57f5fc76de2d6460","subject":"cmd.gateway.project-tasks.v1.describe"}),
  ManageTransfer: Object.freeze({"name":"cmd.gateway.project-tasks.v1.transfer","kind":"command","rev":1,"schema":"6520e5bc3ee46884e84ae2f85b6a16dbfc0e7fa2790338a1b4e9d528f96373a6","subject":"cmd.gateway.project-tasks.v1.transfer"}),
  Migrate: Object.freeze({"name":"cmd.gateway.project-tasks.v1.migration","kind":"command","rev":1,"schema":"84ae4e6e3482e3acb3e3c0bcc971f4792f462393f1aac60c8723a56a0c4523ae","subject":"cmd.gateway.project-tasks.v1.migration"}),
  Read: Object.freeze({"name":"cmd.gateway.project-tasks.v1.read","kind":"command","rev":1,"schema":"e55595b4087b2e066893520576e9d0b32da2e4b5d6c2993daf9c54be017f2a47","subject":"cmd.gateway.project-tasks.v1.read"}),
  Recover: Object.freeze({"name":"cmd.gateway.project-tasks.v1.recover","kind":"command","rev":1,"schema":"1e65528e3d73395601d01ad170cecad0c54b8c5299ece7b893507b983bdefdab","subject":"cmd.gateway.project-tasks.v1.recover"}),
  Schema: Object.freeze({"name":"cmd.gateway.project-tasks.v1.schema","kind":"command","rev":1,"schema":"5df1a1a9e5994594e8d4a364828debc7b0d77240c15fad1e0c0a8d1c65764063","subject":"cmd.gateway.project-tasks.v1.schema"}),
  Search: Object.freeze({"name":"cmd.gateway.project-tasks.v1.query","kind":"command","rev":1,"schema":"6814ce375a74148e3f381978e19cfe2fa2aeb0a71f275a717bbaf4190c46bd12","subject":"cmd.gateway.project-tasks.v1.query"}),
  Write: Object.freeze({"name":"cmd.gateway.project-tasks.v1.write","kind":"command","rev":1,"schema":"9d5aaa2124495130ac466b63cacd71426fe46a270a475be59a074916923fb6ac","subject":"cmd.gateway.project-tasks.v1.write"}),
})
