// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isActingContext(value) {
  if (!record(value)) return false
  if (!(str(value.actorId))) return false
  if (!(str(value.connectionId))) return false
  if (!(value.delegatedBy === undefined || str(value.delegatedBy))) return false
  if (!(value.originalActorId === undefined || str(value.originalActorId))) return false
  if (!(str(value.executionMode))) return false
  return true
}

export function isAgentWork(value) {
  if (!record(value)) return false
  if (!(value.goal === undefined || isResourceRef(value.goal))) return false
  if (!(value.requirements === undefined || list(value.requirements, isResourceRef))) return false
  if (!(value.acceptance === undefined || list(value.acceptance, isCriterion))) return false
  if (!(str(value.readiness))) return false
  if (!(value.reasons === undefined || list(value.reasons, str))) return false
  if (!(value.poolId === undefined || str(value.poolId))) return false
  if (!(value.dispatchId === undefined || str(value.dispatchId))) return false
  if (!(value.worktreeId === undefined || str(value.worktreeId))) return false
  if (!(str(value.reviewState))) return false
  if (!(value.claim === undefined || isLease(value.claim))) return false
  return true
}

export function isAgentWorkInput(value) {
  if (!record(value)) return false
  if (!(value.goal === undefined || isResourceRef(value.goal))) return false
  if (!(value.requirements === undefined || list(value.requirements, isResourceRef))) return false
  if (!(value.acceptance === undefined || list(value.acceptance, isCriterion))) return false
  if (!(str(value.readiness))) return false
  if (!(value.reasons === undefined || list(value.reasons, str))) return false
  if (!(value.poolId === undefined || str(value.poolId))) return false
  if (!(value.dispatchId === undefined || str(value.dispatchId))) return false
  if (!(value.worktreeId === undefined || str(value.worktreeId))) return false
  if (!(str(value.reviewState))) return false
  return true
}

export function isAttachment(value) {
  if (!record(value)) return false
  if (!(isResourceRef(value.ref))) return false
  if (!(str(value.name))) return false
  if (!(str(value.mediaType))) return false
  if (!(dec(value.size))) return false
  if (!(str(value.checksum))) return false
  if (!(str(value.revision))) return false
  return true
}

export function isBinding(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(str(value.slot))) return false
  if (!(str(value.providerId))) return false
  if (!(isResourceRef(value.resource))) return false
  if (!(str(value.state))) return false
  return true
}

export function isCapabilities(value) {
  if (!record(value)) return false
  if (!(str(value.revision))) return false
  if (!(value.operations === null || list(value.operations, isCapability))) return false
  if (!(isTransport(value.transport))) return false
  if (!(isRecoveryPolicy(value.recovery))) return false
  return true
}

export function isCapability(value) {
  if (!record(value)) return false
  if (!(str(value.operation))) return false
  if (!(num(value.revision))) return false
  if (!(value.resourceKinds === undefined || list(value.resourceKinds, str))) return false
  if (!(value.formats === undefined || list(value.formats, str))) return false
  if (!(bool(value.supported))) return false
  if (!(bool(value.authorized))) return false
  if (!(value.reason === undefined || str(value.reason))) return false
  if (!(str(value.concurrency))) return false
  if (!(str(value.offline))) return false
  if (!(value.maxBatchItems === undefined || num(value.maxBatchItems))) return false
  return true
}

export function isChange(value) {
  if (!record(value)) return false
  if (!(isResourceRef(value.resource))) return false
  if (!(str(value.revision))) return false
  if (!(str(value.actorId))) return false
  if (!(str(value.origin))) return false
  if (!(value.operationId === undefined || str(value.operationId))) return false
  if (!(str(value.kind))) return false
  if (!(str(value.occurredAt))) return false
  return true
}

export function isChangesRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(isPageRequest(value.page))) return false
  return true
}

export function isChangesResult(value) {
  if (!record(value)) return false
  if (!(value.changes === null || list(value.changes, isChange))) return false
  if (!(isPageInfo(value.page))) return false
  if (!(value.problem === undefined || isProblem(value.problem))) return false
  return true
}

export function isClaimRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(isMutation(value.mutation))) return false
  if (!(isResourceRef(value.resource))) return false
  if (!(str(value.action))) return false
  if (!(value.leaseId === undefined || str(value.leaseId))) return false
  if (!(value.leaseFence === undefined || str(value.leaseFence))) return false
  if (!(num(value.durationSeconds))) return false
  return true
}

export function isClaimResult(value) {
  if (!record(value)) return false
  if (!(value.lease === undefined || isLease(value.lease))) return false
  if (!(isReceipt(value.receipt))) return false
  return true
}

export function isComment(value) {
  if (!record(value)) return false
  if (!(isResourceRef(value.ref))) return false
  if (!(isRichBody(value.body))) return false
  if (!(str(value.authorId))) return false
  if (!(str(value.createdAt))) return false
  if (!(str(value.revision))) return false
  if (!(value.parent === undefined || isResourceRef(value.parent))) return false
  if (!(value.anchor === undefined || isFieldValue(value.anchor))) return false
  if (!(bool(value.resolved))) return false
  return true
}

export function isCommentInput(value) {
  if (!record(value)) return false
  if (!(isRichBody(value.body))) return false
  if (!(value.parent === undefined || isResourceRef(value.parent))) return false
  if (!(value.anchor === undefined || isFieldValue(value.anchor))) return false
  return true
}

export function isConflict(value) {
  if (!record(value)) return false
  if (!(str(value.baseRevision))) return false
  if (!(str(value.remoteRevision))) return false
  if (!(value.localBody === undefined || isRichBody(value.localBody))) return false
  if (!(value.remoteBody === undefined || isRichBody(value.remoteBody))) return false
  if (!(value.localFields === undefined || list(value.localFields, isFieldValue))) return false
  if (!(value.remoteFields === undefined || list(value.remoteFields, isFieldValue))) return false
  if (!(value.payloadRef === undefined || str(value.payloadRef))) return false
  if (!(value.resolutionOptions === null || list(value.resolutionOptions, str))) return false
  return true
}

export function isCriterion(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.text))) return false
  if (!(str(value.state))) return false
  if (!(value.evidence === undefined || list(value.evidence, isEvidence))) return false
  return true
}

export function isDescribeRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  return true
}

export function isDescribeResult(value) {
  if (!record(value)) return false
  if (!(isCapabilities(value.capabilities))) return false
  if (!(value.binding === undefined || isBinding(value.binding))) return false
  if (!(value.problem === undefined || isProblem(value.problem))) return false
  return true
}

export function isEvidence(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.kind))) return false
  if (!(str(value.uri))) return false
  if (!(value.checksum === undefined || str(value.checksum))) return false
  if (!(str(value.outcome))) return false
  return true
}

export function isFieldSchema(value) {
  if (!record(value)) return false
  if (!(str(value.name))) return false
  if (!(str(value.type))) return false
  if (!(bool(value.required))) return false
  if (!(bool(value.editable))) return false
  if (!(bool(value.multiple))) return false
  if (!(value.allowedValues === undefined || list(value.allowedValues, isFieldValue))) return false
  return true
}

export function isFieldValue(value) {
  if (!record(value)) return false
  if (!(str(value.name))) return false
  if (!(str(value.type))) return false
  if (!(str(value.json))) return false
  return true
}

export function isFilter(value) {
  if (!record(value)) return false
  if (!(str(value.field))) return false
  if (!(str(value.operator))) return false
  if (!(value.values === undefined || list(value.values, isFieldValue))) return false
  return true
}

export function isGrant(value) {
  if (!record(value)) return false
  if (!(str(value.principalId))) return false
  if (!(str(value.principalKind))) return false
  if (!(str(value.operation))) return false
  if (!(str(value.effect))) return false
  if (!(bool(value.inherited))) return false
  return true
}

export function isInvocation(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(isScope(value.scope))) return false
  if (!(isActingContext(value.actor))) return false
  if (!(str(value.expiresAt))) return false
  return true
}

export function isItemReceipt(value) {
  if (!record(value)) return false
  if (!(str(value.itemId))) return false
  if (!(str(value.state))) return false
  if (!(value.resource === undefined || isResourceRef(value.resource))) return false
  if (!(value.revision === undefined || str(value.revision))) return false
  if (!(value.problem === undefined || isProblem(value.problem))) return false
  return true
}

export function isLease(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.holderId))) return false
  if (!(str(value.fence))) return false
  if (!(str(value.expiresAt))) return false
  if (!(isResourceRef(value.resource))) return false
  return true
}

export function isMigration(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(isScope(value.source))) return false
  if (!(isScope(value.destination))) return false
  if (!(str(value.state))) return false
  if (!(str(value.snapshotRevision))) return false
  if (!(value.cursor === undefined || str(value.cursor))) return false
  if (!(value.entities === undefined || list(value.entities, isMigrationEntity))) return false
  if (!(str(value.inventoryChecksum))) return false
  if (!(bool(value.lossless))) return false
  if (!(bool(value.writesPaused))) return false
  return true
}

export function isMigrationEntity(value) {
  if (!record(value)) return false
  if (!(str(value.sourceRecordId))) return false
  if (!(isResourceRef(value.source))) return false
  if (!(value.destination === undefined || isResourceRef(value.destination))) return false
  if (!(str(value.revision))) return false
  if (!(str(value.checksum))) return false
  if (!(value.record === undefined || isTransfer(value.record))) return false
  if (!(value.problems === undefined || list(value.problems, isProblem))) return false
  return true
}

export function isMigrationRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(isMutation(value.mutation))) return false
  if (!(str(value.action))) return false
  if (!(isMigration(value.migration))) return false
  if (!(isPageRequest(value.page))) return false
  return true
}

export function isMigrationResult(value) {
  if (!record(value)) return false
  if (!(value.migration === undefined || isMigration(value.migration))) return false
  if (!(isReceipt(value.receipt))) return false
  if (!(isPageInfo(value.page))) return false
  return true
}

export function isMutation(value) {
  if (!record(value)) return false
  if (!(str(value.operationId))) return false
  if (!(value.expectedRevision === undefined || str(value.expectedRevision))) return false
  if (!(str(value.sourceBindingRevision))) return false
  if (!(value.dependsOn === undefined || list(value.dependsOn, str))) return false
  if (!(str(value.origin))) return false
  if (!(str(value.createdAt))) return false
  return true
}

export function isNativeMapping(value) {
  if (!record(value)) return false
  if (!(str(value.sessionId))) return false
  if (!(str(value.nativeId))) return false
  if (!(isResourceRef(value.resource))) return false
  if (!(str(value.bindingRevision))) return false
  if (!(str(value.providerGeneration))) return false
  if (!(str(value.lastOperationId))) return false
  if (!(str(value.direction))) return false
  return true
}

export function isOfflineOperation(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(isActingContext(value.actor))) return false
  if (!(isMutation(value.mutation))) return false
  if (!(str(value.operation))) return false
  if (!(str(value.payloadRef))) return false
  if (!(str(value.payloadChecksum))) return false
  if (!(isReceipt(value.receipt))) return false
  if (!(str(value.persistedAt))) return false
  if (!(value.sessionId === undefined || str(value.sessionId))) return false
  if (!(value.nativeId === undefined || str(value.nativeId))) return false
  return true
}

export function isPageInfo(value) {
  if (!record(value)) return false
  if (!(value.nextCursor === undefined || str(value.nextCursor))) return false
  if (!(dec(value.total))) return false
  if (!(str(value.totalKind))) return false
  if (!(str(value.consistency))) return false
  if (!(str(value.observedAt))) return false
  return true
}

export function isPageRequest(value) {
  if (!record(value)) return false
  if (!(value.cursor === undefined || str(value.cursor))) return false
  if (!(num(value.limit))) return false
  return true
}

export function isPerson(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.displayName))) return false
  if (!(bool(value.assignable))) return false
  return true
}

export function isPlanningResource(value) {
  if (!record(value)) return false
  if (!(isResourceRef(value.ref))) return false
  if (!(str(value.name))) return false
  if (!(str(value.state))) return false
  if (!(str(value.revision))) return false
  if (!(value.startsAt === undefined || str(value.startsAt))) return false
  if (!(value.endsAt === undefined || str(value.endsAt))) return false
  if (!(value.fields === undefined || list(value.fields, isFieldValue))) return false
  return true
}

export function isProblem(value) {
  if (!record(value)) return false
  if (!(str(value.code))) return false
  if (!(str(value.message))) return false
  if (!(value.field === undefined || str(value.field))) return false
  if (!(str(value.retry))) return false
  if (!(value.retryAfterSeconds === undefined || num(value.retryAfterSeconds))) return false
  return true
}

export function isProject(value) {
  if (!record(value)) return false
  if (!(isResourceRef(value.ref))) return false
  if (!(str(value.name))) return false
  if (!(value.description === undefined || isRichBody(value.description))) return false
  if (!(str(value.revision))) return false
  if (!(value.fields === undefined || list(value.fields, isFieldValue))) return false
  return true
}

export function isProviderChangesRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isChangesRequest(value.request))) return false
  return true
}

export function isProviderClaimRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isClaimRequest(value.request))) return false
  return true
}

export function isProviderDescribeRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isDescribeRequest(value.request))) return false
  return true
}

export function isProviderMigrationRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isMigrationRequest(value.request))) return false
  return true
}

export function isProviderQueryRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isQueryRequest(value.request))) return false
  return true
}

export function isProviderReadRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isReadRequest(value.request))) return false
  return true
}

export function isProviderRecoverRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isRecoverRequest(value.request))) return false
  return true
}

export function isProviderSchemaRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isSchemaRequest(value.request))) return false
  return true
}

export function isProviderTransferRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isTransferRequest(value.request))) return false
  return true
}

export function isProviderWriteRequest(value) {
  if (!record(value)) return false
  if (!(isInvocation(value.invocation))) return false
  if (!(isWriteRequest(value.request))) return false
  return true
}

export function isQuery(value) {
  if (!record(value)) return false
  if (!(value.text === undefined || str(value.text))) return false
  if (!(value.filters === undefined || list(value.filters, isFilter))) return false
  if (!(value.sort === undefined || list(value.sort, isSort))) return false
  if (!(value.savedView === undefined || isResourceRef(value.savedView))) return false
  if (!(value.nativeLanguage === undefined || str(value.nativeLanguage))) return false
  if (!(value.nativeQuery === undefined || str(value.nativeQuery))) return false
  if (!(isPageRequest(value.page))) return false
  return true
}

export function isQueryRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(str(value.kind))) return false
  if (!(isQuery(value.query))) return false
  return true
}

export function isQueryResult(value) {
  if (!record(value)) return false
  if (!(value.items === undefined || list(value.items, isWorkItem))) return false
  if (!(value.projects === undefined || list(value.projects, isProject))) return false
  if (!(value.planning === undefined || list(value.planning, isPlanningResource))) return false
  if (!(isPageInfo(value.page))) return false
  if (!(value.problem === undefined || isProblem(value.problem))) return false
  return true
}

export function isReadRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(isResourceRef(value.resource))) return false
  if (!(str(value.aspect))) return false
  if (!(isPageRequest(value.page))) return false
  return true
}

export function isReadResult(value) {
  if (!record(value)) return false
  if (!(value.item === undefined || isWorkItem(value.item))) return false
  if (!(value.project === undefined || isProject(value.project))) return false
  if (!(value.planning === undefined || isPlanningResource(value.planning))) return false
  if (!(value.relations === undefined || list(value.relations, isRelation))) return false
  if (!(value.comments === undefined || list(value.comments, isComment))) return false
  if (!(value.attachments === undefined || list(value.attachments, isAttachment))) return false
  if (!(value.history === undefined || list(value.history, isChange))) return false
  if (!(value.watchers === undefined || list(value.watchers, isPerson))) return false
  if (!(value.worklogs === undefined || list(value.worklogs, isWorklog))) return false
  if (!(value.actions === undefined || list(value.actions, isWorkflowAction))) return false
  if (!(value.grants === undefined || list(value.grants, isGrant))) return false
  if (!(isPageInfo(value.page))) return false
  if (!(value.problem === undefined || isProblem(value.problem))) return false
  return true
}

export function isReceipt(value) {
  if (!record(value)) return false
  if (!(str(value.operationId))) return false
  if (!(str(value.state))) return false
  if (!(bool(value.remoteAccepted))) return false
  if (!(value.resource === undefined || isResourceRef(value.resource))) return false
  if (!(value.revision === undefined || str(value.revision))) return false
  if (!(value.items === undefined || list(value.items, isItemReceipt))) return false
  if (!(value.problem === undefined || isProblem(value.problem))) return false
  if (!(value.recoveryToken === undefined || str(value.recoveryToken))) return false
  if (!(str(value.observedAt))) return false
  if (!(value.conflict === undefined || isConflict(value.conflict))) return false
  return true
}

export function isRecoverRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(str(value.operationId))) return false
  if (!(value.recoveryToken === undefined || str(value.recoveryToken))) return false
  return true
}

export function isRecoverResult(value) {
  if (!record(value)) return false
  if (!(isReceipt(value.receipt))) return false
  if (!(value.offline === undefined || isOfflineOperation(value.offline))) return false
  return true
}

export function isRecoveryPolicy(value) {
  if (!record(value)) return false
  if (!(str(value.idempotency))) return false
  if (!(dec(value.deduplicationSeconds))) return false
  if (!(dec(value.receiptRetentionSeconds))) return false
  if (!(bool(value.lookupByOperationId))) return false
  if (!(bool(value.reconcileBeforeReplay))) return false
  return true
}

export function isRelation(value) {
  if (!record(value)) return false
  if (!(str(value.kind))) return false
  if (!(isResourceRef(value.source))) return false
  if (!(isResourceRef(value.target))) return false
  if (!(str(value.type))) return false
  return true
}

export function isRelativePosition(value) {
  if (!record(value)) return false
  if (!(isResourceRef(value.container))) return false
  if (!(value.before === undefined || isResourceRef(value.before))) return false
  if (!(value.after === undefined || isResourceRef(value.after))) return false
  return true
}

export function isResourceRef(value) {
  if (!record(value)) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.installationId))) return false
  if (!(str(value.kind))) return false
  if (!(str(value.id))) return false
  if (!(value.key === undefined || str(value.key))) return false
  if (!(value.url === undefined || str(value.url))) return false
  return true
}

export function isRichBody(value) {
  if (!record(value)) return false
  if (!(str(value.format))) return false
  if (!(str(value.version))) return false
  if (!(str(value.source))) return false
  if (!(value.plainText === undefined || str(value.plainText))) return false
  if (!(value.rendered === undefined || str(value.rendered))) return false
  if (!(bool(value.lossy))) return false
  return true
}

export function isSchemaRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(value.resource === undefined || isResourceRef(value.resource))) return false
  if (!(str(value.operation))) return false
  if (!(str(value.resourceKind))) return false
  if (!(isPageRequest(value.page))) return false
  return true
}

export function isSchemaResult(value) {
  if (!record(value)) return false
  if (!(value.fields === null || list(value.fields, isFieldSchema))) return false
  if (!(value.types === undefined || list(value.types, str))) return false
  if (!(value.actions === undefined || list(value.actions, isWorkflowAction))) return false
  if (!(value.people === undefined || list(value.people, isPerson))) return false
  if (!(isPageInfo(value.page))) return false
  if (!(value.problem === undefined || isProblem(value.problem))) return false
  return true
}

export function isScope(value) {
  if (!record(value)) return false
  if (!(str(value.projectId))) return false
  if (!(str(value.environmentId))) return false
  if (!(str(value.tenantId))) return false
  if (!(str(value.bindingId))) return false
  if (!(str(value.bindingRevision))) return false
  if (!(str(value.providerGeneration))) return false
  if (!(str(value.capabilityRevision))) return false
  return true
}

export function isSort(value) {
  if (!record(value)) return false
  if (!(str(value.field))) return false
  if (!(str(value.direction))) return false
  return true
}

export function isTransfer(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(isResourceRef(value.resource))) return false
  if (!(str(value.direction))) return false
  if (!(str(value.method))) return false
  if (!(str(value.uri))) return false
  if (!(str(value.expiresAt))) return false
  if (!(dec(value.size))) return false
  if (!(str(value.mediaType))) return false
  if (!(str(value.checksum))) return false
  if (!(str(value.provenance))) return false
  if (!(bool(value.verified))) return false
  return true
}

export function isTransferRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(isMutation(value.mutation))) return false
  if (!(isResourceRef(value.resource))) return false
  if (!(str(value.action))) return false
  if (!(value.transferId === undefined || str(value.transferId))) return false
  if (!(dec(value.size))) return false
  if (!(str(value.mediaType))) return false
  if (!(str(value.checksum))) return false
  return true
}

export function isTransferResult(value) {
  if (!record(value)) return false
  if (!(value.transfer === undefined || isTransfer(value.transfer))) return false
  if (!(isReceipt(value.receipt))) return false
  return true
}

export function isTransport(value) {
  if (!record(value)) return false
  if (!(str(value.kind))) return false
  if (!(value.protocolVersion === undefined || str(value.protocolVersion))) return false
  if (!(str(value.catalogRevision))) return false
  if (!(str(value.discovery))) return false
  return true
}

export function isWorkItem(value) {
  if (!record(value)) return false
  if (!(isResourceRef(value.ref))) return false
  if (!(isResourceRef(value.project))) return false
  if (!(str(value.type))) return false
  if (!(str(value.title))) return false
  if (!(value.body === undefined || isRichBody(value.body))) return false
  if (!(str(value.status))) return false
  if (!(str(value.revision))) return false
  if (!(value.assigneeId === undefined || str(value.assigneeId))) return false
  if (!(value.parent === undefined || isResourceRef(value.parent))) return false
  if (!(value.labels === undefined || list(value.labels, str))) return false
  if (!(value.fields === undefined || list(value.fields, isFieldValue))) return false
  if (!(value.agent === undefined || isAgentWork(value.agent))) return false
  return true
}

export function isWorkflowAction(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.name))) return false
  if (!(str(value.targetStatus))) return false
  if (!(value.fields === undefined || list(value.fields, isFieldSchema))) return false
  return true
}

export function isWorklog(value) {
  if (!record(value)) return false
  if (!(isResourceRef(value.ref))) return false
  if (!(str(value.authorId))) return false
  if (!(str(value.startedAt))) return false
  if (!(dec(value.seconds))) return false
  if (!(value.body === undefined || isRichBody(value.body))) return false
  if (!(str(value.revision))) return false
  return true
}

export function isWorklogInput(value) {
  if (!record(value)) return false
  if (!(str(value.startedAt))) return false
  if (!(dec(value.seconds))) return false
  if (!(value.body === undefined || isRichBody(value.body))) return false
  return true
}

export function isWriteRequest(value) {
  if (!record(value)) return false
  if (!(isScope(value.scope))) return false
  if (!(isMutation(value.mutation))) return false
  if (!(str(value.action))) return false
  if (!(value.resource === undefined || isResourceRef(value.resource))) return false
  if (!(value.items === undefined || list(value.items, isResourceRef))) return false
  if (!(value.title === undefined || str(value.title))) return false
  if (!(value.body === undefined || isRichBody(value.body))) return false
  if (!(value.fields === undefined || list(value.fields, isFieldValue))) return false
  if (!(value.clear === undefined || list(value.clear, str))) return false
  if (!(value.assigneeId === undefined || str(value.assigneeId))) return false
  if (!(value.principalId === undefined || str(value.principalId))) return false
  if (!(value.actionId === undefined || str(value.actionId))) return false
  if (!(value.relation === undefined || isRelation(value.relation))) return false
  if (!(value.position === undefined || isRelativePosition(value.position))) return false
  if (!(value.comment === undefined || isCommentInput(value.comment))) return false
  if (!(value.worklog === undefined || isWorklogInput(value.worklog))) return false
  if (!(value.planning === undefined || isPlanningResource(value.planning))) return false
  if (!(value.agent === undefined || isAgentWorkInput(value.agent))) return false
  if (!(value.native === undefined || isNativeMapping(value.native))) return false
  if (!(value.grants === undefined || list(value.grants, isGrant))) return false
  if (!(value.leaseFence === undefined || str(value.leaseFence))) return false
  if (!(value.resourceKind === undefined || str(value.resourceKind))) return false
  if (!(value.bulkAction === undefined || str(value.bulkAction))) return false
  if (!(value.fieldDefinitions === undefined || list(value.fieldDefinitions, isFieldSchema))) return false
  if (!(value.workflowActions === undefined || list(value.workflowActions, isWorkflowAction))) return false
  return true
}

export function isWriteResult(value) {
  if (!record(value)) return false
  if (!(isReceipt(value.receipt))) return false
  return true
}
