// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -package=webapps -out <path>

package webapps

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	App |
		Attachment |
		Conversation |
		ConversationAnswerRequest |
		ConversationAnswerResult |
		ConversationApproveRequest |
		ConversationApproveResult |
		ConversationSendRequest |
		ConversationSendResult |
		CreateRequest |
		CreateResult |
		CreationEligibilityRequest |
		CreationEligibilityResult |
		ListRequest |
		ListResult |
		LogEntry |
		Message |
		Preview |
		PreviewCapabilities |
		PreviewNavigateRequest |
		PreviewNavigateResult |
		PreviewOpenExternalRequest |
		PreviewOpenExternalResult |
		PreviewResolveRequest |
		PreviewResolveResult |
		ProjectDirectoryContext |
		ProjectTarget |
		Provider |
		Run |
		RunStopRequest |
		RunStopResult |
		RuntimeEvent |
		ServiceStatus |
		ServicesLogsRequest |
		ServicesLogsResult |
		ServicesStartRequest |
		ServicesStartResult |
		ServicesStopRequest |
		ServicesStopResult |
		Target |
		ToolActivity
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "webapps: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "webapps: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// List is the generated descriptor for cmd.gateway.web-apps.v1.list revision 1.
var List = Command[ListRequest, ListResult]{c: plugin.NewCommand[ListRequest, ListResult]("cmd.gateway.web-apps.v1.list", 1, "cbf6469648ba690382b908ff60d8ff7b5fe4fdac18d7c65fc4309a42376c136c", "cmd.gateway.web-apps.v1.list")}

// Create is the generated descriptor for cmd.gateway.web-apps.v1.create revision 1.
var Create = Command[CreateRequest, CreateResult]{c: plugin.NewCommand[CreateRequest, CreateResult]("cmd.gateway.web-apps.v1.create", 1, "b36c5035182f66128eecb04d19ff7bbfc457bdf4c4428ec072abad36114383d1", "cmd.gateway.web-apps.v1.create")}

// CheckCreationEligibility is the generated descriptor for cmd.gateway.web-apps.v1.creation-eligibility revision 1.
var CheckCreationEligibility = Command[CreationEligibilityRequest, CreationEligibilityResult]{c: plugin.NewCommand[CreationEligibilityRequest, CreationEligibilityResult]("cmd.gateway.web-apps.v1.creation-eligibility", 1, "33df73e2b569ef57351a3b677cba87a054585fd43a1ff982c58b3a58f6111ddf", "cmd.gateway.web-apps.v1.creation-eligibility")}

// SendConversationMessage is the generated descriptor for cmd.gateway.web-apps.v1.conversation.send revision 1.
var SendConversationMessage = Command[ConversationSendRequest, ConversationSendResult]{c: plugin.NewCommand[ConversationSendRequest, ConversationSendResult]("cmd.gateway.web-apps.v1.conversation.send", 1, "8c198bf95569cb7d9d2d346da4ee685be14be8a000b70698dcc047ae4428c69f", "cmd.gateway.web-apps.v1.conversation.send")}

// ApproveConversationRequest is the generated descriptor for cmd.gateway.web-apps.v1.conversation.approve revision 1.
var ApproveConversationRequest = Command[ConversationApproveRequest, ConversationApproveResult]{c: plugin.NewCommand[ConversationApproveRequest, ConversationApproveResult]("cmd.gateway.web-apps.v1.conversation.approve", 1, "e046d65de2b4224cf1a0b0e629146e21de9205fe48a861444cb9aa048d734621", "cmd.gateway.web-apps.v1.conversation.approve")}

// AnswerConversationRequest is the generated descriptor for cmd.gateway.web-apps.v1.conversation.answer revision 1.
var AnswerConversationRequest = Command[ConversationAnswerRequest, ConversationAnswerResult]{c: plugin.NewCommand[ConversationAnswerRequest, ConversationAnswerResult]("cmd.gateway.web-apps.v1.conversation.answer", 1, "796d473b699f1ae91c968cabccf3764051ad2c1ce6bf2977ee0b934555fae086", "cmd.gateway.web-apps.v1.conversation.answer")}

// StopRun is the generated descriptor for cmd.gateway.web-apps.v1.run.stop revision 1.
var StopRun = Command[RunStopRequest, RunStopResult]{c: plugin.NewCommand[RunStopRequest, RunStopResult]("cmd.gateway.web-apps.v1.run.stop", 1, "7cdc315c8824ae8ba869bcd1d5dbefc95a0f91d528944b1c9bf8ac14adc12aa8", "cmd.gateway.web-apps.v1.run.stop")}

// StartServices is the generated descriptor for cmd.gateway.web-apps.v1.services.start revision 1.
var StartServices = Command[ServicesStartRequest, ServicesStartResult]{c: plugin.NewCommand[ServicesStartRequest, ServicesStartResult]("cmd.gateway.web-apps.v1.services.start", 1, "53df9abba0d5dbbbc39aec295dffacfcb5cb6813c12a6e3c54238ef582494128", "cmd.gateway.web-apps.v1.services.start")}

// StopServices is the generated descriptor for cmd.gateway.web-apps.v1.services.stop revision 1.
var StopServices = Command[ServicesStopRequest, ServicesStopResult]{c: plugin.NewCommand[ServicesStopRequest, ServicesStopResult]("cmd.gateway.web-apps.v1.services.stop", 1, "c062f1af1418a834b5b2c72f54ade5a38fe67de97586971b42bd690f3f463742", "cmd.gateway.web-apps.v1.services.stop")}

// ReadServiceLogs is the generated descriptor for cmd.gateway.web-apps.v1.services.logs revision 1.
var ReadServiceLogs = Command[ServicesLogsRequest, ServicesLogsResult]{c: plugin.NewCommand[ServicesLogsRequest, ServicesLogsResult]("cmd.gateway.web-apps.v1.services.logs", 1, "42d6ea8c2a5ecdf68c6e13fc7509a7ddda1d22caac49fa9333954033b7320bac", "cmd.gateway.web-apps.v1.services.logs")}

// ResolvePreview is the generated descriptor for cmd.gateway.web-apps.v1.preview.resolve revision 1.
var ResolvePreview = Command[PreviewResolveRequest, PreviewResolveResult]{c: plugin.NewCommand[PreviewResolveRequest, PreviewResolveResult]("cmd.gateway.web-apps.v1.preview.resolve", 1, "0ff37ad474ebfb345739a546d2aba9d5d46c39af7205cd0c1ce0a53f9e9311ec", "cmd.gateway.web-apps.v1.preview.resolve")}

// NavigatePreview is the generated descriptor for cmd.gateway.web-apps.v1.preview.navigate revision 1.
var NavigatePreview = Command[PreviewNavigateRequest, PreviewNavigateResult]{c: plugin.NewCommand[PreviewNavigateRequest, PreviewNavigateResult]("cmd.gateway.web-apps.v1.preview.navigate", 1, "586135f31c16c97466966f93d6459d2b33e37d23aa893e02951b3d0f2db3e7ec", "cmd.gateway.web-apps.v1.preview.navigate")}

// OpenPreviewExternal is the generated descriptor for cmd.gateway.web-apps.v1.preview.open-external revision 1.
var OpenPreviewExternal = Command[PreviewOpenExternalRequest, PreviewOpenExternalResult]{c: plugin.NewCommand[PreviewOpenExternalRequest, PreviewOpenExternalResult]("cmd.gateway.web-apps.v1.preview.open-external", 1, "7ac6cd7787d2e7c83a9c71a7736c18bc8952ca97dfea2f9280c20a1cabdb8b95", "cmd.gateway.web-apps.v1.preview.open-external")}

// Changed is the generated descriptor for event.web-apps.v1.changed revision 1.
var Changed = Event[RuntimeEvent]{e: plugin.NewEvent[RuntimeEvent]("event.web-apps.v1.changed", 1, "573d4b52aae84c92bc95aa7dc56a9ffbbb9cb8bbb85a6d73c523dd2ad2a0de47", "event.web-apps.v1.changed")}

// Events is the generated descriptor for stream.web-apps.v1.events revision 1.
var Events = Stream[RuntimeEvent]{s: plugin.NewStreamDescriptor[RuntimeEvent]("WEB_APPS_EVENTS", 1, "981e41df754f7f7977a22804eeb7a406a7db5f744659dd640d148fa637a55913", "event.web-apps.v1.changed")}
