// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -package=webapps -out <path>

package webapps

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	App |
		Attachment |
		Conversation |
		ConversationAnswerRequest |
		ConversationAnswerResult |
		ConversationApproveRequest |
		ConversationApproveResult |
		ConversationSendRequest |
		ConversationSendResult |
		CreateRequest |
		CreateResult |
		CreationEligibilityRequest |
		CreationEligibilityResult |
		ListRequest |
		ListResult |
		LogEntry |
		Message |
		Preview |
		PreviewCapabilities |
		PreviewNavigateRequest |
		PreviewNavigateResult |
		PreviewOpenExternalRequest |
		PreviewOpenExternalResult |
		PreviewResolveRequest |
		PreviewResolveResult |
		ProjectDirectoryContext |
		ProjectTarget |
		Provider |
		Run |
		RunStopRequest |
		RunStopResult |
		RuntimeEvent |
		ServiceStatus |
		ServicesLogsRequest |
		ServicesLogsResult |
		ServicesStartRequest |
		ServicesStartResult |
		ServicesStopRequest |
		ServicesStopResult |
		Target |
		ToolActivity
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "webapps: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "webapps: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// List is the generated descriptor for cmd.web-apps.v1.list revision 1.
var List = Command[ListRequest, ListResult]{c: plugin.NewCommand[ListRequest, ListResult]("cmd.web-apps.v1.list", 1, "4bb46fbc3c737fdd15e51957d4431f5f74fe6b4858926ac568b1e5a5183aed97", "cmd.web-apps.v1.list")}

// Create is the generated descriptor for cmd.web-apps.v1.create revision 1.
var Create = Command[CreateRequest, CreateResult]{c: plugin.NewCommand[CreateRequest, CreateResult]("cmd.web-apps.v1.create", 1, "b90d842f26948f74ddc8b6470585cd0b4932282a00da68ce9531177cbdd7faa4", "cmd.web-apps.v1.create")}

// CheckCreationEligibility is the generated descriptor for cmd.web-apps.v1.creation-eligibility revision 1.
var CheckCreationEligibility = Command[CreationEligibilityRequest, CreationEligibilityResult]{c: plugin.NewCommand[CreationEligibilityRequest, CreationEligibilityResult]("cmd.web-apps.v1.creation-eligibility", 1, "0b476ef6a9b31e3dbcb434a7a7a9addf1afbdd12b17437e5c65a723f184a3a1c", "cmd.web-apps.v1.creation-eligibility")}

// SendConversationMessage is the generated descriptor for cmd.web-apps.v1.conversation.send revision 1.
var SendConversationMessage = Command[ConversationSendRequest, ConversationSendResult]{c: plugin.NewCommand[ConversationSendRequest, ConversationSendResult]("cmd.web-apps.v1.conversation.send", 1, "458f2ecce83fc55f282d2602f3ab20ffe9f51438f8e8fbb2971da63945b9ceae", "cmd.web-apps.v1.conversation.send")}

// ApproveConversationRequest is the generated descriptor for cmd.web-apps.v1.conversation.approve revision 1.
var ApproveConversationRequest = Command[ConversationApproveRequest, ConversationApproveResult]{c: plugin.NewCommand[ConversationApproveRequest, ConversationApproveResult]("cmd.web-apps.v1.conversation.approve", 1, "5706a5fe3250b9049d30da45816316f020d03f66d8b4452847b6d5c6678e3bec", "cmd.web-apps.v1.conversation.approve")}

// AnswerConversationRequest is the generated descriptor for cmd.web-apps.v1.conversation.answer revision 1.
var AnswerConversationRequest = Command[ConversationAnswerRequest, ConversationAnswerResult]{c: plugin.NewCommand[ConversationAnswerRequest, ConversationAnswerResult]("cmd.web-apps.v1.conversation.answer", 1, "abcfba5c232d979146ddd62c008421d7ff8e7d9810f68b85e4b1ac6f72312aea", "cmd.web-apps.v1.conversation.answer")}

// StopRun is the generated descriptor for cmd.web-apps.v1.run.stop revision 1.
var StopRun = Command[RunStopRequest, RunStopResult]{c: plugin.NewCommand[RunStopRequest, RunStopResult]("cmd.web-apps.v1.run.stop", 1, "f3a4508b2dfd799270be3f622dddf626179875404437d2eda4dad08d4c196f54", "cmd.web-apps.v1.run.stop")}

// StartServices is the generated descriptor for cmd.web-apps.v1.services.start revision 1.
var StartServices = Command[ServicesStartRequest, ServicesStartResult]{c: plugin.NewCommand[ServicesStartRequest, ServicesStartResult]("cmd.web-apps.v1.services.start", 1, "7cf00b95dfce6b556b4a3e0f57085dfaadd0f967966d88c8186d96e7944136bb", "cmd.web-apps.v1.services.start")}

// StopServices is the generated descriptor for cmd.web-apps.v1.services.stop revision 1.
var StopServices = Command[ServicesStopRequest, ServicesStopResult]{c: plugin.NewCommand[ServicesStopRequest, ServicesStopResult]("cmd.web-apps.v1.services.stop", 1, "68652738afc69adc8e4b579e8fdfa4ed9945d1b2a498c7d653bf492dc3d77ab1", "cmd.web-apps.v1.services.stop")}

// ReadServiceLogs is the generated descriptor for cmd.web-apps.v1.services.logs revision 1.
var ReadServiceLogs = Command[ServicesLogsRequest, ServicesLogsResult]{c: plugin.NewCommand[ServicesLogsRequest, ServicesLogsResult]("cmd.web-apps.v1.services.logs", 1, "d4a088b47debdf1486aa665df549245d830691098ddd0778b28c028ed7293e87", "cmd.web-apps.v1.services.logs")}

// ResolvePreview is the generated descriptor for cmd.web-apps.v1.preview.resolve revision 1.
var ResolvePreview = Command[PreviewResolveRequest, PreviewResolveResult]{c: plugin.NewCommand[PreviewResolveRequest, PreviewResolveResult]("cmd.web-apps.v1.preview.resolve", 1, "ba0bce9af43db6cb49dfdc01736d31608b49182576f038f03b161b86ef1e30f3", "cmd.web-apps.v1.preview.resolve")}

// NavigatePreview is the generated descriptor for cmd.web-apps.v1.preview.navigate revision 1.
var NavigatePreview = Command[PreviewNavigateRequest, PreviewNavigateResult]{c: plugin.NewCommand[PreviewNavigateRequest, PreviewNavigateResult]("cmd.web-apps.v1.preview.navigate", 1, "33b5e477355b14c25a510b4045fe944a61b73d0a49fb726f18f8ab1d3e5e7d9a", "cmd.web-apps.v1.preview.navigate")}

// OpenPreviewExternal is the generated descriptor for cmd.web-apps.v1.preview.open-external revision 1.
var OpenPreviewExternal = Command[PreviewOpenExternalRequest, PreviewOpenExternalResult]{c: plugin.NewCommand[PreviewOpenExternalRequest, PreviewOpenExternalResult]("cmd.web-apps.v1.preview.open-external", 1, "f3048549233bc4e939e673235ea8223c40ed5670f64c5ee0142bbe141ba536de", "cmd.web-apps.v1.preview.open-external")}

// Changed is the generated descriptor for event.web-apps.v1.changed revision 1.
var Changed = Event[RuntimeEvent]{e: plugin.NewEvent[RuntimeEvent]("event.web-apps.v1.changed", 1, "573d4b52aae84c92bc95aa7dc56a9ffbbb9cb8bbb85a6d73c523dd2ad2a0de47", "event.web-apps.v1.changed")}

// Events is the generated descriptor for stream.web-apps.v1.events revision 1.
var Events = Stream[RuntimeEvent]{s: plugin.NewStreamDescriptor[RuntimeEvent]("WEB_APPS_EVENTS", 1, "981e41df754f7f7977a22804eeb7a406a7db5f744659dd640d148fa637a55913", "event.web-apps.v1.changed")}
