// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -package=provideraccess -out <path>

package provideraccess

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	CredentialHandle |
		CredentialRequest |
		CredentialResult |
		EgressCancelRequest |
		EgressCancelResult |
		EgressFailure |
		EgressJob |
		EgressReadRequest |
		EgressReadResult |
		EgressRequest |
		EgressResult |
		EgressStartResult |
		RevokeRequest |
		RevokeResult
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "provideraccess: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "provideraccess: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// Credential is the generated descriptor for cmd.gateway.provider-access.v1.credential revision 1.
var Credential = Command[CredentialRequest, CredentialResult]{c: plugin.NewValidatedCommand[CredentialRequest, CredentialResult]("cmd.gateway.provider-access.v1.credential", 1, "b83fc191119f8402957d001dd1aa8bf331afabfce8c8adf82877b44d88c6bab8", "cmd.gateway.provider-access.v1.credential")}

// Revoke is the generated descriptor for cmd.gateway.provider-access.v1.revoke revision 1.
var Revoke = Command[RevokeRequest, RevokeResult]{c: plugin.NewValidatedCommand[RevokeRequest, RevokeResult]("cmd.gateway.provider-access.v1.revoke", 1, "1f0abb275fd8e1c5e7ba57d3b6655c777f164035591fff63608b2b5adedfb1ed", "cmd.gateway.provider-access.v1.revoke")}

// EgressStart is the generated descriptor for cmd.gateway.provider-access.v1.egress-start revision 1.
var EgressStart = Command[EgressRequest, EgressStartResult]{c: plugin.NewValidatedCommand[EgressRequest, EgressStartResult]("cmd.gateway.provider-access.v1.egress-start", 1, "4fa2b827fd638437a327cc81d0a124c946d140645f534c649b1fbf5666ff199a", "cmd.gateway.provider-access.v1.egress-start")}

// EgressRead is the generated descriptor for cmd.gateway.provider-access.v1.egress-read revision 1.
var EgressRead = Command[EgressReadRequest, EgressReadResult]{c: plugin.NewValidatedCommand[EgressReadRequest, EgressReadResult]("cmd.gateway.provider-access.v1.egress-read", 1, "19cfd1cd805efb5823d2bed40447a4b4e2762380d29b87f7cac9bfbd81d7a8bf", "cmd.gateway.provider-access.v1.egress-read")}

// EgressCancel is the generated descriptor for cmd.gateway.provider-access.v1.egress-cancel revision 1.
var EgressCancel = Command[EgressCancelRequest, EgressCancelResult]{c: plugin.NewValidatedCommand[EgressCancelRequest, EgressCancelResult]("cmd.gateway.provider-access.v1.egress-cancel", 1, "734dcb520a538e8a7abf9dec944bf18263c82975cd8cdf5559799b988f8a0cbf", "cmd.gateway.provider-access.v1.egress-cancel")}
