// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -out <path>

package messaging

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	ChangedEvent |
		Conversation |
		ConversationOpenRequest |
		ConversationOpenResult |
		DeliveryUpdateRequest |
		DeliveryUpdateResult |
		EndpointIdentity |
		EndpointRemoveRequest |
		EndpointRemoveResult |
		EndpointUpsertRequest |
		EndpointUpsertResult |
		Fault |
		IdempotencyRecord |
		InboxConversationSummary |
		InboxSummaryRequest |
		InboxSummaryResult |
		Message |
		MessageDelivery |
		MessageListRequest |
		MessageListResult |
		MessageReference |
		MessageSendRequest |
		MessageSendResult |
		MetadataEntry |
		OperationStatus |
		Receipt |
		ReceiptAckRequest |
		ReceiptAckResult
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "messaging: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "messaging: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// UpsertEndpoint is the generated descriptor for cmd.messaging.v1.endpoint.upsert revision 1.
var UpsertEndpoint = Command[EndpointUpsertRequest, EndpointUpsertResult]{c: plugin.NewCommand[EndpointUpsertRequest, EndpointUpsertResult]("cmd.messaging.v1.endpoint.upsert", 1, "8ef7e61e2ef6452431e6aa81f8fa08fb7f0401aa92d4f7570aefe7958f64ce61", "cmd.messaging.v1.endpoint.upsert")}

// RemoveEndpoint is the generated descriptor for cmd.messaging.v1.endpoint.remove revision 1.
var RemoveEndpoint = Command[EndpointRemoveRequest, EndpointRemoveResult]{c: plugin.NewCommand[EndpointRemoveRequest, EndpointRemoveResult]("cmd.messaging.v1.endpoint.remove", 1, "a0099030b38aec33073ebab7095bed8b860473ac467495ea1e5fcb72afa8516a", "cmd.messaging.v1.endpoint.remove")}

// OpenConversation is the generated descriptor for cmd.messaging.v1.conversation.open revision 1.
var OpenConversation = Command[ConversationOpenRequest, ConversationOpenResult]{c: plugin.NewCommand[ConversationOpenRequest, ConversationOpenResult]("cmd.messaging.v1.conversation.open", 1, "2435c8fb24dc2fc91a8dcc1e01a63909c6fd83f86e8812b600d49026aaa96556", "cmd.messaging.v1.conversation.open")}

// SendMessage is the generated descriptor for cmd.messaging.v1.message.send revision 1.
var SendMessage = Command[MessageSendRequest, MessageSendResult]{c: plugin.NewCommand[MessageSendRequest, MessageSendResult]("cmd.messaging.v1.message.send", 1, "dbba749407821a6aa5fb9b401c6597c2044e47cfdfdab8557c6e48e31af39de4", "cmd.messaging.v1.message.send")}

// ListMessages is the generated descriptor for cmd.messaging.v1.message.list revision 1.
var ListMessages = Command[MessageListRequest, MessageListResult]{c: plugin.NewCommand[MessageListRequest, MessageListResult]("cmd.messaging.v1.message.list", 1, "fa6f64b53d2120e515ceba2d1b45b3eccecdc38bfc36b10a9580754f1e53c626", "cmd.messaging.v1.message.list")}

// AckReceipt is the generated descriptor for cmd.messaging.v1.receipt.ack revision 1.
var AckReceipt = Command[ReceiptAckRequest, ReceiptAckResult]{c: plugin.NewCommand[ReceiptAckRequest, ReceiptAckResult]("cmd.messaging.v1.receipt.ack", 1, "77457b2d6b9033b5118b5e4123a9fe05ed9580e85e214e38b0153dccd02ed496", "cmd.messaging.v1.receipt.ack")}

// UpdateDelivery is the generated descriptor for cmd.messaging.v1.delivery.update revision 1.
var UpdateDelivery = Command[DeliveryUpdateRequest, DeliveryUpdateResult]{c: plugin.NewCommand[DeliveryUpdateRequest, DeliveryUpdateResult]("cmd.messaging.v1.delivery.update", 1, "42365b00e9c57e8a25041cf92760f94848b0fb369f1116f062499f26a2854efe", "cmd.messaging.v1.delivery.update")}

// GetInboxSummary is the generated descriptor for cmd.messaging.v1.inbox.summary revision 1.
var GetInboxSummary = Command[InboxSummaryRequest, InboxSummaryResult]{c: plugin.NewCommand[InboxSummaryRequest, InboxSummaryResult]("cmd.messaging.v1.inbox.summary", 1, "a1c53b1e3df90e7fe48695a39d3753bd071cbb195df6da99b91e6db18c3dbab2", "cmd.messaging.v1.inbox.summary")}

// Changed is the generated descriptor for event.messaging.v1.changed revision 1.
var Changed = Event[ChangedEvent]{e: plugin.NewEvent[ChangedEvent]("event.messaging.v1.changed", 1, "24b3130d757afbbd8a16a46b9d6cab08b850c3fc2204f6aba26e0c5cdc3a2bf5", "event.messaging.v1.changed")}
