// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/plugin-typescript -emit=go -out <path>

package plugin

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	ExtensionPoint |
		Family |
		FamilyMember |
		HostCapabilities |
		LauncherSpec |
		LifecycleOperation |
		Manifest |
		NavItem |
		PanelSpec |
		Permissions |
		PresentationBadge |
		PresentationGroup |
		PresentationItem |
		PresentationLease |
		PresentationRequest |
		PresentationResult |
		PresentationTerminal |
		Pricing |
		ProtocolRequirements |
		Provider |
		Publisher |
		Requirement |
		RuntimeSnapshot |
		RuntimeStatus |
		TerminalBindingContext |
		TmuxPresentationContext |
		UIContribution |
		When
}

// CmdTerminalPresentationProject is the generated descriptor for terminal.presentation.project.v1 revision 1.
var CmdTerminalPresentationProject = NewCommand[PresentationRequest, PresentationResult]("terminal.presentation.project.v1", 1, "bf4dbefbc9cd9832e1803f4c91e34802ab02a41ff793e9ae3ba9a3926294c0d7")
