// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/plugin-typescript -emit=go -out <path>

package plugin

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	Binding |
		ComponentAssignRequest |
		ComponentAssignResult |
		ComponentAssignment |
		ComponentAvailableRequest |
		ComponentAvailableResult |
		ComponentContributeRequest |
		ComponentContributeResult |
		ComponentExtension |
		ComponentFileTreeSnapshot |
		ComponentIdentity |
		ComponentPlacement |
		ComponentProjectToolsSnapshot |
		ComponentSessionListSnapshot |
		ComponentSessionTabSnapshot |
		ComponentStageSnapshot |
		ComponentTasksSnapshot |
		ComponentTerminalSnapshot |
		ComponentWorkspaceSnapshot |
		Config |
		ConfigField |
		ConfigSection |
		DesktopApplication |
		DesktopApplicationSession |
		DesktopApplicationWindow |
		DesktopApplicationsOpenRequest |
		DesktopApplicationsOpenResult |
		DesktopApplicationsQuitRequest |
		DesktopApplicationsQuitResult |
		DesktopApplicationsRefreshRequest |
		DesktopApplicationsRefreshResult |
		DesktopApplicationsRegisterRequest |
		DesktopApplicationsRegisterResult |
		DesktopApplicationsScanRequest |
		DesktopApplicationsScanResult |
		DesktopApplicationsScanV2Request |
		DesktopApplicationsScanV2Result |
		DesktopApplicationsStatusRequest |
		DesktopApplicationsStatusResult |
		DesktopApplicationsViewerTicketRequest |
		DesktopApplicationsViewerTicketResult |
		DesktopSessionStatus |
		DirectoryContextActionContribution |
		DirectoryContextActionEligibilityRequest |
		DirectoryContextActionEligibilityResult |
		DirectoryContextActionWizardContext |
		ExtensionPoint |
		Family |
		FamilyMember |
		HostCapabilities |
		LauncherSpec |
		LifecycleOperation |
		Manifest |
		NavItem |
		PanelSpec |
		Permissions |
		PresentationBadge |
		PresentationGroup |
		PresentationItem |
		PresentationLease |
		PresentationRequest |
		PresentationResult |
		PresentationTerminal |
		Pricing |
		ProjectDirectoryContext |
		ProjectViewContribution |
		ProtocolRequirements |
		Provider |
		Publisher |
		Requirement |
		RuntimeSnapshot |
		RuntimeStatus |
		TerminalBindingContext |
		TmuxAvailability |
		TmuxAvailabilityRequest |
		TmuxAvailabilityResult |
		TmuxPanesRequest |
		TmuxPanesResult |
		TmuxPresentationContext |
		TmuxSessionsRequest |
		TmuxSessionsResult |
		TmuxWindowsRequest |
		TmuxWindowsResult |
		UIContribution |
		When
}

// CmdTerminalPresentationProject is the generated descriptor for terminal.presentation.project.v1 revision 2.
var CmdTerminalPresentationProject = NewCommand[PresentationRequest, PresentationResult]("terminal.presentation.project.v1", 2, "3b8d09c15b513b8f7c7bd71dd8574c0f3c35fd029d8c99e549295845329ae1b0")

// CmdDesktopApplicationsStatus is the generated descriptor for cmd.desktop-applications.v1.status revision 1.
var CmdDesktopApplicationsStatus = NewCommand[DesktopApplicationsStatusRequest, DesktopApplicationsStatusResult]("cmd.desktop-applications.v1.status", 1, "a5377f746e1a8c185530e49d0c0c3edfdb67af4212772aca9884e3cd4c652eeb")

// CmdDesktopApplicationsScan is the generated descriptor for cmd.desktop-applications.v1.scan revision 1.
var CmdDesktopApplicationsScan = NewCommand[DesktopApplicationsScanRequest, DesktopApplicationsScanResult]("cmd.desktop-applications.v1.scan", 1, "6fddd6aaa432cb7d88056f74b8d826f965acf9825b0a2941773ec9412f301ca2")

// CmdDesktopApplicationsScanV2 is the generated descriptor for cmd.desktop-applications.v2.scan revision 2.
var CmdDesktopApplicationsScanV2 = NewCommand[DesktopApplicationsScanV2Request, DesktopApplicationsScanV2Result]("cmd.desktop-applications.v2.scan", 2, "669c04959cfbc69abde5337afa121524ed1c02a6a8aa4618b064133d4a28e5dd")

// CmdDesktopApplicationsRegister is the generated descriptor for cmd.desktop-applications.v1.register revision 1.
var CmdDesktopApplicationsRegister = NewCommand[DesktopApplicationsRegisterRequest, DesktopApplicationsRegisterResult]("cmd.desktop-applications.v1.register", 1, "5766883aaf37bbf1be7d4391a5b5a9613db1c910dcddd900ab86c242964f1c76")

// CmdDesktopApplicationsOpen is the generated descriptor for cmd.desktop-applications.v1.open revision 1.
var CmdDesktopApplicationsOpen = NewCommand[DesktopApplicationsOpenRequest, DesktopApplicationsOpenResult]("cmd.desktop-applications.v1.open", 1, "5baa7d4ddf71da7e93da5e2327c273d32176524239872b76e47a6c432772333e")

// CmdDesktopApplicationsRefresh is the generated descriptor for cmd.desktop-applications.v1.refresh revision 1.
var CmdDesktopApplicationsRefresh = NewCommand[DesktopApplicationsRefreshRequest, DesktopApplicationsRefreshResult]("cmd.desktop-applications.v1.refresh", 1, "ed0615f3b487e99d6e9c16fe1d1d2ebed74e4d6e22f5756238d20f001120909a")

// CmdDesktopApplicationsViewerTicket is the generated descriptor for cmd.desktop-applications.v1.viewer-ticket revision 1.
var CmdDesktopApplicationsViewerTicket = NewCommand[DesktopApplicationsViewerTicketRequest, DesktopApplicationsViewerTicketResult]("cmd.desktop-applications.v1.viewer-ticket", 1, "a19dc252c64ab47a3b997e610118a3d7a56c2cb5ea3aac077051f43e1a109bdc")

// CmdDesktopApplicationsQuit is the generated descriptor for cmd.desktop-applications.v1.quit revision 1.
var CmdDesktopApplicationsQuit = NewCommand[DesktopApplicationsQuitRequest, DesktopApplicationsQuitResult]("cmd.desktop-applications.v1.quit", 1, "7b40318af1df2da39cbcc59ed265ea9cd5ed9ff1c92a12029032a878b663d4cb")

// CmdTmuxAvailability is the generated descriptor for cmd.tmux.v1.availability revision 1.
var CmdTmuxAvailability = NewCommand[TmuxAvailabilityRequest, TmuxAvailabilityResult]("cmd.tmux.v1.availability", 1, "f8062f381ee51562eb4382bf8e933665bec761f44a9a3ee55920cbf9aabdefd2")

// CmdTmuxSessions is the generated descriptor for cmd.tmux.v1.sessions revision 1.
var CmdTmuxSessions = NewCommand[TmuxSessionsRequest, TmuxSessionsResult]("cmd.tmux.v1.sessions", 1, "744e1ebd0fd49cb0888975016a649d19aa7cc5b3dd64dd57ca7f45cdb309f28b")

// CmdTmuxWindows is the generated descriptor for cmd.tmux.v1.windows revision 1.
var CmdTmuxWindows = NewCommand[TmuxWindowsRequest, TmuxWindowsResult]("cmd.tmux.v1.windows", 1, "5ada9d5bd4e11b7c690ddd228f2ff9e5a572f0ab26a25253ceb634bb35557f6d")

// CmdTmuxPanes is the generated descriptor for cmd.tmux.v1.panes revision 1.
var CmdTmuxPanes = NewCommand[TmuxPanesRequest, TmuxPanesResult]("cmd.tmux.v1.panes", 1, "c31c3da0ba820fa740c2f613e6f4b0c65a1bdb21812072d424a48dc3b9e18dcc")
