// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -package=projecttasks -out <path>

package projecttasks

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	ActingContext |
		AgentWork |
		AgentWorkInput |
		Attachment |
		Binding |
		Capabilities |
		Capability |
		Change |
		ChangesRequest |
		ChangesResult |
		ClaimRequest |
		ClaimResult |
		Comment |
		CommentInput |
		Conflict |
		Criterion |
		DescribeRequest |
		DescribeResult |
		Evidence |
		FieldSchema |
		FieldValue |
		Filter |
		Grant |
		Invocation |
		ItemReceipt |
		Lease |
		Migration |
		MigrationEntity |
		MigrationRequest |
		MigrationResult |
		Mutation |
		NativeMapping |
		OfflineOperation |
		PageInfo |
		PageRequest |
		Person |
		PlanningResource |
		Problem |
		Project |
		ProviderChangesRequest |
		ProviderClaimRequest |
		ProviderDescribeRequest |
		ProviderMigrationRequest |
		ProviderQueryRequest |
		ProviderReadRequest |
		ProviderRecoverRequest |
		ProviderSchemaRequest |
		ProviderTransferRequest |
		ProviderWriteRequest |
		Query |
		QueryRequest |
		QueryResult |
		ReadRequest |
		ReadResult |
		Receipt |
		RecoverRequest |
		RecoverResult |
		RecoveryPolicy |
		Relation |
		RelativePosition |
		ResourceRef |
		RichBody |
		SchemaRequest |
		SchemaResult |
		Scope |
		Sort |
		Transfer |
		TransferRequest |
		TransferResult |
		Transport |
		WorkItem |
		WorkflowAction |
		Worklog |
		WorklogInput |
		WriteRequest |
		WriteResult
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "projecttasks: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "projecttasks: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// Describe is the generated descriptor for cmd.gateway.project-tasks.v1.describe revision 1.
var Describe = Command[DescribeRequest, DescribeResult]{c: plugin.NewValidatedCommand[DescribeRequest, DescribeResult]("cmd.gateway.project-tasks.v1.describe", 1, "946bb5fd4a342c05f4c3a49d55c17a785a1e77ff5b2593cf57f5fc76de2d6460", "cmd.gateway.project-tasks.v1.describe")}

// Changes is the generated descriptor for cmd.gateway.project-tasks.v1.changes revision 1.
var Changes = Command[ChangesRequest, ChangesResult]{c: plugin.NewValidatedCommand[ChangesRequest, ChangesResult]("cmd.gateway.project-tasks.v1.changes", 1, "30435e50fbeb4c612ac5edb11e712d7b35b200a4562ec1938a22da839db66d1d", "cmd.gateway.project-tasks.v1.changes")}

// Recover is the generated descriptor for cmd.gateway.project-tasks.v1.recover revision 1.
var Recover = Command[RecoverRequest, RecoverResult]{c: plugin.NewValidatedCommand[RecoverRequest, RecoverResult]("cmd.gateway.project-tasks.v1.recover", 1, "1e65528e3d73395601d01ad170cecad0c54b8c5299ece7b893507b983bdefdab", "cmd.gateway.project-tasks.v1.recover")}

// ManageTransfer is the generated descriptor for cmd.gateway.project-tasks.v1.transfer revision 1.
var ManageTransfer = Command[TransferRequest, TransferResult]{c: plugin.NewValidatedCommand[TransferRequest, TransferResult]("cmd.gateway.project-tasks.v1.transfer", 1, "6520e5bc3ee46884e84ae2f85b6a16dbfc0e7fa2790338a1b4e9d528f96373a6", "cmd.gateway.project-tasks.v1.transfer")}

// Migrate is the generated descriptor for cmd.gateway.project-tasks.v1.migration revision 1.
var Migrate = Command[MigrationRequest, MigrationResult]{c: plugin.NewValidatedCommand[MigrationRequest, MigrationResult]("cmd.gateway.project-tasks.v1.migration", 1, "84ae4e6e3482e3acb3e3c0bcc971f4792f462393f1aac60c8723a56a0c4523ae", "cmd.gateway.project-tasks.v1.migration")}

// Schema is the generated descriptor for cmd.gateway.project-tasks.v1.schema revision 1.
var Schema = Command[SchemaRequest, SchemaResult]{c: plugin.NewValidatedCommand[SchemaRequest, SchemaResult]("cmd.gateway.project-tasks.v1.schema", 1, "5df1a1a9e5994594e8d4a364828debc7b0d77240c15fad1e0c0a8d1c65764063", "cmd.gateway.project-tasks.v1.schema")}

// Search is the generated descriptor for cmd.gateway.project-tasks.v1.query revision 1.
var Search = Command[QueryRequest, QueryResult]{c: plugin.NewValidatedCommand[QueryRequest, QueryResult]("cmd.gateway.project-tasks.v1.query", 1, "6814ce375a74148e3f381978e19cfe2fa2aeb0a71f275a717bbaf4190c46bd12", "cmd.gateway.project-tasks.v1.query")}

// Read is the generated descriptor for cmd.gateway.project-tasks.v1.read revision 1.
var Read = Command[ReadRequest, ReadResult]{c: plugin.NewValidatedCommand[ReadRequest, ReadResult]("cmd.gateway.project-tasks.v1.read", 1, "e55595b4087b2e066893520576e9d0b32da2e4b5d6c2993daf9c54be017f2a47", "cmd.gateway.project-tasks.v1.read")}

// Write is the generated descriptor for cmd.gateway.project-tasks.v1.write revision 1.
var Write = Command[WriteRequest, WriteResult]{c: plugin.NewValidatedCommand[WriteRequest, WriteResult]("cmd.gateway.project-tasks.v1.write", 1, "9d5aaa2124495130ac466b63cacd71426fe46a270a475be59a074916923fb6ac", "cmd.gateway.project-tasks.v1.write")}

// Claim is the generated descriptor for cmd.gateway.project-tasks.v1.claim revision 1.
var Claim = Command[ClaimRequest, ClaimResult]{c: plugin.NewValidatedCommand[ClaimRequest, ClaimResult]("cmd.gateway.project-tasks.v1.claim", 1, "3fd40b2d9138cd59272d18769bee2b178bbc7856892760c0524f5a51adabf114", "cmd.gateway.project-tasks.v1.claim")}
