// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -package=sessioncontext -out <path>

package sessioncontext

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	ActionInput |
		ActionRequest |
		ActionResult |
		AllowedAction |
		Context |
		OpenRequest |
		OpenResult |
		RefreshRequest |
		RefreshResult
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "sessioncontext: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "sessioncontext: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// Open is the generated descriptor for cmd.session-context.v1.open revision 1.
var Open = Command[OpenRequest, OpenResult]{c: plugin.NewCommand[OpenRequest, OpenResult]("cmd.session-context.v1.open", 1, "c234e4674c2f0ef6baf0569c91ee0a890ba39c8d813eb43577499b10548d7c38", "cmd.session-context.v1.open")}

// Refresh is the generated descriptor for cmd.session-context.v1.refresh revision 1.
var Refresh = Command[RefreshRequest, RefreshResult]{c: plugin.NewCommand[RefreshRequest, RefreshResult]("cmd.session-context.v1.refresh", 1, "90df2715cb6657cec4d99d0f3bf297d9fb1b23767ec708bc8ddf8c13669322e5", "cmd.session-context.v1.refresh")}

// Action is the generated descriptor for cmd.session-context.v1.action revision 1.
var Action = Command[ActionRequest, ActionResult]{c: plugin.NewCommand[ActionRequest, ActionResult]("cmd.session-context.v1.action", 1, "c3276afd6e85e56af01a2cd02288bf32ff72a91dad925ced6d2287b0109ea62d", "cmd.session-context.v1.action")}
