// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface NavItem {
  id: string
  label: string
  icon?: string
  href: string
  order?: number
  kind?: string
  section?: NavReference
  parent?: NavReference
  childrenPoint?: string
  placement?: string
  newTab?: boolean
}

export interface NavReference {
  owner: string
  id: string
}

export interface NavigationDiagnostic {
  owner: string
  id: string
  code: string
}

export interface NavigationNode {
  owner: string
  item: NavItem
  parent?: NavReference
  section?: NavReference
}

export interface NavigationSnapshot {
  items: NavigationNode[] | null
  diagnostics: NavigationDiagnostic[] | null
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isNavItem(value: unknown): value is NavItem
export declare function isNavReference(value: unknown): value is NavReference
export declare function isNavigationDiagnostic(value: unknown): value is NavigationDiagnostic
export declare function isNavigationNode(value: unknown): value is NavigationNode
export declare function isNavigationSnapshot(value: unknown): value is NavigationSnapshot
