// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/plugin-typescript -emit=go -package=consumer -out <path>

package consumer

import (
	"context"
	"encoding/json"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	Ping |
		Pong
}

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ d plugin.Descriptor }

// Event names one event payload this package owns.
type Event[T Payload] struct{ d plugin.Descriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.d.Name() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.d.Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, h plugin.Host, c Command[Req, Resp], req Req) (Resp, error) {
	var resp Resp
	if err := plugin.Invoke(ctx, h, c.d, req, &resp); err != nil {
		var zero Resp
		return zero, err
	}
	return resp, nil
}

// Handle registers a typed handler for one of this package's commands. The
// schema check happens in the registrar before this decodes anything.
func Handle[Req, Resp Payload](r *plugin.Registrar, c Command[Req, Resp], fn func(context.Context, plugin.Caller, Req) (Resp, error)) {
	plugin.HandleRaw(r, c.d, func(ctx context.Context, caller plugin.Caller, raw json.RawMessage) (json.RawMessage, error) {
		var req Req
		if err := json.Unmarshal(raw, &req); err != nil {
			return nil, plugin.Fault{Code: plugin.FaultSchema, Op: c.d.Name(), Message: "request does not decode", Err: err}
		}
		resp, err := fn(ctx, caller, req)
		if err != nil {
			return nil, err
		}
		body, err := json.Marshal(resp)
		if err != nil {
			return nil, plugin.Fault{Code: plugin.FaultSchema, Op: c.d.Name(), Message: "response does not marshal", Err: err}
		}
		return body, nil
	})
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](h plugin.Host, e Event[T], v T) error { return plugin.Publish(h, e.d, v) }

// On subscribes to one of this package's typed events. On a host without
// StatusSubscriber, silence is indistinguishable from loss and periodic cursor
// reconciliation is mandatory.
func On[T Payload](h plugin.Host, e Event[T], fn func(T)) (plugin.Subscription, error) {
	if fn == nil {
		return nil, plugin.Fault{Code: plugin.FaultUnavailable, Op: e.d.Name(), Message: "nil handler"}
	}
	return plugin.Observe(h, e.d, func(raw json.RawMessage) {
		var v T
		if json.Unmarshal(raw, &v) != nil {
			return
		}
		fn(v)
	})
}

// PingCommand is the generated descriptor for cmd.consumer.v1.ping revision 1.
var PingCommand = Command[Ping, Pong]{d: plugin.NewDescriptor("cmd.consumer.v1.ping", 1, "4c91f7d50e211a9d2ed6fd8d0cfb2c17a3d9cd8cb9e71adfffa38c8e6cc2fcd3")}

// PongedEvent is the generated descriptor for event.consumer.v1.ponged revision 1.
var PongedEvent = Event[Pong]{d: plugin.NewDescriptor("event.consumer.v1.ponged", 1, "1ca85c792a5af2f31ca6281e09585e00e63b5f2adaeb2d591169de30a14c5543")}
