// Package consumer is a worked example of a package that owns its own payload
// types, plus the fixtures that prove the classification guarantee holds across
// a package boundary.
//
// It is what a real consumer — agent-messaging, say — looks like: DTOs here,
// and payload_gen.go generated by plugin-typescript carrying this package's own
// Payload union, its Command/Event types, its descriptors and its Call/Handle/
// On/Emit wrappers. Nothing in it is hand-written except these DTOs.
//
// It lives under cmd/ so that importing the SDK never pulls it in.
package consumer

// Ping and Pong are classified and exposed, so the generator admits them to the
// union and this package's Call accepts them.

type Ping struct {
	Note string `json:"note" bd:"public"`
	Seq  uint64 `json:"seq,string" bd:"public"`
}

type Pong struct {
	Note string `json:"note" bd:"public"`
	Echo Ping   `json:"echo" bd:"public"`
}

// Unclassified is what a consumer writes when they forget the tags and do not
// expose the type. It is absent from the generated union, so a call site naming
// it does not compile — see negative_test.go.
type Unclassified struct {
	Note string `json:"note"`
}

// Forged is the embedding-promotion attack ADR 0025 §6 rules out. Go promotes
// methods through embedding, so every marker-method seal — however it is spelled
// — is satisfied by this type, and APIKey would marshal unclassified. A union
// without ~ matches exactly the named types, and Forged is a distinct defined
// type, so it is not one of them.
type Forged struct {
	Ping
	APIKey string `json:"apiKey"`
}
