// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/plugin-typescript -emit=go -package=messaging -out <path>

package messaging

import (
	"context"
	"encoding/json"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	ChangedEvent |
		Conversation |
		ConversationOpenRequest |
		ConversationOpenResult |
		DeliveryUpdateRequest |
		DeliveryUpdateResult |
		EndpointIdentity |
		EndpointRemoveRequest |
		EndpointRemoveResult |
		EndpointUpsertRequest |
		EndpointUpsertResult |
		Fault |
		IdempotencyRecord |
		InboxConversationSummary |
		InboxSummaryRequest |
		InboxSummaryResult |
		Message |
		MessageDelivery |
		MessageListRequest |
		MessageListResult |
		MessageReference |
		MessageSendRequest |
		MessageSendResult |
		MetadataEntry |
		OperationStatus |
		Receipt |
		ReceiptAckRequest |
		ReceiptAckResult
}

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ d plugin.Descriptor }

// Event names one event payload this package owns.
type Event[T Payload] struct{ d plugin.Descriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.d.Name() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.d.Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, h plugin.Host, c Command[Req, Resp], req Req) (Resp, error) {
	var resp Resp
	if err := plugin.Invoke(ctx, h, c.d, req, &resp); err != nil {
		var zero Resp
		return zero, err
	}
	return resp, nil
}

// Handle registers a typed handler for one of this package's commands. The
// schema check happens in the registrar before this decodes anything.
func Handle[Req, Resp Payload](r *plugin.Registrar, c Command[Req, Resp], fn func(context.Context, plugin.Caller, Req) (Resp, error)) {
	if fn == nil {
		panic("messaging: Handle needs a handler")
	}
	plugin.HandleRaw(r, c.d, func(ctx context.Context, caller plugin.Caller, raw json.RawMessage) (json.RawMessage, error) {
		var req Req
		if err := json.Unmarshal(raw, &req); err != nil {
			return nil, plugin.Fault{Code: plugin.FaultSchema, Op: c.d.Name(), Message: "request does not decode", Err: err}
		}
		resp, err := fn(ctx, caller, req)
		if err != nil {
			return nil, err
		}
		body, err := json.Marshal(resp)
		if err != nil {
			return nil, plugin.Fault{Code: plugin.FaultSchema, Op: c.d.Name(), Message: "response does not marshal", Err: err}
		}
		return body, nil
	})
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](h plugin.Host, e Event[T], v T) error { return plugin.Publish(h, e.d, v) }

// On subscribes to one of this package's typed events. On a host without
// StatusSubscriber, silence is indistinguishable from loss and periodic cursor
// reconciliation is mandatory.
func On[T Payload](h plugin.Host, e Event[T], fn func(T)) (plugin.Subscription, error) {
	if fn == nil {
		return nil, plugin.Fault{Code: plugin.FaultUnavailable, Op: e.d.Name(), Message: "nil handler"}
	}
	return plugin.Observe(h, e.d, func(raw json.RawMessage) {
		var v T
		if json.Unmarshal(raw, &v) != nil {
			return
		}
		fn(v)
	})
}

// UpsertEndpoint is the generated descriptor for cmd.messaging.v1.endpoint.upsert revision 1.
var UpsertEndpoint = Command[EndpointUpsertRequest, EndpointUpsertResult]{d: plugin.NewDescriptor("cmd.messaging.v1.endpoint.upsert", 1, "5417e52a31fb7c85330e3904e077b597d4fc6becc377e6703e836aed96af4f46")}

// RemoveEndpoint is the generated descriptor for cmd.messaging.v1.endpoint.remove revision 1.
var RemoveEndpoint = Command[EndpointRemoveRequest, EndpointRemoveResult]{d: plugin.NewDescriptor("cmd.messaging.v1.endpoint.remove", 1, "23dcc2946ed0b5ebfdce8c49d40d08936e354316fe212fe36b9fc472c36c519f")}

// OpenConversation is the generated descriptor for cmd.messaging.v1.conversation.open revision 1.
var OpenConversation = Command[ConversationOpenRequest, ConversationOpenResult]{d: plugin.NewDescriptor("cmd.messaging.v1.conversation.open", 1, "e2a057abb4e3da355643232dd955c3cc0479525e61b86b4935d142b57fd0614c")}

// SendMessage is the generated descriptor for cmd.messaging.v1.message.send revision 1.
var SendMessage = Command[MessageSendRequest, MessageSendResult]{d: plugin.NewDescriptor("cmd.messaging.v1.message.send", 1, "3ba7b86d3ea71468beeb0c3707ac25d0029d30cc292fc79b58f9671a68a0030e")}

// ListMessages is the generated descriptor for cmd.messaging.v1.message.list revision 1.
var ListMessages = Command[MessageListRequest, MessageListResult]{d: plugin.NewDescriptor("cmd.messaging.v1.message.list", 1, "1d5405f976e928d210dde14e48a44d6b6bb1c4c8d60602cb5a6b62031e22c969")}

// AckReceipt is the generated descriptor for cmd.messaging.v1.receipt.ack revision 1.
var AckReceipt = Command[ReceiptAckRequest, ReceiptAckResult]{d: plugin.NewDescriptor("cmd.messaging.v1.receipt.ack", 1, "f69abb5188e12c2f6161f76edf31e7d748aac0e13ab027b80e4d6cd5b9206641")}

// UpdateDelivery is the generated descriptor for cmd.messaging.v1.delivery.update revision 1.
var UpdateDelivery = Command[DeliveryUpdateRequest, DeliveryUpdateResult]{d: plugin.NewDescriptor("cmd.messaging.v1.delivery.update", 1, "c5849b61d938212dd30359f4de6da4379a7fc2372ccba3b97f7300ba0188dcd8")}

// GetInboxSummary is the generated descriptor for cmd.messaging.v1.inbox.summary revision 1.
var GetInboxSummary = Command[InboxSummaryRequest, InboxSummaryResult]{d: plugin.NewDescriptor("cmd.messaging.v1.inbox.summary", 1, "d2d2fe607678ed1fae0af6146016dc461bdf93eda7e2a73bf42ec9d8a347a9c5")}

// Changed is the generated descriptor for event.messaging.v1.changed revision 1.
var Changed = Event[ChangedEvent]{d: plugin.NewDescriptor("event.messaging.v1.changed", 1, "6490e9913e2cdd41406a9f0024762c121a4ec52168fa660c6be1c5fd8c74d8db")}
