// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -package=projectknowledge -out <path>

package projectknowledge

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	Access |
		ActingContext |
		Attachment |
		Binding |
		Capabilities |
		Capability |
		Change |
		ChangesRequest |
		ChangesResult |
		Comment |
		CommentInput |
		Conflict |
		Content |
		DescribeRequest |
		DescribeResult |
		Export |
		FieldSchema |
		FieldValue |
		Filter |
		Grant |
		HierarchyMove |
		InlineTask |
		Invocation |
		ItemReceipt |
		Migration |
		MigrationEntity |
		MigrationRequest |
		MigrationResult |
		Mutation |
		OfflineOperation |
		PageInfo |
		PageRequest |
		Problem |
		ProviderChangesRequest |
		ProviderDescribeRequest |
		ProviderMigrationRequest |
		ProviderQueryRequest |
		ProviderReadRequest |
		ProviderRecoverRequest |
		ProviderSchemaRequest |
		ProviderTransferRequest |
		ProviderWriteRequest |
		Query |
		QueryRequest |
		QueryResult |
		Reaction |
		ReactionInput |
		ReadRequest |
		ReadResult |
		Receipt |
		RecoverRequest |
		RecoverResult |
		RecoveryPolicy |
		Relation |
		ResourceRef |
		RichBody |
		SchemaRequest |
		SchemaResult |
		Scope |
		Sort |
		Space |
		Transfer |
		TransferRequest |
		TransferResult |
		Transport |
		Version |
		VersionDiff |
		WriteRequest |
		WriteResult
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "projectknowledge: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "projectknowledge: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// Describe is the generated descriptor for cmd.gateway.project-knowledge.v1.describe revision 1.
var Describe = Command[DescribeRequest, DescribeResult]{c: plugin.NewValidatedCommand[DescribeRequest, DescribeResult]("cmd.gateway.project-knowledge.v1.describe", 1, "100d5540e650c9aa3f88499812407767fb7e03bb2382ffeb1b38adbc80a04594", "cmd.gateway.project-knowledge.v1.describe")}

// Changes is the generated descriptor for cmd.gateway.project-knowledge.v1.changes revision 1.
var Changes = Command[ChangesRequest, ChangesResult]{c: plugin.NewValidatedCommand[ChangesRequest, ChangesResult]("cmd.gateway.project-knowledge.v1.changes", 1, "085d53973a0b28bdc1bc3fd50aaaa4f5f16ab19e7e163643f9a789f39ade1e02", "cmd.gateway.project-knowledge.v1.changes")}

// Recover is the generated descriptor for cmd.gateway.project-knowledge.v1.recover revision 1.
var Recover = Command[RecoverRequest, RecoverResult]{c: plugin.NewValidatedCommand[RecoverRequest, RecoverResult]("cmd.gateway.project-knowledge.v1.recover", 1, "793b616dad6dc1f6fc0ace2e5d76505bc00c17808e3515be7c160710bb402bc7", "cmd.gateway.project-knowledge.v1.recover")}

// ManageTransfer is the generated descriptor for cmd.gateway.project-knowledge.v1.transfer revision 1.
var ManageTransfer = Command[TransferRequest, TransferResult]{c: plugin.NewValidatedCommand[TransferRequest, TransferResult]("cmd.gateway.project-knowledge.v1.transfer", 1, "a9a16a61fae4e22a838a2a4f984c34abda5f2b3924d355697fa06f6d4b9dd445", "cmd.gateway.project-knowledge.v1.transfer")}

// Migrate is the generated descriptor for cmd.gateway.project-knowledge.v1.migration revision 1.
var Migrate = Command[MigrationRequest, MigrationResult]{c: plugin.NewValidatedCommand[MigrationRequest, MigrationResult]("cmd.gateway.project-knowledge.v1.migration", 1, "b9e92538a53f3c88ba5029167ba060a7cfc91aedced8c8925cf113473b00b0ba", "cmd.gateway.project-knowledge.v1.migration")}

// Schema is the generated descriptor for cmd.gateway.project-knowledge.v1.schema revision 1.
var Schema = Command[SchemaRequest, SchemaResult]{c: plugin.NewValidatedCommand[SchemaRequest, SchemaResult]("cmd.gateway.project-knowledge.v1.schema", 1, "c853db6dc62c71191721ffb5b10005c2c97079e6d37dfb932ac4e4bb39086463", "cmd.gateway.project-knowledge.v1.schema")}

// Search is the generated descriptor for cmd.gateway.project-knowledge.v1.query revision 1.
var Search = Command[QueryRequest, QueryResult]{c: plugin.NewValidatedCommand[QueryRequest, QueryResult]("cmd.gateway.project-knowledge.v1.query", 1, "d6b0b69acc1d972f29b5148191b92ca2df1453afa8dd18128be5ae74f8b986fd", "cmd.gateway.project-knowledge.v1.query")}

// Read is the generated descriptor for cmd.gateway.project-knowledge.v1.read revision 1.
var Read = Command[ReadRequest, ReadResult]{c: plugin.NewValidatedCommand[ReadRequest, ReadResult]("cmd.gateway.project-knowledge.v1.read", 1, "357f8700da898cd402a88cd628d450c3bcd13ac3d15875e703066a2021a1423f", "cmd.gateway.project-knowledge.v1.read")}

// Write is the generated descriptor for cmd.gateway.project-knowledge.v1.write revision 1.
var Write = Command[WriteRequest, WriteResult]{c: plugin.NewValidatedCommand[WriteRequest, WriteResult]("cmd.gateway.project-knowledge.v1.write", 1, "d846133ce187a99bf6d6bcc711fe376a062f92fea5b6aff0fdff8b0088360dd4", "cmd.gateway.project-knowledge.v1.write")}
