// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: go run ./cmd/contractgen -emit=go -package=codingsessions -out <path>

package codingsessions

import (
	"context"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

// Payload is the closed set of this package's classified payload types. A
// union type set rather than a marker method: Go promotes methods through
// embedding, so every marker is satisfied by a type that embeds a member and
// adds an unclassified field. Without ~ this matches exactly the named types.
//
// Membership is published API surface. Adding a type is free; removing one
// breaks every consumer, so it needs a changelog entry.
type Payload interface {
	Approval |
		ApprovalOption |
		ApproveRequest |
		BoundWorkUnit |
		Capabilities |
		CatalogRequest |
		CatalogResult |
		ChangedEvent |
		ConfigChoice |
		ConfigOption |
		ConfigUpdate |
		ConfigValue |
		CreateRequest |
		EventsRequest |
		EventsResult |
		Failure |
		ListRequest |
		ListResult |
		Message |
		Model |
		NewTaskRequest |
		OpenSurfaceRequest |
		OpenSurfaceResult |
		Overrides |
		Preferences |
		PreferencesRequest |
		PreviewJob |
		PreviewJobRequest |
		PreviewJobResult |
		PreviewRequest |
		PreviewResult |
		PromptRequest |
		PromptResult |
		Provider |
		Route |
		Session |
		SessionEvent |
		SessionRequest |
		SessionResult |
		StateUpdate |
		StopRequest |
		TextInput |
		ToolUpdate |
		WorkUnitReference
}

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "codingsessions: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "codingsessions: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}

// Catalog is the generated descriptor for cmd.gateway.coding-sessions.v1.catalog revision 1.
var Catalog = Command[CatalogRequest, CatalogResult]{c: plugin.NewValidatedCommand[CatalogRequest, CatalogResult]("cmd.gateway.coding-sessions.v1.catalog", 1, "472e7e6147aba591f004c331e296e86cf6ae72254010fa503f3c868d76f3dc02", "cmd.gateway.coding-sessions.v1.catalog")}

// Preview is the generated descriptor for cmd.gateway.coding-sessions.v1.preview revision 1.
var Preview = Command[PreviewRequest, PreviewJobResult]{c: plugin.NewValidatedCommand[PreviewRequest, PreviewJobResult]("cmd.gateway.coding-sessions.v1.preview", 1, "473a9b018e2d58a0414164ebdd951be0e5700231cf3030f2515eec44e3056c77", "cmd.gateway.coding-sessions.v1.preview")}

// PreviewRead is the generated descriptor for cmd.gateway.coding-sessions.v1.preview-read revision 1.
var PreviewRead = Command[PreviewJobRequest, PreviewJobResult]{c: plugin.NewValidatedCommand[PreviewJobRequest, PreviewJobResult]("cmd.gateway.coding-sessions.v1.preview-read", 1, "12c17d2d6c15af21bea886d67adb953a7c4c3536f6f31fb333faed68f3e260a7", "cmd.gateway.coding-sessions.v1.preview-read")}

// PreviewCancel is the generated descriptor for cmd.gateway.coding-sessions.v1.preview-cancel revision 1.
var PreviewCancel = Command[PreviewJobRequest, PreviewJobResult]{c: plugin.NewValidatedCommand[PreviewJobRequest, PreviewJobResult]("cmd.gateway.coding-sessions.v1.preview-cancel", 1, "ee510f00f8073f13d27e9d3745d4bd6ea62d742e61ba0408c1994e1878b8a90f", "cmd.gateway.coding-sessions.v1.preview-cancel")}

// Create is the generated descriptor for cmd.gateway.coding-sessions.v1.create revision 1.
var Create = Command[CreateRequest, SessionResult]{c: plugin.NewValidatedCommand[CreateRequest, SessionResult]("cmd.gateway.coding-sessions.v1.create", 1, "420ae406d3faba10ed9e624755ba3933681c8609acbe7506dccaa2886822e1f1", "cmd.gateway.coding-sessions.v1.create")}

// Read is the generated descriptor for cmd.gateway.coding-sessions.v1.read revision 1.
var Read = Command[SessionRequest, SessionResult]{c: plugin.NewValidatedCommand[SessionRequest, SessionResult]("cmd.gateway.coding-sessions.v1.read", 1, "8832001706d99c4f6443e991dfcd75be37fbe6f65716f22ae2d40192f0cf307d", "cmd.gateway.coding-sessions.v1.read")}

// Recover is the generated descriptor for cmd.gateway.coding-sessions.v1.recover revision 1.
var Recover = Command[SessionRequest, SessionResult]{c: plugin.NewValidatedCommand[SessionRequest, SessionResult]("cmd.gateway.coding-sessions.v1.recover", 1, "c1fa7990685425fcb66fd94a350322304d11705158f03b4bd634c608741df2b6", "cmd.gateway.coding-sessions.v1.recover")}

// List is the generated descriptor for cmd.gateway.coding-sessions.v1.list revision 1.
var List = Command[ListRequest, ListResult]{c: plugin.NewValidatedCommand[ListRequest, ListResult]("cmd.gateway.coding-sessions.v1.list", 1, "9165cb8062ae5a6fb6e1d670b2a3143fa2cf7a50f69a8ded3266ab8bfcdb5eb6", "cmd.gateway.coding-sessions.v1.list")}

// Prompt is the generated descriptor for cmd.gateway.coding-sessions.v1.prompt revision 1.
var Prompt = Command[PromptRequest, PromptResult]{c: plugin.NewValidatedCommand[PromptRequest, PromptResult]("cmd.gateway.coding-sessions.v1.prompt", 1, "f5c2150744580a05f197a123940f371583bbe6a9404dabe5546ecf68c62a68c4", "cmd.gateway.coding-sessions.v1.prompt")}

// Stop is the generated descriptor for cmd.gateway.coding-sessions.v1.stop revision 1.
var Stop = Command[StopRequest, SessionResult]{c: plugin.NewValidatedCommand[StopRequest, SessionResult]("cmd.gateway.coding-sessions.v1.stop", 1, "80ac3931ba9da5bffbe72911e5cd33fdfd06bb385ad55f7f6e98936bd9facf4d", "cmd.gateway.coding-sessions.v1.stop")}

// End is the generated descriptor for cmd.gateway.coding-sessions.v1.end revision 1.
var End = Command[SessionRequest, SessionResult]{c: plugin.NewValidatedCommand[SessionRequest, SessionResult]("cmd.gateway.coding-sessions.v1.end", 1, "1c4f5db1962e7fc92d01d9e7cbecb34611658d1f011ca6f139deac221d1dc168", "cmd.gateway.coding-sessions.v1.end")}

// Complete is the generated descriptor for cmd.gateway.coding-sessions.v1.complete revision 1.
var Complete = Command[SessionRequest, SessionResult]{c: plugin.NewValidatedCommand[SessionRequest, SessionResult]("cmd.gateway.coding-sessions.v1.complete", 1, "c0f3eb4178636fdc5d650d06e6881f8c0dba20d0ab9324e871ff555c70875cbd", "cmd.gateway.coding-sessions.v1.complete")}

// NewTask is the generated descriptor for cmd.gateway.coding-sessions.v1.new-task revision 1.
var NewTask = Command[NewTaskRequest, SessionResult]{c: plugin.NewValidatedCommand[NewTaskRequest, SessionResult]("cmd.gateway.coding-sessions.v1.new-task", 1, "1a1d6c732d1a9a1e7c1eca54d817c4685276d925b88c92b99f9c35a66332b5f3", "cmd.gateway.coding-sessions.v1.new-task")}

// UpdatePreferences is the generated descriptor for cmd.gateway.coding-sessions.v1.preferences revision 1.
var UpdatePreferences = Command[PreferencesRequest, SessionResult]{c: plugin.NewValidatedCommand[PreferencesRequest, SessionResult]("cmd.gateway.coding-sessions.v1.preferences", 1, "a19936e0aac5d9fac802e0ef7cf19f76572a81b99b500396fde7a0eb8e56d98e", "cmd.gateway.coding-sessions.v1.preferences")}

// Approve is the generated descriptor for cmd.gateway.coding-sessions.v1.approve revision 1.
var Approve = Command[ApproveRequest, SessionResult]{c: plugin.NewValidatedCommand[ApproveRequest, SessionResult]("cmd.gateway.coding-sessions.v1.approve", 1, "19ef74374fb2281d43d3fd3905adfb785428f7cccb5ee58a77941c6a1e42725e", "cmd.gateway.coding-sessions.v1.approve")}

// Events is the generated descriptor for cmd.gateway.coding-sessions.v1.events revision 1.
var Events = Command[EventsRequest, EventsResult]{c: plugin.NewValidatedCommand[EventsRequest, EventsResult]("cmd.gateway.coding-sessions.v1.events", 1, "140dc34f5f348d6ef84b17d97124797fb8a6f11f5a6a6b016ab83fb22e16fd0e", "cmd.gateway.coding-sessions.v1.events")}

// OpenSurface is the generated descriptor for cmd.gateway.coding-sessions.v1.open-surface revision 1.
var OpenSurface = Command[OpenSurfaceRequest, OpenSurfaceResult]{c: plugin.NewValidatedCommand[OpenSurfaceRequest, OpenSurfaceResult]("cmd.gateway.coding-sessions.v1.open-surface", 1, "c58ff311051c0969d594628d825c3144ebffc264d1669d9975afd5977393478d", "cmd.gateway.coding-sessions.v1.open-surface")}

// Changed is the generated descriptor for event.gateway.coding-sessions.v1.changed revision 1.
var Changed = Event[ChangedEvent]{e: plugin.NewEvent[ChangedEvent]("event.gateway.coding-sessions.v1.changed", 1, "6ba741e12f65cfbd3db73b053c55241b236fe87602888426ac34c90857aec42c", "event.gateway.coding-sessions.v1.changed")}
