// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface Access {
  effectiveOperations: string[] | null
  grants?: Grant[]
  inheritedFrom?: ResourceRef
  publicLinkEnabled: boolean
  revision: string
}

export interface ActingContext {
  actorId: string
  connectionId: string
  delegatedBy?: string
  originalActorId?: string
  executionMode: string
}

export interface Attachment {
  ref: ResourceRef
  name: string
  mediaType: string
  size: string
  checksum: string
  revision: string
}

export interface Binding {
  scope: Scope
  slot: string
  providerId: string
  resource: ResourceRef
  state: string
}

export interface Capabilities {
  revision: string
  operations: Capability[] | null
  transport: Transport
  recovery: RecoveryPolicy
}

export interface Capability {
  operation: string
  revision: number
  resourceKinds?: string[]
  formats?: string[]
  supported: boolean
  authorized: boolean
  reason?: string
  concurrency: string
  offline: string
  maxBatchItems?: number
}

export interface Change {
  resource: ResourceRef
  revision: string
  actorId: string
  origin: string
  operationId?: string
  kind: string
  occurredAt: string
}

export interface ChangesRequest {
  scope: Scope
  page: PageRequest
}

export interface ChangesResult {
  changes: Change[] | null
  page: PageInfo
  problem?: Problem
}

export interface Comment {
  ref: ResourceRef
  body: RichBody
  authorId: string
  createdAt: string
  revision: string
  parent?: ResourceRef
  anchor?: FieldValue
  resolved: boolean
}

export interface CommentInput {
  body: RichBody
  parent?: ResourceRef
  anchor?: FieldValue
}

export interface Conflict {
  baseRevision: string
  remoteRevision: string
  localBody?: RichBody
  remoteBody?: RichBody
  localFields?: FieldValue[]
  remoteFields?: FieldValue[]
  payloadRef?: string
  resolutionOptions: string[] | null
}

export interface Content {
  ref: ResourceRef
  space: ResourceRef
  kind: string
  title: string
  body?: RichBody
  state: string
  revision: string
  versionId: string
  parent?: ResourceRef
  ancestors?: ResourceRef[]
  depth: number
  orderKey?: string
  labels?: string[]
  properties?: FieldValue[]
  template?: ResourceRef
  authorId: string
  createdAt: string
  updatedAt: string
}

export interface DescribeRequest {
  scope: Scope
}

export interface DescribeResult {
  capabilities: Capabilities
  binding?: Binding
  problem?: Problem
}

export interface Export {
  mode: string
  format: string
  includeVersions: boolean
  includeAttachments: boolean
  includePermissions: boolean
  transfer?: Transfer
  lossless: boolean
}

export interface FieldSchema {
  name: string
  type: string
  required: boolean
  editable: boolean
  multiple: boolean
  allowedValues?: FieldValue[]
}

export interface FieldValue {
  name: string
  type: string
  json: string
}

export interface Filter {
  field: string
  operator: string
  values?: FieldValue[]
}

export interface Grant {
  principalId: string
  principalKind: string
  operation: string
  effect: string
  inherited: boolean
}

export interface HierarchyMove {
  parent: ResourceRef
  before?: ResourceRef
  after?: ResourceRef
  includeDescendants: boolean
}

export interface InlineTask {
  id: string
  text: string
  state: string
  assigneeId?: string
  managedTask?: ResourceRef
}

export interface Invocation {
  id: string
  scope: Scope
  actor: ActingContext
  expiresAt: string
}

export interface ItemReceipt {
  itemId: string
  state: string
  resource?: ResourceRef
  revision?: string
  problem?: Problem
}

export interface Migration {
  id: string
  source: Scope
  destination: Scope
  state: string
  snapshotRevision: string
  cursor?: string
  entities?: MigrationEntity[]
  inventoryChecksum: string
  lossless: boolean
  writesPaused: boolean
}

export interface MigrationEntity {
  sourceRecordId: string
  source: ResourceRef
  destination?: ResourceRef
  revision: string
  checksum: string
  record?: Transfer
  problems?: Problem[]
}

export interface MigrationRequest {
  scope: Scope
  mutation: Mutation
  action: string
  migration: Migration
  page: PageRequest
}

export interface MigrationResult {
  migration?: Migration
  receipt: Receipt
  page: PageInfo
}

export interface Mutation {
  operationId: string
  expectedRevision?: string
  sourceBindingRevision: string
  dependsOn?: string[]
  origin: string
  createdAt: string
}

export interface OfflineOperation {
  scope: Scope
  actor: ActingContext
  mutation: Mutation
  operation: string
  payloadRef: string
  payloadChecksum: string
  receipt: Receipt
  persistedAt: string
  sessionId?: string
  nativeId?: string
}

export interface PageInfo {
  nextCursor?: string
  total: string
  totalKind: string
  consistency: string
  observedAt: string
}

export interface PageRequest {
  cursor?: string
  limit: number
}

export interface Problem {
  code: string
  message: string
  field?: string
  retry: string
  retryAfterSeconds?: number
}

export interface ProviderChangesRequest {
  invocation: Invocation
  request: ChangesRequest
}

export interface ProviderDescribeRequest {
  invocation: Invocation
  request: DescribeRequest
}

export interface ProviderMigrationRequest {
  invocation: Invocation
  request: MigrationRequest
}

export interface ProviderQueryRequest {
  invocation: Invocation
  request: QueryRequest
}

export interface ProviderReadRequest {
  invocation: Invocation
  request: ReadRequest
}

export interface ProviderRecoverRequest {
  invocation: Invocation
  request: RecoverRequest
}

export interface ProviderSchemaRequest {
  invocation: Invocation
  request: SchemaRequest
}

export interface ProviderTransferRequest {
  invocation: Invocation
  request: TransferRequest
}

export interface ProviderWriteRequest {
  invocation: Invocation
  request: WriteRequest
}

export interface Query {
  text?: string
  filters?: Filter[]
  sort?: Sort[]
  savedView?: ResourceRef
  nativeLanguage?: string
  nativeQuery?: string
  page: PageRequest
}

export interface QueryRequest {
  scope: Scope
  kind: string
  container?: ResourceRef
  query: Query
}

export interface QueryResult {
  spaces?: Space[]
  contents?: Content[]
  page: PageInfo
  problem?: Problem
}

export interface Reaction {
  id: string
  actorId: string
  value: string
}

export interface ReactionInput {
  value: string
}

export interface ReadRequest {
  scope: Scope
  resource: ResourceRef
  aspect: string
  versionId?: string
  compareVersionId?: string
  page: PageRequest
}

export interface ReadResult {
  space?: Space
  content?: Content
  versions?: Version[]
  diff?: VersionDiff
  relations?: Relation[]
  comments?: Comment[]
  reactions?: Reaction[]
  watcherIds?: string[]
  inlineTasks?: InlineTask[]
  attachments?: Attachment[]
  access?: Access
  history?: Change[]
  page: PageInfo
  problem?: Problem
}

export interface Receipt {
  operationId: string
  state: string
  remoteAccepted: boolean
  resource?: ResourceRef
  revision?: string
  items?: ItemReceipt[]
  problem?: Problem
  recoveryToken?: string
  observedAt: string
  conflict?: Conflict
}

export interface RecoverRequest {
  scope: Scope
  operationId: string
  recoveryToken?: string
}

export interface RecoverResult {
  receipt: Receipt
  offline?: OfflineOperation
}

export interface RecoveryPolicy {
  idempotency: string
  deduplicationSeconds: string
  receiptRetentionSeconds: string
  lookupByOperationId: boolean
  reconcileBeforeReplay: boolean
}

export interface Relation {
  kind: string
  source: ResourceRef
  target: ResourceRef
  type: string
}

export interface ResourceRef {
  providerId: string
  installationId: string
  kind: string
  id: string
  key?: string
  url?: string
}

export interface RichBody {
  format: string
  version: string
  source: string
  plainText?: string
  rendered?: string
  lossy: boolean
}

export interface SchemaRequest {
  scope: Scope
  resource?: ResourceRef
  operation: string
  contentKind: string
}

export interface SchemaResult {
  fields: FieldSchema[] | null
  kinds: string[] | null
  formats: string[] | null
  states: string[] | null
  problem?: Problem
}

export interface Scope {
  projectId: string
  environmentId: string
  tenantId: string
  bindingId: string
  bindingRevision: string
  providerGeneration: string
  capabilityRevision: string
}

export interface Sort {
  field: string
  direction: string
}

export interface Space {
  ref: ResourceRef
  name: string
  description?: RichBody
  revision: string
  fields?: FieldValue[]
}

export interface Transfer {
  id: string
  resource: ResourceRef
  direction: string
  method: string
  uri: string
  expiresAt: string
  size: string
  mediaType: string
  checksum: string
  provenance: string
  verified: boolean
}

export interface TransferRequest {
  scope: Scope
  mutation: Mutation
  resource: ResourceRef
  action: string
  transferId?: string
  size: string
  mediaType: string
  checksum: string
}

export interface TransferResult {
  transfer?: Transfer
  receipt: Receipt
}

export interface Transport {
  kind: string
  protocolVersion?: string
  catalogRevision: string
  discovery: string
}

export interface Version {
  id: string
  resource: ResourceRef
  revision: string
  authorId: string
  createdAt: string
  message?: string
  body?: RichBody
}

export interface VersionDiff {
  fromId: string
  toId: string
  format: string
  source: string
  lossy: boolean
}

export interface WriteRequest {
  scope: Scope
  mutation: Mutation
  action: string
  resource?: ResourceRef
  title?: string
  body?: RichBody
  contentKind?: string
  fields?: FieldValue[]
  clear?: string[]
  versionId?: string
  move?: HierarchyMove
  comment?: CommentInput
  reaction?: ReactionInput
  inlineTask?: InlineTask
  labels?: string[]
  template?: ResourceRef
  grants?: Grant[]
  state?: string
  principalId?: string
  export?: Export
}

export interface WriteResult {
  receipt: Receipt
  export?: Export
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isAccess(value: unknown): value is Access
export declare function isActingContext(value: unknown): value is ActingContext
export declare function isAttachment(value: unknown): value is Attachment
export declare function isBinding(value: unknown): value is Binding
export declare function isCapabilities(value: unknown): value is Capabilities
export declare function isCapability(value: unknown): value is Capability
export declare function isChange(value: unknown): value is Change
export declare function isChangesRequest(value: unknown): value is ChangesRequest
export declare function isChangesResult(value: unknown): value is ChangesResult
export declare function isComment(value: unknown): value is Comment
export declare function isCommentInput(value: unknown): value is CommentInput
export declare function isConflict(value: unknown): value is Conflict
export declare function isContent(value: unknown): value is Content
export declare function isDescribeRequest(value: unknown): value is DescribeRequest
export declare function isDescribeResult(value: unknown): value is DescribeResult
export declare function isExport(value: unknown): value is Export
export declare function isFieldSchema(value: unknown): value is FieldSchema
export declare function isFieldValue(value: unknown): value is FieldValue
export declare function isFilter(value: unknown): value is Filter
export declare function isGrant(value: unknown): value is Grant
export declare function isHierarchyMove(value: unknown): value is HierarchyMove
export declare function isInlineTask(value: unknown): value is InlineTask
export declare function isInvocation(value: unknown): value is Invocation
export declare function isItemReceipt(value: unknown): value is ItemReceipt
export declare function isMigration(value: unknown): value is Migration
export declare function isMigrationEntity(value: unknown): value is MigrationEntity
export declare function isMigrationRequest(value: unknown): value is MigrationRequest
export declare function isMigrationResult(value: unknown): value is MigrationResult
export declare function isMutation(value: unknown): value is Mutation
export declare function isOfflineOperation(value: unknown): value is OfflineOperation
export declare function isPageInfo(value: unknown): value is PageInfo
export declare function isPageRequest(value: unknown): value is PageRequest
export declare function isProblem(value: unknown): value is Problem
export declare function isProviderChangesRequest(value: unknown): value is ProviderChangesRequest
export declare function isProviderDescribeRequest(value: unknown): value is ProviderDescribeRequest
export declare function isProviderMigrationRequest(value: unknown): value is ProviderMigrationRequest
export declare function isProviderQueryRequest(value: unknown): value is ProviderQueryRequest
export declare function isProviderReadRequest(value: unknown): value is ProviderReadRequest
export declare function isProviderRecoverRequest(value: unknown): value is ProviderRecoverRequest
export declare function isProviderSchemaRequest(value: unknown): value is ProviderSchemaRequest
export declare function isProviderTransferRequest(value: unknown): value is ProviderTransferRequest
export declare function isProviderWriteRequest(value: unknown): value is ProviderWriteRequest
export declare function isQuery(value: unknown): value is Query
export declare function isQueryRequest(value: unknown): value is QueryRequest
export declare function isQueryResult(value: unknown): value is QueryResult
export declare function isReaction(value: unknown): value is Reaction
export declare function isReactionInput(value: unknown): value is ReactionInput
export declare function isReadRequest(value: unknown): value is ReadRequest
export declare function isReadResult(value: unknown): value is ReadResult
export declare function isReceipt(value: unknown): value is Receipt
export declare function isRecoverRequest(value: unknown): value is RecoverRequest
export declare function isRecoverResult(value: unknown): value is RecoverResult
export declare function isRecoveryPolicy(value: unknown): value is RecoveryPolicy
export declare function isRelation(value: unknown): value is Relation
export declare function isResourceRef(value: unknown): value is ResourceRef
export declare function isRichBody(value: unknown): value is RichBody
export declare function isSchemaRequest(value: unknown): value is SchemaRequest
export declare function isSchemaResult(value: unknown): value is SchemaResult
export declare function isScope(value: unknown): value is Scope
export declare function isSort(value: unknown): value is Sort
export declare function isSpace(value: unknown): value is Space
export declare function isTransfer(value: unknown): value is Transfer
export declare function isTransferRequest(value: unknown): value is TransferRequest
export declare function isTransferResult(value: unknown): value is TransferResult
export declare function isTransport(value: unknown): value is Transport
export declare function isVersion(value: unknown): value is Version
export declare function isVersionDiff(value: unknown): value is VersionDiff
export declare function isWriteRequest(value: unknown): value is WriteRequest
export declare function isWriteResult(value: unknown): value is WriteResult
