// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  Changes: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.changes","kind":"command","rev":1,"schema":"085d53973a0b28bdc1bc3fd50aaaa4f5f16ab19e7e163643f9a789f39ade1e02","subject":"cmd.gateway.project-knowledge.v1.changes"}),
  Describe: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.describe","kind":"command","rev":1,"schema":"100d5540e650c9aa3f88499812407767fb7e03bb2382ffeb1b38adbc80a04594","subject":"cmd.gateway.project-knowledge.v1.describe"}),
  ManageTransfer: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.transfer","kind":"command","rev":1,"schema":"a9a16a61fae4e22a838a2a4f984c34abda5f2b3924d355697fa06f6d4b9dd445","subject":"cmd.gateway.project-knowledge.v1.transfer"}),
  Migrate: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.migration","kind":"command","rev":1,"schema":"b9e92538a53f3c88ba5029167ba060a7cfc91aedced8c8925cf113473b00b0ba","subject":"cmd.gateway.project-knowledge.v1.migration"}),
  Read: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.read","kind":"command","rev":1,"schema":"357f8700da898cd402a88cd628d450c3bcd13ac3d15875e703066a2021a1423f","subject":"cmd.gateway.project-knowledge.v1.read"}),
  Recover: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.recover","kind":"command","rev":1,"schema":"793b616dad6dc1f6fc0ace2e5d76505bc00c17808e3515be7c160710bb402bc7","subject":"cmd.gateway.project-knowledge.v1.recover"}),
  Schema: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.schema","kind":"command","rev":1,"schema":"c853db6dc62c71191721ffb5b10005c2c97079e6d37dfb932ac4e4bb39086463","subject":"cmd.gateway.project-knowledge.v1.schema"}),
  Search: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.query","kind":"command","rev":1,"schema":"d6b0b69acc1d972f29b5148191b92ca2df1453afa8dd18128be5ae74f8b986fd","subject":"cmd.gateway.project-knowledge.v1.query"}),
  Write: Object.freeze({"name":"cmd.gateway.project-knowledge.v1.write","kind":"command","rev":1,"schema":"d846133ce187a99bf6d6bcc711fe376a062f92fea5b6aff0fdff8b0088360dd4","subject":"cmd.gateway.project-knowledge.v1.write"}),
})
