package main

import (
	"bytes"
	"fmt"
	"go/format"
	"reflect"
	"strings"
)

const generatedHeader = "// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT."

// tsType mirrors the browser's view of a Go field type. buildModels has already
// rejected every kind that lands in the default branch.
func tsType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Pointer:
		return tsType(t.Elem())
	case reflect.Slice:
		return tsType(t.Elem()) + "[]"
	case reflect.Struct:
		return t.Name()
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int32, reflect.Int64, reflect.Uint32, reflect.Uint64:
		return "number"
	default:
		return "unknown"
	}
}

// dtsNullable is the emitted contract: a nil slice or pointer marshals as null
// unless it is omitted, and the readonly subgraph validates its arrays as
// present, so they are never null there.
func dtsNullable(m *model, f field) bool {
	return !f.optional && (f.list() || f.typ.Kind() == reflect.Pointer) && !m.readonly
}

func emitDTS(ms *modelSet) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader + "\n\n")
	for _, name := range ms.names {
		if name == "TerminalBindingContext" {
			b.WriteString("export type TerminalBindingContext =\n  | { readonly kind: 'none'; readonly tmux?: never }\n  | { readonly kind: 'tmux'; readonly tmux: TmuxPresentationContext }\n\n")
			continue
		}
		m := ms.byName[name]
		fmt.Fprintf(&b, "export interface %s {\n", name)
		for _, f := range m.fields {
			kind, optional := tsType(f.typ), ""
			if f.optional {
				optional = "?"
			}
			if f.asString {
				kind = "string"
			}
			if m.readonly && f.list() {
				kind = "readonly " + kind
			}
			if dtsNullable(m, f) {
				kind += " | null"
			}
			if name == "PresentationItem" && f.goName == "Freshness" {
				kind = "'fresh' | 'stale' | 'unknown'"
			}
			prefix := ""
			if m.readonly {
				prefix = "readonly "
			}
			fmt.Fprintf(&b, "  %s%s%s: %s\n", prefix, f.jsonName, optional, kind)
		}
		b.WriteString("}\n\n")
	}
	return append(bytes.TrimRight(b.Bytes(), "\n"), '\n')
}

// emitGo writes a package's payload_gen.go. The union is a type set without ~,
// so it matches exactly the named types — there is no marker method to forge
// and no embedding promotion that satisfies it (ADR 0025 §6).
//
// For plugin the file carries the union and the descriptors; the typed
// wrappers are hand-written there because they are the host-exposed contract.
// For every other package it carries the union, that package's own Command and
// Event types over plugin.Descriptor, its descriptors, and its own Call, Handle,
// Emit and On. A consumer hand-writes none of it, and plugin never imports back.
func emitGo(t target, ms *modelSet) ([]byte, error) {
	digest, err := hashes(ms, t.ops)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString(generatedHeader + "\n")
	fmt.Fprintf(&b, "// Regenerate: go run ./cmd/plugin-typescript -emit=go%s -out <path>\n\n", pkgFlag(t))
	fmt.Fprintf(&b, "package %s\n\n", t.pkg)
	if t.pkg != "plugin" {
		b.WriteString("import (\n\t\"context\"\n\t\"encoding/json\"\n\n\t\"github.com/ByteDeskAI/bytedesk-sdk-dependencies/plugin\"\n)\n\n")
	}
	b.WriteString("// Payload is the closed set of this package's classified payload types. A\n")
	b.WriteString("// union type set rather than a marker method: Go promotes methods through\n")
	b.WriteString("// embedding, so every marker is satisfied by a type that embeds a member and\n")
	b.WriteString("// adds an unclassified field. Without ~ this matches exactly the named types.\n")
	b.WriteString("//\n")
	b.WriteString("// Membership is published API surface. Adding a type is free; removing one\n")
	b.WriteString("// breaks every consumer, so it needs a changelog entry.\n")
	b.WriteString("type Payload interface {\n")
	for i, name := range ms.union() {
		if i > 0 {
			b.WriteString(" |\n")
		}
		b.WriteString("\t" + name)
	}
	b.WriteString("\n}\n")
	if t.pkg != "plugin" {
		b.WriteString(consumerWrappers)
	}
	for _, op := range t.ops {
		fmt.Fprintf(&b, "\n// %s is the generated descriptor for %s revision %d.\n", op.goVar, op.name, op.rev)
		switch {
		case t.pkg == "plugin" && op.kind == kindEvent:
			fmt.Fprintf(&b, "var %s = NewEvent[%s](%q, %d, %q)\n", op.goVar, op.req.Name(), op.name, op.rev, digest[op.goVar])
		case t.pkg == "plugin":
			fmt.Fprintf(&b, "var %s = NewCommand[%s, %s](%q, %d, %q)\n", op.goVar, op.req.Name(), op.resp.Name(), op.name, op.rev, digest[op.goVar])
		case op.kind == kindEvent:
			fmt.Fprintf(&b, "var %s = Event[%s]{d: plugin.NewDescriptor(%q, %d, %q)}\n", op.goVar, op.req.Name(), op.name, op.rev, digest[op.goVar])
		default:
			fmt.Fprintf(&b, "var %s = Command[%s, %s]{d: plugin.NewDescriptor(%q, %d, %q)}\n", op.goVar, op.req.Name(), op.resp.Name(), op.name, op.rev, digest[op.goVar])
		}
	}
	return format.Source(b.Bytes())
}

func pkgFlag(t target) string {
	if t.pkg == "plugin" {
		return ""
	}
	return " -package=" + t.pkg
}

// consumerWrappers is the typed API a non-plugin package gets. It is generated
// rather than exported from plugin because Go cannot write a function generic
// over "some union": Call has to be constrained by THIS package's Payload, so
// an unclassified type fails to compile at the call site here, not only in
// plugin. plugin.Invoke and friends are the mechanism underneath.
const consumerWrappers = `

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ d plugin.Descriptor }

// Event names one event payload this package owns.
type Event[T Payload] struct{ d plugin.Descriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.d.Name() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.d.Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, h plugin.Host, c Command[Req, Resp], req Req) (Resp, error) {
	var resp Resp
	if err := plugin.Invoke(ctx, h, c.d, req, &resp); err != nil {
		var zero Resp
		return zero, err
	}
	return resp, nil
}

// Handle registers a typed handler for one of this package's commands. The
// schema check happens in the registrar before this decodes anything.
func Handle[Req, Resp Payload](r *plugin.Registrar, c Command[Req, Resp], fn func(context.Context, plugin.Caller, Req) (Resp, error)) {
	plugin.HandleRaw(r, c.d, func(ctx context.Context, caller plugin.Caller, raw json.RawMessage) (json.RawMessage, error) {
		var req Req
		if err := json.Unmarshal(raw, &req); err != nil {
			return nil, plugin.Fault{Code: plugin.FaultSchema, Op: c.d.Name(), Message: "request does not decode", Err: err}
		}
		resp, err := fn(ctx, caller, req)
		if err != nil {
			return nil, err
		}
		body, err := json.Marshal(resp)
		if err != nil {
			return nil, plugin.Fault{Code: plugin.FaultSchema, Op: c.d.Name(), Message: "response does not marshal", Err: err}
		}
		return body, nil
	})
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](h plugin.Host, e Event[T], v T) error { return plugin.Publish(h, e.d, v) }

// On subscribes to one of this package's typed events. On a host without
// StatusSubscriber, silence is indistinguishable from loss and periodic cursor
// reconciliation is mandatory.
func On[T Payload](h plugin.Host, e Event[T], fn func(T)) (plugin.Subscription, error) {
	if fn == nil {
		return nil, plugin.Fault{Code: plugin.FaultUnavailable, Op: e.d.Name(), Message: "nil handler"}
	}
	return plugin.Observe(h, e.d, func(raw json.RawMessage) {
		var v T
		if json.Unmarshal(raw, &v) != nil {
			return
		}
		fn(v)
	})
}
`

// emitJS writes the runtime validators the browser realm needs, because
// TypeScript types are erased and untrusted iframes reach that boundary. These
// are shape checks only: a security invariant a structural validator cannot
// derive — RuntimeSnapshot's available => installed && generation && enabled —
// stays hand-written in the SDK's ui/index.js (ADR 0025 §9).
func emitJS(ms *modelSet) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader + "\n\n")
	b.WriteString("const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)\n")
	b.WriteString("const decimal = /^-?(0|[1-9][0-9]*)$/\n")
	b.WriteString("const str = (v) => typeof v === 'string'\n")
	b.WriteString("const bool = (v) => typeof v === 'boolean'\n")
	b.WriteString("const num = (v) => typeof v === 'number' && Number.isFinite(v)\n")
	b.WriteString("const dec = (v) => str(v) && decimal.test(v)\n")
	b.WriteString("const list = (v, of) => Array.isArray(v) && v.every(of)\n\n")
	for _, name := range ms.names {
		if name == "TerminalBindingContext" {
			b.WriteString("export function isTerminalBindingContext(value) {\n")
			b.WriteString("  if (!record(value)) return false\n")
			b.WriteString("  if (value.kind === 'none') return value.tmux === undefined || value.tmux === null\n")
			b.WriteString("  if (value.kind === 'tmux') return isTmuxPresentationContext(value.tmux)\n")
			b.WriteString("  return false\n}\n\n")
			continue
		}
		m := ms.byName[name]
		fmt.Fprintf(&b, "export function is%s(value) {\n", name)
		b.WriteString("  if (!record(value)) return false\n")
		for _, f := range m.fields {
			fmt.Fprintf(&b, "  if (!(%s)) return false\n", jsCheck(m, f))
		}
		b.WriteString("  return true\n}\n\n")
	}
	return append(bytes.TrimRight(b.Bytes(), "\n"), '\n')
}

func jsCheck(m *model, f field) string {
	ref := "value." + f.jsonName
	pred := "str"
	switch {
	case f.elem != nil:
		pred = "is" + f.elem.Name()
	case strings.HasSuffix(f.wire, ".string"):
		pred = "dec"
	case f.wire == wireBool:
		pred = "bool"
	case f.wire == wireInt32, f.wire == wireUint32:
		pred = "num"
	}
	check := pred + "(" + ref + ")"
	if f.list() {
		check = "list(" + ref + ", " + pred + ")"
	}
	if m.name == "PresentationItem" && f.goName == "Freshness" {
		check = "['fresh', 'stale', 'unknown'].includes(" + ref + ")"
	}
	if dtsNullable(m, f) {
		check = ref + " === null || " + check
	}
	if f.optional {
		check = ref + " === undefined || " + check
	}
	return check
}
