// Command plugin-typescript emits the browser's types from the canonical Go
// JSON model. It uses only the standard library and never requires npm/network.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/plugin"
)

func declarations() []byte {
	models := map[string]reflect.Type{}
	var visit func(reflect.Type)
	visit = func(t reflect.Type) {
		if t.Kind() == reflect.Pointer || t.Kind() == reflect.Slice {
			visit(t.Elem())
			return
		}
		if t.Kind() != reflect.Struct {
			return
		}
		if _, found := models[t.Name()]; found {
			return
		}
		models[t.Name()] = t
		for i := 0; i < t.NumField(); i++ {
			visit(t.Field(i).Type)
		}
	}
	for _, model := range []any{plugin.Manifest{}, plugin.RuntimeSnapshot{}, plugin.HostCapabilities{}, plugin.ProtocolRequirements{}, plugin.LifecycleOperation{}, plugin.PresentationRequest{}, plugin.PresentationResult{}} {
		visit(reflect.TypeOf(model))
	}
	var fieldType func(reflect.Type) string
	fieldType = func(t reflect.Type) string {
		switch t.Kind() {
		case reflect.Pointer:
			return fieldType(t.Elem())
		case reflect.Slice:
			return fieldType(t.Elem()) + "[]"
		case reflect.Struct:
			return t.Name()
		case reflect.String:
			return "string"
		case reflect.Bool:
			return "boolean"
		case reflect.Int, reflect.Int32, reflect.Int64, reflect.Uint32, reflect.Uint64:
			return "number"
		default:
			panic("unsupported contract type: " + t.String())
		}
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by plugin-typescript from SDK Go JSON contracts. DO NOT EDIT.\n\n")
	names := make([]string, 0, len(models))
	for name := range models {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if name == "TerminalBindingContext" {
			b.WriteString("export type TerminalBindingContext =\n  | { readonly kind: 'none'; readonly tmux?: never }\n  | { readonly kind: 'tmux'; readonly tmux: TmuxPresentationContext }\n\n")
			continue
		}
		fmt.Fprintf(&b, "export interface %s {\n", name)
		t := models[name]
		presentation := strings.HasPrefix(name, "Presentation") || name == "TmuxPresentationContext"
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			parts := strings.Split(f.Tag.Get("json"), ",")
			if parts[0] == "-" || !f.IsExported() {
				continue
			}
			key, optional, kind := parts[0], "", fieldType(f.Type)
			if key == "" {
				key = f.Name
			}
			for _, opt := range parts[1:] {
				if opt == "omitempty" || opt == "omitzero" {
					optional = "?"
				}
				if opt == "string" {
					kind = "string"
				}
			}
			if presentation && f.Type.Kind() == reflect.Slice {
				kind = "readonly " + kind
			}
			if optional == "" && (f.Type.Kind() == reflect.Slice || f.Type.Kind() == reflect.Pointer) && !presentation {
				kind += " | null"
			}
			if name == "PresentationItem" && f.Name == "Freshness" {
				kind = "'fresh' | 'stale' | 'unknown'"
			}
			prefix := ""
			if presentation {
				prefix = "readonly "
			}
			fmt.Fprintf(&b, "  %s%s%s: %s\n", prefix, key, optional, kind)
		}
		b.WriteString("}\n\n")
	}
	return append(bytes.TrimRight(b.Bytes(), "\n"), '\n')
}

func main() {
	out := flag.String("out", "-", "output file, or - for stdout")
	flag.Parse()
	data := declarations()
	var err error
	if *out == "-" {
		_, err = os.Stdout.Write(data)
	} else {
		err = os.WriteFile(*out, data, 0644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
