package main

import (
	"bytes"
	"fmt"
	"go/format"
	"reflect"
	"strings"
)

const generatedHeader = "// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT."

// tsType mirrors the browser's view of a Go field type. buildModels has already
// rejected every kind that lands in the default branch.
func tsType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Pointer:
		return tsType(t.Elem())
	case reflect.Slice:
		return tsType(t.Elem()) + "[]"
	case reflect.Struct:
		return t.Name()
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int32, reflect.Int64, reflect.Uint32, reflect.Uint64:
		return "number"
	default:
		return "unknown"
	}
}

// dtsNullable is the emitted contract: a nil slice or pointer marshals as null
// unless it is omitted, and the readonly subgraph validates its arrays as
// present, so they are never null there.
func dtsNullable(m *model, f field) bool {
	return !f.optional && (f.list() || f.typ.Kind() == reflect.Pointer) && !m.readonly
}

func emitDTS(ms *modelSet) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader + "\n\n")
	for _, name := range ms.names {
		if name == "TerminalBindingContext" {
			b.WriteString("export type TerminalBindingContext =\n  | { readonly kind: 'none'; readonly tmux?: never }\n  | { readonly kind: 'tmux'; readonly tmux: TmuxPresentationContext }\n\n")
			continue
		}
		m := ms.byName[name]
		fmt.Fprintf(&b, "export interface %s {\n", name)
		for _, f := range m.fields {
			kind, optional := tsType(f.typ), ""
			if f.optional {
				optional = "?"
			}
			if f.asString {
				kind = "string"
			}
			if m.readonly && f.list() {
				kind = "readonly " + kind
			}
			if dtsNullable(m, f) {
				kind += " | null"
			}
			if name == "PresentationItem" && f.goName == "Freshness" {
				kind = "'fresh' | 'stale' | 'unknown'"
			}
			prefix := ""
			if m.readonly {
				prefix = "readonly "
			}
			fmt.Fprintf(&b, "  %s%s%s: %s\n", prefix, f.jsonName, optional, kind)
		}
		b.WriteString("}\n\n")
	}
	// The guards emitJS writes, declared so tsc sees the same module surface the
	// paired .js exports. Without these an `import { isManifest }` is a TS2305
	// against a symbol that resolves perfectly at runtime. They narrow, so a
	// guard is usable in control flow rather than merely present.
	b.WriteString("// Runtime shape guards. The paired JS module exports one per declaration\n")
	b.WriteString("// above; they check structure only, not the host's security invariants.\n")
	for _, name := range ms.names {
		fmt.Fprintf(&b, "export declare function is%s(value: unknown): value is %s\n", name, name)
	}
	return append(bytes.TrimRight(b.Bytes(), "\n"), '\n')
}

// emitGo writes a package's payload_gen.go. The union is a type set without ~,
// so it matches exactly the named types — there is no marker method to forge
// and no embedding promotion that satisfies it (ADR 0025 §6).
//
// For plugin the file carries the union and the descriptors; the typed
// wrappers are hand-written there because they are the host-exposed contract.
// For every other package it carries the union, that package's own Command and
// Event types over plugin.Descriptor, its descriptors, and its own Call, Handle,
// Emit and On. A consumer hand-writes none of it, and plugin never imports back.
func emitGo(t target, ms *modelSet) ([]byte, error) {
	digest, err := hashes(ms, t.ops)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString(generatedHeader + "\n")
	fmt.Fprintf(&b, "// Regenerate: go run ./cmd/contractgen -emit=go%s -out <path>\n\n", pkgFlag(t))
	fmt.Fprintf(&b, "package %s\n\n", t.pkg)
	if t.pkg != "plugin" {
		b.WriteString("import (\n\t\"context\"\n\n\t\"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/bus\"\n\t\"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin\"\n)\n\n")
	}
	b.WriteString("// Payload is the closed set of this package's classified payload types. A\n")
	b.WriteString("// union type set rather than a marker method: Go promotes methods through\n")
	b.WriteString("// embedding, so every marker is satisfied by a type that embeds a member and\n")
	b.WriteString("// adds an unclassified field. Without ~ this matches exactly the named types.\n")
	b.WriteString("//\n")
	b.WriteString("// Membership is published API surface. Adding a type is free; removing one\n")
	b.WriteString("// breaks every consumer, so it needs a changelog entry.\n")
	b.WriteString("type Payload interface {\n")
	for i, name := range ms.union() {
		if i > 0 {
			b.WriteString(" |\n")
		}
		b.WriteString("\t" + name)
	}
	b.WriteString("\n}\n")
	if t.pkg != "plugin" {
		b.WriteString(strings.ReplaceAll(consumerWrappers, "{{PACKAGE}}", t.pkg))
	}
	for _, op := range t.ops {
		fmt.Fprintf(&b, "\n// %s is the generated descriptor for %s revision %d.\n", op.goVar, op.name, op.rev)
		b.WriteString(descriptorVar(op, digest[op.goVar]))
	}
	return format.Source(b.Bytes())
}

func pkgFlag(t target) string {
	if t.pkg == defaultTarget {
		return ""
	}
	return " -package=" + t.pkg
}

// descriptorVar renders one generated descriptor. Every kind goes through a
// constructor rather than a struct literal, because the descriptor's fields are
// unexported: a call site cannot hand-assemble one and therefore cannot type an
// operation name at all. That stops drift; it is not a security boundary, and
// the constructors have to be exported because generated code lives in another
// package.
func descriptorVar(op operation, hash string) string {
	switch op.kind {
	case kindEvent:
		return fmt.Sprintf("var %s = Event[%s]{e: plugin.NewEvent[%s](%q, %d, %q, %q)}\n",
			op.goVar, op.req.Name(), op.req.Name(), op.name, op.rev, hash, op.subject)
	case kindStream:
		return fmt.Sprintf("var %s = Stream[%s]{s: plugin.NewStreamDescriptor[%s](%q, %d, %q, %q)}\n",
			op.goVar, op.req.Name(), op.req.Name(), op.stream, op.rev, hash, op.subjects[0])
	case kindBucket:
		return fmt.Sprintf("var %s = Bucket[%s]{b: plugin.NewBucketDescriptor[%s](%q, %d, %q)}\n",
			op.goVar, op.req.Name(), op.req.Name(), op.bucket, op.rev, hash)
	case kindService:
		return fmt.Sprintf("var %s = Service{s: plugin.NewServiceDescriptor(%q, %d, %q, %q)}\n",
			op.goVar, op.name, op.rev, hash, op.endpoints[0].subject)
	default:
		return fmt.Sprintf("var %s = Command[%s, %s]{c: plugin.NewCommand[%s, %s](%q, %d, %q, %q)}\n",
			op.goVar, op.req.Name(), op.resp.Name(), op.req.Name(), op.resp.Name(), op.name, op.rev, hash, op.subject)
	}
}

// consumerWrappers is the typed API a non-plugin package gets. It is generated
// rather than exported from plugin because Go cannot write a function generic
// over "some union": Call has to be constrained by THIS package's Payload, so
// an unclassified type fails to compile at the call site here, not only in
// plugin. plugin.Invoke and friends are the mechanism underneath.
const consumerWrappers = `

// The typed API a non-plugin package gets.
//
// It is GENERATED rather than exported from plugin, and the reason survives
// into v2 unchanged: Go cannot write a function generic over "some union", so
// Call has to be constrained by THIS package's Payload if an unclassified type
// is to fail to compile at the call site here rather than only inside plugin.
//
// plugin's own generics are deliberately [Req, Resp any] — they are the
// mechanism, and a mechanism that insisted on one package's union could not be
// shared. The closed union lives here, at the author-facing edge, which is
// where it does its work.

// Command names one request/response operation this package owns.
type Command[Req, Resp Payload] struct{ c plugin.Command[Req, Resp] }

// Event names one event payload this package owns.
type Event[T Payload] struct{ e plugin.Event[T] }

// Stream names one durable subject this package owns.
type Stream[T Payload] struct{ s plugin.StreamDescriptor[T] }

// Bucket names one KV bucket this package owns.
type Bucket[T Payload] struct{ b plugin.BucketDescriptor[T] }

// Service names one service this package owns.
type Service struct{ s plugin.ServiceDescriptor }

// Name reports the operation name, for registry keys and diagnostics.
func (c Command[Req, Resp]) Name() string { return c.c.Descriptor().Name() }

// Descriptor reports the generated operation identity. A host that serves this
// public contract uses it to register and echo the exact schema revision;
// callers still cannot construct a descriptor because Command retains c.
func (c Command[Req, Resp]) Descriptor() plugin.Descriptor { return c.c.Descriptor() }

// Name reports the event name, for registry keys and diagnostics.
func (e Event[T]) Name() string { return e.e.Descriptor().Name() }

// Name reports the stream name.
func (s Stream[T]) Name() string { return s.s.Descriptor().Name() }

// Name reports the bucket name.
func (b Bucket[T]) Name() string { return b.b.Descriptor().Name() }

// Name reports the service name.
func (s Service) Name() string { return s.s.Descriptor().Name() }

// Call invokes one of this package's typed commands.
func Call[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], req Req) (Resp, error) {
	return plugin.Call[Req, Resp](ctx, b, c.c, req)
}

// Serve mounts a handler for one of this package's commands. The schema check
// happens before the request is decoded, so a payload from another contract
// revision is never unmarshalled into a type it does not fit.
func Serve[Req, Resp Payload](ctx context.Context, b bus.Bus, c Command[Req, Resp], fn func(context.Context, Req, bus.Caller) (Resp, error)) (bus.Service, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: c.Name(), Message: "{{PACKAGE}}: Serve needs a handler"}
	}
	return plugin.Serve[Req, Resp](ctx, b, c.c, fn)
}

// Emit publishes one of this package's typed events.
func Emit[T Payload](ctx context.Context, b bus.Bus, e Event[T], v T) error {
	return plugin.Emit[T](ctx, b, e.e, v)
}

// On subscribes to one of this package's typed events.
func On[T Payload](ctx context.Context, b bus.Bus, e Event[T], fn func(context.Context, T, bus.Caller)) (bus.Subscription, error) {
	if fn == nil {
		return nil, bus.Fault{Code: bus.FaultUnavailable, Op: e.Name(), Message: "{{PACKAGE}}: On needs a handler"}
	}
	return plugin.On[T](ctx, b, e.e, fn)
}

// OpenStream returns the typed durable view of one of this package's streams.
func OpenStream[T Payload](b bus.Bus, s Stream[T]) plugin.TypedStream[T] {
	return plugin.Stream[T](b, s.s)
}

// OpenBucket opens one of this package's KV buckets.
func OpenBucket[T Payload](ctx context.Context, b bus.Bus, d Bucket[T]) (plugin.TypedBucket[T], error) {
	return plugin.OpenBucket[T](ctx, b, d.b)
}
`

// emitJS writes the runtime validators the browser realm needs, because
// TypeScript types are erased and untrusted iframes reach that boundary. These
// are shape checks only: a security invariant a structural validator cannot
// derive — RuntimeSnapshot's available => installed && generation && enabled —
// stays hand-written in the SDK's ui/index.js (ADR 0025 §9).
func emitJS(ms *modelSet) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader + "\n\n")
	b.WriteString("const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)\n")
	b.WriteString("const decimal = /^-?(0|[1-9][0-9]*)$/\n")
	b.WriteString("const str = (v) => typeof v === 'string'\n")
	b.WriteString("const bool = (v) => typeof v === 'boolean'\n")
	b.WriteString("const num = (v) => typeof v === 'number' && Number.isFinite(v)\n")
	b.WriteString("const dec = (v) => str(v) && decimal.test(v)\n")
	b.WriteString("const list = (v, of) => Array.isArray(v) && v.every(of)\n\n")
	for _, name := range ms.names {
		if name == "TerminalBindingContext" {
			b.WriteString("export function isTerminalBindingContext(value) {\n")
			b.WriteString("  if (!record(value)) return false\n")
			b.WriteString("  if (value.kind === 'none') return value.tmux === undefined || value.tmux === null\n")
			b.WriteString("  if (value.kind === 'tmux') return isTmuxPresentationContext(value.tmux)\n")
			b.WriteString("  return false\n}\n\n")
			continue
		}
		m := ms.byName[name]
		fmt.Fprintf(&b, "export function is%s(value) {\n", name)
		b.WriteString("  if (!record(value)) return false\n")
		for _, f := range m.fields {
			fmt.Fprintf(&b, "  if (!(%s)) return false\n", jsCheck(m, f))
		}
		b.WriteString("  return true\n}\n\n")
	}
	return append(bytes.TrimRight(b.Bytes(), "\n"), '\n')
}

func jsCheck(m *model, f field) string {
	ref := "value." + f.jsonName
	pred := "str"
	switch {
	case f.elem != nil:
		pred = "is" + f.elem.Name()
	case strings.HasSuffix(f.wire, ".string"):
		pred = "dec"
	case f.wire == wireBool:
		pred = "bool"
	case f.wire == wireInt32, f.wire == wireUint32:
		pred = "num"
	}
	check := pred + "(" + ref + ")"
	if f.list() {
		check = "list(" + ref + ", " + pred + ")"
	}
	if m.name == "PresentationItem" && f.goName == "Freshness" {
		check = "['fresh', 'stale', 'unknown'].includes(" + ref + ")"
	}
	if dtsNullable(m, f) {
		check = ref + " === null || " + check
	}
	if f.optional {
		check = ref + " === undefined || " + check
	}
	return check
}
