// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface FieldError {
  field: string
  message: string
}

export interface OwnerReadRequest {
  sectionId: string
}

export interface OwnerReadResult {
  sectionId: string
  valuesJson: string
  configuredSecrets: string[] | null
}

export interface ValidateRequest {
  sectionId: string
  valuesJson: string
  configuredSecrets: string[] | null
}

export interface ValidateResult {
  valid: boolean
  errors: FieldError[] | null
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isFieldError(value: unknown): value is FieldError
export declare function isOwnerReadRequest(value: unknown): value is OwnerReadRequest
export declare function isOwnerReadResult(value: unknown): value is OwnerReadResult
export declare function isValidateRequest(value: unknown): value is ValidateRequest
export declare function isValidateResult(value: unknown): value is ValidateResult
