// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  OwnerRead: Object.freeze({"name":"cmd.gateway.settings.v1.read-owner","kind":"command","rev":1,"schema":"17381d9a607e08abe6552a597571aa61282e2eeae52c7a66e10c92144382c047","subject":"cmd.gateway.settings.v1.read-owner"}),
})
