// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isFieldError(value) {
  if (!record(value)) return false
  if (!(str(value.field))) return false
  if (!(str(value.message))) return false
  return true
}

export function isOwnerReadRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sectionId))) return false
  return true
}

export function isOwnerReadResult(value) {
  if (!record(value)) return false
  if (!(str(value.sectionId))) return false
  if (!(str(value.valuesJson))) return false
  if (!(value.configuredSecrets === null || list(value.configuredSecrets, str))) return false
  return true
}

export function isValidateRequest(value) {
  if (!record(value)) return false
  if (!(str(value.sectionId))) return false
  if (!(str(value.valuesJson))) return false
  if (!(value.configuredSecrets === null || list(value.configuredSecrets, str))) return false
  return true
}

export function isValidateResult(value) {
  if (!record(value)) return false
  if (!(bool(value.valid))) return false
  if (!(value.errors === null || list(value.errors, isFieldError))) return false
  return true
}
