// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface AppendRequest {
  invocationId?: string
  handleId: string
  offset: string
  data: string
}

export interface AppendResult {
  nextOffset: string
}

export interface CommitRequest {
  invocationId?: string
  handleId: string
}

export interface CommitResult {
  handle: Handle
}

export interface CreateRequest {
  invocationId?: string
  providerId: string
  purpose: string
  size: string
  sha256: string
  ttlSeconds?: number
}

export interface CreateResult {
  handle: Handle
}

export interface Handle {
  id: string
  providerId: string
  providerGeneration: string
  purpose: string
  size: string
  sha256: string
  expiresAt: string
  state: string
}

export interface ReadRequest {
  invocationId?: string
  handleId: string
  offset: string
  limit: number
}

export interface ReadResult {
  data: string
  nextOffset: string
  eof: boolean
}

export interface RevokeRequest {
  invocationId?: string
  handleId: string
}

export interface RevokeResult {
  revoked: boolean
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isAppendRequest(value: unknown): value is AppendRequest
export declare function isAppendResult(value: unknown): value is AppendResult
export declare function isCommitRequest(value: unknown): value is CommitRequest
export declare function isCommitResult(value: unknown): value is CommitResult
export declare function isCreateRequest(value: unknown): value is CreateRequest
export declare function isCreateResult(value: unknown): value is CreateResult
export declare function isHandle(value: unknown): value is Handle
export declare function isReadRequest(value: unknown): value is ReadRequest
export declare function isReadResult(value: unknown): value is ReadResult
export declare function isRevokeRequest(value: unknown): value is RevokeRequest
export declare function isRevokeResult(value: unknown): value is RevokeResult
