// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  Append: Object.freeze({"name":"cmd.gateway.payloads.v1.append","kind":"command","rev":1,"schema":"0bd4f9e5bd5d9ce6153b0cdece50dc0993b52cb8b079c5396a297a7e1e1593f3","subject":"cmd.gateway.payloads.v1.append"}),
  Commit: Object.freeze({"name":"cmd.gateway.payloads.v1.commit","kind":"command","rev":1,"schema":"60a3e35c2a79aeca604f4f6099d12ab8f0b2b6c02270307d58627a5210aa67a2","subject":"cmd.gateway.payloads.v1.commit"}),
  Create: Object.freeze({"name":"cmd.gateway.payloads.v1.create","kind":"command","rev":1,"schema":"5e7ab3b8fa044a4c14a62842ac068f75b6ff64f8d8ab2f264bda8e40374236d1","subject":"cmd.gateway.payloads.v1.create"}),
  Read: Object.freeze({"name":"cmd.gateway.payloads.v1.read","kind":"command","rev":1,"schema":"46427af3bee4250bd7cbdfab4b1c94d86f74f85a74a2279b2a011386b34d22d1","subject":"cmd.gateway.payloads.v1.read"}),
  Revoke: Object.freeze({"name":"cmd.gateway.payloads.v1.revoke","kind":"command","rev":1,"schema":"0525aff67f7d1eac044fcc724b594fe33b6433a3ca0473b039d02ce4d2fa2a39","subject":"cmd.gateway.payloads.v1.revoke"}),
})
