// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isAppendRequest(value) {
  if (!record(value)) return false
  if (!(value.invocationId === undefined || str(value.invocationId))) return false
  if (!(str(value.handleId))) return false
  if (!(dec(value.offset))) return false
  if (!(str(value.data))) return false
  return true
}

export function isAppendResult(value) {
  if (!record(value)) return false
  if (!(dec(value.nextOffset))) return false
  return true
}

export function isCommitRequest(value) {
  if (!record(value)) return false
  if (!(value.invocationId === undefined || str(value.invocationId))) return false
  if (!(str(value.handleId))) return false
  return true
}

export function isCommitResult(value) {
  if (!record(value)) return false
  if (!(isHandle(value.handle))) return false
  return true
}

export function isCreateRequest(value) {
  if (!record(value)) return false
  if (!(value.invocationId === undefined || str(value.invocationId))) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.purpose))) return false
  if (!(dec(value.size))) return false
  if (!(str(value.sha256))) return false
  if (!(value.ttlSeconds === undefined || num(value.ttlSeconds))) return false
  return true
}

export function isCreateResult(value) {
  if (!record(value)) return false
  if (!(isHandle(value.handle))) return false
  return true
}

export function isHandle(value) {
  if (!record(value)) return false
  if (!(str(value.id))) return false
  if (!(str(value.providerId))) return false
  if (!(str(value.providerGeneration))) return false
  if (!(str(value.purpose))) return false
  if (!(dec(value.size))) return false
  if (!(str(value.sha256))) return false
  if (!(str(value.expiresAt))) return false
  if (!(str(value.state))) return false
  return true
}

export function isReadRequest(value) {
  if (!record(value)) return false
  if (!(value.invocationId === undefined || str(value.invocationId))) return false
  if (!(str(value.handleId))) return false
  if (!(dec(value.offset))) return false
  if (!(num(value.limit))) return false
  return true
}

export function isReadResult(value) {
  if (!record(value)) return false
  if (!(str(value.data))) return false
  if (!(dec(value.nextOffset))) return false
  if (!(bool(value.eof))) return false
  return true
}

export function isRevokeRequest(value) {
  if (!record(value)) return false
  if (!(value.invocationId === undefined || str(value.invocationId))) return false
  if (!(str(value.handleId))) return false
  return true
}

export function isRevokeResult(value) {
  if (!record(value)) return false
  if (!(bool(value.revoked))) return false
  return true
}
