// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

export interface ChangedEvent {
  cursor: string
  conversationId?: string
  endpointIds?: string[]
  sequence: string
  changedAt: string
}

export interface Conversation {
  conversationId: string
  ownerEndpointId: string
  participantEndpointIds: string[] | null
  createdAt: string
  updatedAt: string
}

export interface ConversationOpenRequest {
  conversationId: string
  ownerEndpointId: string
  participantEndpointIds: string[] | null
}

export interface ConversationOpenResult {
  status: OperationStatus
  conversation?: Conversation
}

export interface DeliveryUpdateRequest {
  messageId: string
  adapterId: string
  fromState: string
  toState: string
  attempt: string
  updatedAt: string
  fault?: Fault
}

export interface DeliveryUpdateResult {
  status: OperationStatus
  delivery?: MessageDelivery
}

export interface EndpointIdentity {
  endpointId: string
  actorId: string
  displayName: string
  title: string
  provider: string
  sourcePlugin: string
}

export interface EndpointRemoveRequest {
  endpointId: string
}

export interface EndpointRemoveResult {
  status: OperationStatus
  endpointId?: string
}

export interface EndpointUpsertRequest {
  endpoint: EndpointIdentity
}

export interface EndpointUpsertResult {
  status: OperationStatus
  endpoint?: EndpointIdentity
}

export interface Fault {
  code: string
  message?: string
}

export interface IdempotencyRecord {
  ownerEndpointId: string
  key: string
  payloadHash: string
  messageId: string
  createdAt: string
  expiresAt: string
}

export interface InboxConversationSummary {
  conversationId: string
  unreadCount: string
  latestMessageId?: string
  latestSequence: string
  updatedAt: string
}

export interface InboxSummaryRequest {
  endpointId: string
}

export interface InboxSummaryResult {
  status: OperationStatus
  endpointId?: string
  unreadCount: string
  conversations?: InboxConversationSummary[]
}

export interface Message {
  messageId: string
  conversationId: string
  sender: EndpointIdentity
  body: string
  kind: string
  metadata?: MetadataEntry[]
  references?: MessageReference[]
  sequence: string
  createdAt: string
  delivery: MessageDelivery
}

export interface MessageDelivery {
  state: string
  adapterId?: string
  attempt: string
  updatedAt: string
  fault?: Fault
}

export interface MessageListRequest {
  conversationId: string
  requesterEndpointId: string
  afterCursor?: string
  limit?: number
}

export interface MessageListResult {
  status: OperationStatus
  messages?: Message[]
  nextCursor?: string
  hasMore: boolean
}

export interface MessageReference {
  kind: string
  id: string
  label?: string
}

export interface MessageSendRequest {
  conversationId: string
  senderEndpointId: string
  body: string
  kind: string
  metadata?: MetadataEntry[]
  references?: MessageReference[]
  idempotencyKey: string
}

export interface MessageSendResult {
  status: OperationStatus
  message?: Message
}

export interface MetadataEntry {
  key: string
  value: string
}

export interface OperationStatus {
  ok: boolean
  fault?: Fault
}

export interface Receipt {
  endpointId: string
  conversationId: string
  throughSequence: string
  acknowledgedAt: string
}

export interface ReceiptAckRequest {
  endpointId: string
  conversationId: string
  throughSequence: string
}

export interface ReceiptAckResult {
  status: OperationStatus
  receipt?: Receipt
}

// Runtime shape guards. The paired JS module exports one per declaration
// above; they check structure only, not the host's security invariants.
export declare function isChangedEvent(value: unknown): value is ChangedEvent
export declare function isConversation(value: unknown): value is Conversation
export declare function isConversationOpenRequest(value: unknown): value is ConversationOpenRequest
export declare function isConversationOpenResult(value: unknown): value is ConversationOpenResult
export declare function isDeliveryUpdateRequest(value: unknown): value is DeliveryUpdateRequest
export declare function isDeliveryUpdateResult(value: unknown): value is DeliveryUpdateResult
export declare function isEndpointIdentity(value: unknown): value is EndpointIdentity
export declare function isEndpointRemoveRequest(value: unknown): value is EndpointRemoveRequest
export declare function isEndpointRemoveResult(value: unknown): value is EndpointRemoveResult
export declare function isEndpointUpsertRequest(value: unknown): value is EndpointUpsertRequest
export declare function isEndpointUpsertResult(value: unknown): value is EndpointUpsertResult
export declare function isFault(value: unknown): value is Fault
export declare function isIdempotencyRecord(value: unknown): value is IdempotencyRecord
export declare function isInboxConversationSummary(value: unknown): value is InboxConversationSummary
export declare function isInboxSummaryRequest(value: unknown): value is InboxSummaryRequest
export declare function isInboxSummaryResult(value: unknown): value is InboxSummaryResult
export declare function isMessage(value: unknown): value is Message
export declare function isMessageDelivery(value: unknown): value is MessageDelivery
export declare function isMessageListRequest(value: unknown): value is MessageListRequest
export declare function isMessageListResult(value: unknown): value is MessageListResult
export declare function isMessageReference(value: unknown): value is MessageReference
export declare function isMessageSendRequest(value: unknown): value is MessageSendRequest
export declare function isMessageSendResult(value: unknown): value is MessageSendResult
export declare function isMetadataEntry(value: unknown): value is MetadataEntry
export declare function isOperationStatus(value: unknown): value is OperationStatus
export declare function isReceipt(value: unknown): value is Receipt
export declare function isReceiptAckRequest(value: unknown): value is ReceiptAckRequest
export declare function isReceiptAckResult(value: unknown): value is ReceiptAckResult
