// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

// Descriptors are frozen: a page that could rewrite a subject or a schema
// hash could address a contract it was never granted.
export const descriptors = Object.freeze({
  AckReceipt: Object.freeze({"name":"cmd.messaging.v1.receipt.ack","kind":"command","rev":1,"schema":"77457b2d6b9033b5118b5e4123a9fe05ed9580e85e214e38b0153dccd02ed496","subject":"cmd.messaging.v1.receipt.ack"}),
  Changed: Object.freeze({"name":"event.messaging.v1.changed","kind":"event","rev":1,"schema":"24b3130d757afbbd8a16a46b9d6cab08b850c3fc2204f6aba26e0c5cdc3a2bf5","subject":"event.messaging.v1.changed"}),
  GetInboxSummary: Object.freeze({"name":"cmd.messaging.v1.inbox.summary","kind":"command","rev":1,"schema":"a1c53b1e3df90e7fe48695a39d3753bd071cbb195df6da99b91e6db18c3dbab2","subject":"cmd.messaging.v1.inbox.summary"}),
  ListMessages: Object.freeze({"name":"cmd.messaging.v1.message.list","kind":"command","rev":1,"schema":"fa6f64b53d2120e515ceba2d1b45b3eccecdc38bfc36b10a9580754f1e53c626","subject":"cmd.messaging.v1.message.list"}),
  OpenConversation: Object.freeze({"name":"cmd.messaging.v1.conversation.open","kind":"command","rev":1,"schema":"2435c8fb24dc2fc91a8dcc1e01a63909c6fd83f86e8812b600d49026aaa96556","subject":"cmd.messaging.v1.conversation.open"}),
  RemoveEndpoint: Object.freeze({"name":"cmd.messaging.v1.endpoint.remove","kind":"command","rev":1,"schema":"a0099030b38aec33073ebab7095bed8b860473ac467495ea1e5fcb72afa8516a","subject":"cmd.messaging.v1.endpoint.remove"}),
  SendMessage: Object.freeze({"name":"cmd.messaging.v1.message.send","kind":"command","rev":1,"schema":"dbba749407821a6aa5fb9b401c6597c2044e47cfdfdab8557c6e48e31af39de4","subject":"cmd.messaging.v1.message.send"}),
  UpdateDelivery: Object.freeze({"name":"cmd.messaging.v1.delivery.update","kind":"command","rev":1,"schema":"42365b00e9c57e8a25041cf92760f94848b0fb369f1116f062499f26a2854efe","subject":"cmd.messaging.v1.delivery.update"}),
  UpsertEndpoint: Object.freeze({"name":"cmd.messaging.v1.endpoint.upsert","kind":"command","rev":1,"schema":"8ef7e61e2ef6452431e6aa81f8fa08fb7f0401aa92d4f7570aefe7958f64ce61","subject":"cmd.messaging.v1.endpoint.upsert"}),
})
