// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.

const record = (v) => v !== null && typeof v === 'object' && !Array.isArray(v)
const decimal = /^-?(0|[1-9][0-9]*)$/
const str = (v) => typeof v === 'string'
const bool = (v) => typeof v === 'boolean'
const num = (v) => typeof v === 'number' && Number.isFinite(v)
const dec = (v) => str(v) && decimal.test(v)
const list = (v, of) => Array.isArray(v) && v.every(of)

export function isChangedEvent(value) {
  if (!record(value)) return false
  if (!(str(value.cursor))) return false
  if (!(value.conversationId === undefined || str(value.conversationId))) return false
  if (!(value.endpointIds === undefined || list(value.endpointIds, str))) return false
  if (!(dec(value.sequence))) return false
  if (!(str(value.changedAt))) return false
  return true
}

export function isConversation(value) {
  if (!record(value)) return false
  if (!(str(value.conversationId))) return false
  if (!(str(value.ownerEndpointId))) return false
  if (!(value.participantEndpointIds === null || list(value.participantEndpointIds, str))) return false
  if (!(str(value.createdAt))) return false
  if (!(str(value.updatedAt))) return false
  return true
}

export function isConversationOpenRequest(value) {
  if (!record(value)) return false
  if (!(str(value.conversationId))) return false
  if (!(str(value.ownerEndpointId))) return false
  if (!(value.participantEndpointIds === null || list(value.participantEndpointIds, str))) return false
  return true
}

export function isConversationOpenResult(value) {
  if (!record(value)) return false
  if (!(isOperationStatus(value.status))) return false
  if (!(value.conversation === undefined || isConversation(value.conversation))) return false
  return true
}

export function isDeliveryUpdateRequest(value) {
  if (!record(value)) return false
  if (!(str(value.messageId))) return false
  if (!(str(value.adapterId))) return false
  if (!(str(value.fromState))) return false
  if (!(str(value.toState))) return false
  if (!(dec(value.attempt))) return false
  if (!(str(value.updatedAt))) return false
  if (!(value.fault === undefined || isFault(value.fault))) return false
  return true
}

export function isDeliveryUpdateResult(value) {
  if (!record(value)) return false
  if (!(isOperationStatus(value.status))) return false
  if (!(value.delivery === undefined || isMessageDelivery(value.delivery))) return false
  return true
}

export function isEndpointIdentity(value) {
  if (!record(value)) return false
  if (!(str(value.endpointId))) return false
  if (!(str(value.actorId))) return false
  if (!(str(value.displayName))) return false
  if (!(str(value.title))) return false
  if (!(str(value.provider))) return false
  if (!(str(value.sourcePlugin))) return false
  return true
}

export function isEndpointRemoveRequest(value) {
  if (!record(value)) return false
  if (!(str(value.endpointId))) return false
  return true
}

export function isEndpointRemoveResult(value) {
  if (!record(value)) return false
  if (!(isOperationStatus(value.status))) return false
  if (!(value.endpointId === undefined || str(value.endpointId))) return false
  return true
}

export function isEndpointUpsertRequest(value) {
  if (!record(value)) return false
  if (!(isEndpointIdentity(value.endpoint))) return false
  return true
}

export function isEndpointUpsertResult(value) {
  if (!record(value)) return false
  if (!(isOperationStatus(value.status))) return false
  if (!(value.endpoint === undefined || isEndpointIdentity(value.endpoint))) return false
  return true
}

export function isFault(value) {
  if (!record(value)) return false
  if (!(str(value.code))) return false
  if (!(value.message === undefined || str(value.message))) return false
  return true
}

export function isIdempotencyRecord(value) {
  if (!record(value)) return false
  if (!(str(value.ownerEndpointId))) return false
  if (!(str(value.key))) return false
  if (!(str(value.payloadHash))) return false
  if (!(str(value.messageId))) return false
  if (!(str(value.createdAt))) return false
  if (!(str(value.expiresAt))) return false
  return true
}

export function isInboxConversationSummary(value) {
  if (!record(value)) return false
  if (!(str(value.conversationId))) return false
  if (!(dec(value.unreadCount))) return false
  if (!(value.latestMessageId === undefined || str(value.latestMessageId))) return false
  if (!(dec(value.latestSequence))) return false
  if (!(str(value.updatedAt))) return false
  return true
}

export function isInboxSummaryRequest(value) {
  if (!record(value)) return false
  if (!(str(value.endpointId))) return false
  return true
}

export function isInboxSummaryResult(value) {
  if (!record(value)) return false
  if (!(isOperationStatus(value.status))) return false
  if (!(value.endpointId === undefined || str(value.endpointId))) return false
  if (!(dec(value.unreadCount))) return false
  if (!(value.conversations === undefined || list(value.conversations, isInboxConversationSummary))) return false
  return true
}

export function isMessage(value) {
  if (!record(value)) return false
  if (!(str(value.messageId))) return false
  if (!(str(value.conversationId))) return false
  if (!(isEndpointIdentity(value.sender))) return false
  if (!(str(value.body))) return false
  if (!(str(value.kind))) return false
  if (!(value.metadata === undefined || list(value.metadata, isMetadataEntry))) return false
  if (!(value.references === undefined || list(value.references, isMessageReference))) return false
  if (!(dec(value.sequence))) return false
  if (!(str(value.createdAt))) return false
  if (!(isMessageDelivery(value.delivery))) return false
  return true
}

export function isMessageDelivery(value) {
  if (!record(value)) return false
  if (!(str(value.state))) return false
  if (!(value.adapterId === undefined || str(value.adapterId))) return false
  if (!(dec(value.attempt))) return false
  if (!(str(value.updatedAt))) return false
  if (!(value.fault === undefined || isFault(value.fault))) return false
  return true
}

export function isMessageListRequest(value) {
  if (!record(value)) return false
  if (!(str(value.conversationId))) return false
  if (!(str(value.requesterEndpointId))) return false
  if (!(value.afterCursor === undefined || str(value.afterCursor))) return false
  if (!(value.limit === undefined || num(value.limit))) return false
  return true
}

export function isMessageListResult(value) {
  if (!record(value)) return false
  if (!(isOperationStatus(value.status))) return false
  if (!(value.messages === undefined || list(value.messages, isMessage))) return false
  if (!(value.nextCursor === undefined || str(value.nextCursor))) return false
  if (!(bool(value.hasMore))) return false
  return true
}

export function isMessageReference(value) {
  if (!record(value)) return false
  if (!(str(value.kind))) return false
  if (!(str(value.id))) return false
  if (!(value.label === undefined || str(value.label))) return false
  return true
}

export function isMessageSendRequest(value) {
  if (!record(value)) return false
  if (!(str(value.conversationId))) return false
  if (!(str(value.senderEndpointId))) return false
  if (!(str(value.body))) return false
  if (!(str(value.kind))) return false
  if (!(value.metadata === undefined || list(value.metadata, isMetadataEntry))) return false
  if (!(value.references === undefined || list(value.references, isMessageReference))) return false
  if (!(str(value.idempotencyKey))) return false
  return true
}

export function isMessageSendResult(value) {
  if (!record(value)) return false
  if (!(isOperationStatus(value.status))) return false
  if (!(value.message === undefined || isMessage(value.message))) return false
  return true
}

export function isMetadataEntry(value) {
  if (!record(value)) return false
  if (!(str(value.key))) return false
  if (!(str(value.value))) return false
  return true
}

export function isOperationStatus(value) {
  if (!record(value)) return false
  if (!(bool(value.ok))) return false
  if (!(value.fault === undefined || isFault(value.fault))) return false
  return true
}

export function isReceipt(value) {
  if (!record(value)) return false
  if (!(str(value.endpointId))) return false
  if (!(str(value.conversationId))) return false
  if (!(dec(value.throughSequence))) return false
  if (!(str(value.acknowledgedAt))) return false
  return true
}

export function isReceiptAckRequest(value) {
  if (!record(value)) return false
  if (!(str(value.endpointId))) return false
  if (!(str(value.conversationId))) return false
  if (!(dec(value.throughSequence))) return false
  return true
}

export function isReceiptAckResult(value) {
  if (!record(value)) return false
  if (!(isOperationStatus(value.status))) return false
  if (!(value.receipt === undefined || isReceipt(value.receipt))) return false
  return true
}
